-- PostgreSQL primary migration 0050 (staged): admin audit and collection
-- controls hardening.
--
-- Brings the two owner-operation tables to D1 parity before any PostgreSQL
-- admin writer exists:
--
--   * admin_action_audit (0007) keyed audit rows by a NOT NULL operation_id.
--     D1 (migrations/0019, rebuilt by 0037) keys them by an AUTOINCREMENT id,
--     keeps operation_id UNIQUE but nullable (legacy rows carry NULL), closes
--     the action vocabulary and bounds details_json at 2000 characters.  The
--     identity id here is GENERATED BY DEFAULT so an import can carry the
--     sealed D1 ids verbatim; ON CONFLICT (operation_id) keeps working through
--     the UNIQUE constraint.  Rows are append-only: the only permitted update
--     is started -> success | failure with every identity column unchanged,
--     and DELETE and TRUNCATE are refused.
--   * collection_controls (0007, revision >= 1 since 0016) left reason_code
--     nullable and open, and did not tie control_state to its four flags.  D1
--     (migrations/0009) makes both closed.  The Worker reader
--     (src/collection-controls.ts) already refuses an inconsistent row, so the
--     database now refuses to store one.
--
-- Fail-closed backfill: only a NULL reason_code is normalized (to 'initial',
-- the D1 bootstrap reason).  Any other out-of-vocabulary reason, inconsistent
-- state/flag row, unknown audit action, over-long details or malformed
-- operation_id makes the ADD CONSTRAINT validation fail, so the migration
-- aborts and the schema stays at its previous version rather than silently
-- rewriting owner state.  No participant column is added; neither table
-- carries owner_digest.  Every RAISE carries a constant message and ERRCODE.

-- (1) admin_action_audit: identity id, backfilled in creation order.
ALTER TABLE admin_action_audit ADD COLUMN id bigint;

UPDATE admin_action_audit audit
   SET id = ordered.position
  FROM (
    SELECT operation_id,
           row_number() OVER (ORDER BY created_at, operation_id COLLATE "C") AS position
      FROM admin_action_audit
  ) ordered
 WHERE ordered.operation_id = audit.operation_id;

ALTER TABLE admin_action_audit
  ALTER COLUMN id SET NOT NULL,
  ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

SELECT setval(pg_get_serial_sequence('admin_action_audit', 'id'),
              COALESCE(max(id), 0) + 1, false)
  FROM admin_action_audit;

-- (2) Re-key: id becomes the primary key; operation_id becomes a nullable
-- UNIQUE key.  NULLs stay distinct, so any number of imported legacy rows may
-- omit it, while a non-null operation_id remains the idempotency key.
ALTER TABLE admin_action_audit DROP CONSTRAINT admin_action_audit_pkey;
ALTER TABLE admin_action_audit ALTER COLUMN operation_id DROP NOT NULL;
ALTER TABLE admin_action_audit
  ADD CONSTRAINT admin_action_audit_pkey PRIMARY KEY (id);
ALTER TABLE admin_action_audit
  ADD CONSTRAINT admin_action_audit_operation_id_key UNIQUE (operation_id),
  ADD CONSTRAINT admin_action_audit_operation_id_check
    CHECK (operation_id IS NULL OR char_length(operation_id) = 36),
  ADD CONSTRAINT admin_action_audit_action_check
    CHECK (action IN ('set_collection_controls', 'run_maintenance', 'sync_distribution')),
  ADD CONSTRAINT admin_action_audit_details_json_check
    CHECK (char_length(details_json) <= 2000);

-- (3) Read paths: the owner console's recent-actions list (D1
-- admin_action_audit_recent) and the participant-erasure lease, which looks
-- for a started run_maintenance row carrying the same participantDigest.
CREATE INDEX admin_action_audit_recent
  ON admin_action_audit (created_at DESC, id DESC);
CREATE INDEX admin_action_audit_started_participant
  ON admin_action_audit (((details_json::jsonb) ->> 'participantDigest'))
  WHERE outcome = 'started' AND action = 'run_maintenance';

-- (4) Append-only lifecycle.  Inserts are unrestricted beyond the table
-- constraints (live begins insert 'started'; an import carries terminal
-- rows).  An update must move a started row to a terminal outcome and may
-- rewrite only outcome and details_json.
CREATE FUNCTION admin_action_audit_lifecycle_guard()
RETURNS trigger
LANGUAGE plpgsql SET search_path FROM CURRENT AS $$
BEGIN
  IF TG_OP = 'DELETE' THEN
    RAISE EXCEPTION 'admin_action_audit_delete_refused' USING ERRCODE = 'P1005';
  END IF;
  IF OLD.outcome <> 'started'
     OR NEW.outcome NOT IN ('success', 'failure')
     OR NEW.id IS DISTINCT FROM OLD.id
     OR NEW.operation_id IS DISTINCT FROM OLD.operation_id
     OR NEW.action IS DISTINCT FROM OLD.action
     OR NEW.actor_identity_digest IS DISTINCT FROM OLD.actor_identity_digest
     OR NEW.created_at IS DISTINCT FROM OLD.created_at THEN
    RAISE EXCEPTION 'admin_action_audit_transition_refused' USING ERRCODE = 'P1005';
  END IF;
  RETURN NEW;
END;
$$;
CREATE TRIGGER admin_action_audit_lifecycle_guard
  BEFORE UPDATE OR DELETE ON admin_action_audit
  FOR EACH ROW EXECUTE FUNCTION admin_action_audit_lifecycle_guard();

CREATE FUNCTION admin_action_audit_no_truncate()
RETURNS trigger
LANGUAGE plpgsql SET search_path FROM CURRENT AS $$
BEGIN
  RAISE EXCEPTION 'admin_action_audit_truncate_refused' USING ERRCODE = 'P1005';
END;
$$;
CREATE TRIGGER admin_action_audit_no_truncate
  BEFORE TRUNCATE ON admin_action_audit
  FOR EACH STATEMENT EXECUTE FUNCTION admin_action_audit_no_truncate();

-- (5) collection_controls: closed reason vocabulary.  Only the reason column
-- is written, so the 0042/0043 import-fence guards (BEFORE UPDATE OF
-- control_state, enrollment_enabled, publication_enabled) do not fire and the
-- revision is not advanced: this is a representation fix, not a control
-- change.
UPDATE collection_controls
   SET reason_code = 'initial'
 WHERE reason_code IS NULL;
ALTER TABLE collection_controls ALTER COLUMN reason_code SET NOT NULL;

-- (6) collection_controls: state follows the flags exactly as D1 0009 and the
-- Worker reader define it: operational = all four on, contained = all four
-- off, degraded = any mix.
ALTER TABLE collection_controls
  ADD CONSTRAINT collection_controls_reason_code_check CHECK (
    reason_code IN (
      'initial',
      'drill_containment',
      'drill_restore',
      'privacy_incident',
      'security_incident',
      'abuse_or_cost',
      'maintenance'
    )
  ),
  ADD CONSTRAINT collection_controls_state_flags_check CHECK (
    (control_state = 'operational'
      AND enrollment_enabled
      AND upload_registration_enabled
      AND processing_enabled
      AND publication_enabled)
    OR
    (control_state = 'contained'
      AND NOT enrollment_enabled
      AND NOT upload_registration_enabled
      AND NOT processing_enabled
      AND NOT publication_enabled)
    OR
    (control_state = 'degraded'
      AND NOT (enrollment_enabled
        AND upload_registration_enabled
        AND processing_enabled
        AND publication_enabled)
      AND NOT (NOT enrollment_enabled
        AND NOT upload_registration_enabled
        AND NOT processing_enabled
        AND NOT publication_enabled))
  );
