import { ApiError } from "./errors";
import type {
  AppleSignInHandoffStore,
  GoogleDeliveredSignInHandoff,
  GooglePendingSignInHandoff,
  GoogleSignInHandoffInsert,
  GoogleSignInHandoffStore,
  IdentityHandoffBackend,
} from "./identity-handoff-backend";
import { createD1IdentityHandoffBackend } from "./d1-identity-handoff-backend";

/**
 * The Apple state row is deliberately kept behind a tiny repository surface.
 * Callers pass the state-row nonce digest, never the raw nonce or an ID token.
 * Callback operations remain single-claim and time-bounded. Result delivery is
 * idempotent for the same state+verifier so a client can recover after a crash;
 * enrollment remains the one-use sink that deletes the proof row.
 *
 * `expires_at` is phase-dependent and always holds the deadline of the phase
 * the row is in: while the row is empty it is the authorization deadline set
 * by the start route, and the write that fills the row replaces it with the
 * delivery deadline of the proof minted by that same write. A row is therefore
 * bounded by exactly one live deadline at any moment, which is why the purge
 * query, its index, and the rule that an expired-but-filled row reads as
 * invalid rather than pending are all unaffected. `created_at` is retained, so
 * the authorization deadline of a filled row is still reconstructible.
 */

const INSTANT_PATTERN = /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/u;
const NONCE_HASH_PATTERN = /^[0-9a-f]{64}$/u;
const LINK_KEY_PATTERN = /^[0-9a-f]{64}$/u;
const PROOF_PATTERN = /^[A-Za-z0-9_-]{64}$/u;
// SHA-256(verifier), lowercase hex. The verifier is generated by and held only
// on the initiating client; the raw verifier never reaches this table.
const BINDING_HASH_PATTERN = /^[0-9a-f]{64}$/u;

type AppleHandoffSource = D1Database | AppleSignInHandoffStore | IdentityHandoffBackend;
type GoogleHandoffSource = D1Database | GoogleSignInHandoffStore | IdentityHandoffBackend;
export type IdentityHandoffSource = D1Database | IdentityHandoffBackend;

function handoffStore(source: AppleHandoffSource): AppleSignInHandoffStore {
  if (typeof (source as Partial<IdentityHandoffBackend>).apple?.readPending === "function") {
    return (source as IdentityHandoffBackend).apple;
  }
  if (typeof (source as Partial<AppleSignInHandoffStore>).readPending === "function") {
    return source as AppleSignInHandoffStore;
  }
  return createD1IdentityHandoffBackend(source as D1Database).apple;
}

function googleHandoffStore(source: GoogleHandoffSource): GoogleSignInHandoffStore {
  if (typeof (source as Partial<IdentityHandoffBackend>).google?.readPending === "function") {
    return (source as IdentityHandoffBackend).google;
  }
  if (typeof (source as Partial<GoogleSignInHandoffStore>).readPending === "function") {
    return source as GoogleSignInHandoffStore;
  }
  return createD1IdentityHandoffBackend(source as D1Database).google;
}

function providerStore(
  source: IdentityHandoffSource,
  provider: "apple" | "google",
): AppleSignInHandoffStore | GoogleSignInHandoffStore {
  if (provider === "apple") {
    if (typeof (source as Partial<IdentityHandoffBackend>).apple?.readPending === "function") {
      return (source as IdentityHandoffBackend).apple;
    }
    return createD1IdentityHandoffBackend(source as D1Database).apple;
  }
  if (typeof (source as Partial<IdentityHandoffBackend>).google?.readPending === "function") {
    return (source as IdentityHandoffBackend).google;
  }
  return createD1IdentityHandoffBackend(source as D1Database).google;
}

export interface AppleSignInHandoffInsert {
  readonly state: string;
  readonly nonceHash: string;
  readonly bindingHash: string;
  readonly createdAt: string;
  readonly expiresAt: string;
}

export interface ApplePendingSignInHandoff {
  readonly state: string;
  readonly nonceHash: string;
}

export interface AppleDeliveredSignInHandoff {
  readonly proof: string;
}

function internalError(): never {
  throw new ApiError(500, "INTERNAL_ERROR");
}

function assertNonceHash(value: string): void {
  if (!NONCE_HASH_PATTERN.test(value)) internalError();
}

function assertBindingHash(value: string): void {
  if (!BINDING_HASH_PATTERN.test(value)) internalError();
}

function assertIdentityLinkKey(value: string): void {
  if (!LINK_KEY_PATTERN.test(value)) internalError();
}

function assertProof(value: string): void {
  if (!PROOF_PATTERN.test(value)) internalError();
}

function assertInstant(value: string): void {
  if (!INSTANT_PATTERN.test(value)) internalError();
}

/** Inserts an empty, live Apple transaction before redirecting to Apple. */
export async function insertAppleSignInHandoff(
  db: AppleHandoffSource,
  handoff: AppleSignInHandoffInsert,
): Promise<void> {
  assertNonceHash(handoff.nonceHash);
  assertBindingHash(handoff.bindingHash);
  await handoffStore(db).insert(handoff);
}

/**
 * Returns the nonce digest only for an empty, live row.  An unknown, filled,
 * delivered, or expired state is indistinguishable from no callback attempt.
 */
export async function readPendingAppleSignInHandoff(
  db: AppleHandoffSource,
  state: string,
  nowIso: string,
  bindingHash?: string,
): Promise<ApplePendingSignInHandoff | null> {
  // The provider callback has no verifier and passes no binding, so it reads a
  // pending row on state alone. The result route passes the initiator's binding
  // so that a caller who holds the state but not the verifier cannot even learn
  // that a sign-in is pending.
  const bindingProvided = bindingHash !== undefined;
  if (bindingProvided) assertBindingHash(bindingHash);
  const row = await handoffStore(db).readPending({ state, nowIso, ...(bindingProvided ? { bindingHash } : {}) });
  if (!row || !NONCE_HASH_PATTERN.test(row.nonceHash)) return null;
  return row;
}

/**
 * Atomically reserves a pending handoff before any provider I/O. Exactly one of
 * many racing callbacks wins this conditional UPDATE and receives the nonce
 * digest; every other callback sees zero changes and must stop before signing a
 * client secret or contacting the provider. `claimed_at` is a lease: a claim
 * older than `staleClaimBeforeIso` is re-claimable, so a crashed claimant frees
 * the row for one bounded retry rather than stranding the sign-in for its whole
 * authorization window. The returned `claimId` fences completion and discard.
 */
export async function claimPendingAppleSignInHandoff(
  db: AppleHandoffSource,
  state: string,
  claimId: string,
  nowIso: string,
  staleClaimBeforeIso: string,
): Promise<ApplePendingSignInHandoff | null> {
  assertProof(claimId);
  assertInstant(nowIso);
  assertInstant(staleClaimBeforeIso);
  const row = await handoffStore(db).claim({ state, claimId, nowIso, staleClaimBeforeIso });
  if (!row || !NONCE_HASH_PATTERN.test(row.nonceHash)) return null;
  return row;
}

/**
 * Atomically fills a pending handoff with the already verified pairwise link
 * key and a fresh opaque proof.  A false result means it expired, was filled,
 * was delivered, or was re-claimed by another callback while provider
 * verification was in flight.
 *
 * The same statement moves the row from its authorization phase into its
 * delivery phase: the WHERE clause still enforces the authorization deadline
 * (SQLite evaluates it against the pre-update row), while `expires_at` is
 * rewritten to the window the freshly minted proof gets from this instant.
 * The caller must pass a deadline strictly after `nowIso`, so a proof can
 * never be minted already expired or expire before it is first collectable.
 */
export async function completeAppleSignInHandoff(
  db: AppleHandoffSource,
  state: string,
  claimId: string,
  identityLinkKey: string,
  proof: string,
  nowIso: string,
  deliveryExpiresAtIso: string,
): Promise<boolean> {
  assertProof(claimId);
  assertIdentityLinkKey(identityLinkKey);
  assertProof(proof);
  // Both instants are canonical `toISOString()` output, so the ordering
  // comparison below is a lexicographic one on identical formats. Rejecting
  // any other shape is what makes that comparison sound rather than lucky.
  assertInstant(nowIso);
  assertInstant(deliveryExpiresAtIso);
  if (!(deliveryExpiresAtIso > nowIso)) internalError();
  // Completion is fenced to the claimant: a callback whose claim was preempted
  // by a lease-expiry re-claim writes zero rows here and reports failure.
  return handoffStore(db).complete({
    state, claimId, identityLinkKey, proof, nowIso, deliveryExpiresAtIso,
  });
}

/**
 * Delivers a proof idempotently to the same state+verifier until the caller
 * consumes it through the existing enrollment path or it expires. This row
 * operation never writes participant, session, or device state.
 */
export async function deliverAppleSignInHandoff(
  db: AppleHandoffSource,
  state: string,
  nowIso: string,
  bindingHash: string,
): Promise<AppleDeliveredSignInHandoff | null> {
  // The proof is released only to a caller that re-presents the initiator's
  // verifier: `binding_hash` must match SHA-256(verifier). A caller holding the
  // state but not the verifier updates zero rows, so the proof is neither
  // delivered nor marked consumed and remains collectable by the initiator.
  assertBindingHash(bindingHash);
  const row = await handoffStore(db).deliver({ state, nowIso, bindingHash });
  if (!row || !PROOF_PATTERN.test(row.proof)) return null;
  return row;
}

export async function consumeAppleSignInHandoff(
  db: AppleHandoffSource,
  proof: string,
  bindingHash: string,
  nowIso: string,
): Promise<{ linkKeyHex: string } | null> {
  assertProof(proof);
  assertBindingHash(bindingHash);
  assertInstant(nowIso);
  const row = await handoffStore(db).consume({ proof, bindingHash, nowIso });
  if (!row || !LINK_KEY_PATTERN.test(row.linkKeyHex)) return null;
  return row;
}

export async function hasExpiredAppleSignInHandoffs(
  db: AppleHandoffSource,
  nowIso: string,
): Promise<boolean> {
  assertInstant(nowIso);
  return handoffStore(db).hasExpired({ nowIso });
}

/**
 * Deletes a live, still-empty, UNCLAIMED handoff after a provider cancellation
 * that arrives before any callback has claimed the row. The `claim_id IS NULL`
 * predicate is the fence: a cancellation callback can never delete a row another
 * callback is already processing — that claimant discards its own row on failure
 * through `discardClaimedAppleSignInHandoff`.
 */
export async function discardPendingAppleSignInHandoff(
  db: AppleHandoffSource,
  state: string,
  nowIso: string,
): Promise<void> {
  await handoffStore(db).discardPending({ state, nowIso });
}

/**
 * Discards a handoff the caller currently holds the claim on, after its own
 * provider exchange failed. Fenced to `claimId`: a callback that lost its claim
 * to a lease-expiry re-claim deletes nothing, so it can never remove the row the
 * new claimant is processing.
 */
export async function discardClaimedAppleSignInHandoff(
  db: AppleHandoffSource,
  state: string,
  claimId: string,
  nowIso: string,
): Promise<void> {
  assertProof(claimId);
  await handoffStore(db).discardClaimed({ state, claimId, nowIso });
}

/** Purges expired rows in a bounded batch for scheduled/opportunistic cleanup. */
export async function deleteExpiredAppleSignInHandoffs(
  db: AppleHandoffSource,
  nowIso: string,
  maximumRows = 100,
): Promise<number> {
  if (!Number.isInteger(maximumRows) || maximumRows < 1 || maximumRows > 1000) {
    internalError();
  }
  return handoffStore(db).purge({ nowIso, maximumRows });
}

const VERIFIER_PATTERN = /^[A-Za-z0-9_-]{43,128}$/u;

export async function insertGoogleSignInHandoff(
  db: GoogleHandoffSource,
  handoff: GoogleSignInHandoffInsert,
): Promise<void> {
  if (!VERIFIER_PATTERN.test(handoff.codeVerifier)) internalError();
  assertBindingHash(handoff.bindingHash);
  await googleHandoffStore(db).insert(handoff);
}

export async function readPendingGoogleSignInHandoff(
  db: GoogleHandoffSource,
  state: string,
  nowIso: string,
  bindingHash?: string,
): Promise<GooglePendingSignInHandoff | null> {
  const bindingProvided = bindingHash !== undefined;
  if (bindingProvided) assertBindingHash(bindingHash);
  assertInstant(nowIso);
  const row = await googleHandoffStore(db).readPending({
    state,
    nowIso,
    ...(bindingProvided ? { bindingHash } : {}),
  });
  if (!row || !VERIFIER_PATTERN.test(row.codeVerifier)) return null;
  return row;
}

export async function claimPendingGoogleSignInHandoff(
  db: GoogleHandoffSource,
  state: string,
  claimId: string,
  nowIso: string,
  staleClaimBeforeIso: string,
): Promise<GooglePendingSignInHandoff | null> {
  assertProof(claimId);
  assertInstant(nowIso);
  assertInstant(staleClaimBeforeIso);
  const row = await googleHandoffStore(db).claim({
    state, claimId, nowIso, staleClaimBeforeIso,
  });
  if (!row || !VERIFIER_PATTERN.test(row.codeVerifier)) return null;
  return row;
}

export async function completeGoogleSignInHandoff(
  db: GoogleHandoffSource,
  state: string,
  claimId: string,
  identityLinkKey: string,
  proof: string,
  nowIso: string,
  deliveryExpiresAtIso: string,
): Promise<boolean> {
  assertProof(claimId);
  assertIdentityLinkKey(identityLinkKey);
  assertProof(proof);
  assertInstant(nowIso);
  assertInstant(deliveryExpiresAtIso);
  if (!(deliveryExpiresAtIso > nowIso)) internalError();
  return googleHandoffStore(db).complete({
    state, claimId, identityLinkKey, proof, nowIso, deliveryExpiresAtIso,
  });
}

export async function deliverGoogleSignInHandoff(
  db: GoogleHandoffSource,
  state: string,
  nowIso: string,
  bindingHash: string,
): Promise<GoogleDeliveredSignInHandoff | null> {
  assertBindingHash(bindingHash);
  assertInstant(nowIso);
  const row = await googleHandoffStore(db).deliver({ state, nowIso, bindingHash });
  if (!row || !PROOF_PATTERN.test(row.proof)) return null;
  return row;
}

export async function consumeGoogleSignInHandoff(
  db: GoogleHandoffSource,
  proof: string,
  bindingHash: string,
  nowIso: string,
): Promise<{ linkKeyHex: string } | null> {
  assertProof(proof);
  assertBindingHash(bindingHash);
  assertInstant(nowIso);
  const row = await googleHandoffStore(db).consume({ proof, bindingHash, nowIso });
  if (!row || !LINK_KEY_PATTERN.test(row.linkKeyHex)) return null;
  return row;
}

export async function hasExpiredGoogleSignInHandoffs(
  db: GoogleHandoffSource,
  nowIso: string,
): Promise<boolean> {
  assertInstant(nowIso);
  return googleHandoffStore(db).hasExpired({ nowIso });
}

export async function discardPendingGoogleSignInHandoff(
  db: GoogleHandoffSource,
  state: string,
  nowIso: string,
): Promise<void> {
  assertInstant(nowIso);
  await googleHandoffStore(db).discardPending({ state, nowIso });
}

export async function discardClaimedGoogleSignInHandoff(
  db: GoogleHandoffSource,
  state: string,
  claimId: string,
  nowIso: string,
): Promise<void> {
  assertProof(claimId);
  assertInstant(nowIso);
  await googleHandoffStore(db).discardClaimed({ state, claimId, nowIso });
}

export async function deleteExpiredGoogleSignInHandoffs(
  db: GoogleHandoffSource,
  nowIso: string,
  maximumRows = 100,
): Promise<number> {
  if (!Number.isInteger(maximumRows) || maximumRows < 1 || maximumRows > 1000) {
    internalError();
  }
  assertInstant(nowIso);
  return googleHandoffStore(db).purge({ nowIso, maximumRows });
}

export async function consumeHostedSignInHandoff(
  db: IdentityHandoffSource,
  provider: "apple" | "google",
  proof: string,
  bindingHash: string,
  nowIso: string,
): Promise<{ linkKeyHex: string } | null> {
  assertProof(proof);
  assertBindingHash(bindingHash);
  assertInstant(nowIso);
  const row = await providerStore(db, provider).consume({ proof, bindingHash, nowIso });
  if (!row || !LINK_KEY_PATTERN.test(row.linkKeyHex)) return null;
  return row;
}
