/**
 * Live id allocation guard for the retained typed v1/v1.1 telemetry family.
 *
 * Primary migration 0052 makes the nine id-keyed typed tables
 * GENERATED BY DEFAULT AS IDENTITY, so the importer keeps writing exact D1
 * ids while live v1.0/v1.1 admission omits them. An identity that has not
 * been moved past the imported rows would hand out an id that already
 * exists, so every live path must refuse service until the headroom holds.
 *
 * Both helpers run on a caller-owned client: they never start, commit or
 * roll back a transaction, and a failure never carries SQL, provider text
 * or id values.
 */
import { ApiError } from "./errors";
import {
  createPostgresSchemaConfig,
  quotePostgresIdentifier,
  type PostgresClient,
  type PostgresSchemaOptions,
} from "./postgres-client";

/** The id-keyed typed tables from primary 0030, parent before child. */
export const POSTGRES_TYPED_IDENTITY_TABLES = Object.freeze([
  "typed_telemetry_namespaces",
  "typed_telemetry_owners",
  "typed_telemetry_devices",
  "typed_telemetry_manifests",
  "typed_telemetry_chunks",
  "typed_telemetry_identifiers",
  "typed_telemetry_attributions",
  "typed_telemetry_quota_dimensions",
  "typed_telemetry_records",
] as const);

export type PostgresTypedIdentityTable = (typeof POSTGRES_TYPED_IDENTITY_TABLES)[number];

/** The 0030 id CHECK bound, which is also the D1/JavaScript safe-integer bound. */
const MAX_TYPED_ID = 9_007_199_254_740_991n;
const UNSIGNED_DECIMAL = /^(0|[1-9][0-9]{0,18})$/u;

interface IdentityStateRow {
  readonly table_name: unknown;
  readonly identity_kind: unknown;
  readonly sequence_bound: unknown;
  readonly increment_by: unknown;
  readonly maximum_value: unknown;
  readonly cycles: unknown;
  readonly last_value: unknown;
  readonly is_called: unknown;
  readonly max_id: unknown;
}

function unavailable(): never {
  throw new ApiError(503, "BACKEND_STORAGE_UNAVAILABLE");
}

function primarySchemaName(schema: PostgresSchemaOptions): string {
  return createPostgresSchemaConfig(schema).primarySchema;
}

function assertClient(client: PostgresClient): void {
  if (client === null || typeof client !== "object" || typeof client.query !== "function") {
    throw new TypeError("invalid PostgreSQL client");
  }
}

function sequenceName(table: PostgresTypedIdentityTable): string {
  return `${table}_id_seq`;
}

/**
 * One statement for all nine tables. The identity sequence is read directly:
 * pg_sequence_last_value is NULL both for a fresh identity and right after a
 * RESTART, so only last_value with is_called gives the next value. The
 * snapshot for max(id) is never newer than the sequence read, and sequences
 * only move forward, so concurrent live allocations cannot produce a false
 * pass (explicit-id imports must finish before routing). pg_get_serial_sequence
 * proves the read sequence is the column's own identity rather than a
 * same-named relation.
 */
function identityStateSql(schema: string): string {
  return POSTGRES_TYPED_IDENTITY_TABLES.map((table) => {
    const sequence = sequenceName(table);
    return `SELECT '${table}'::text AS table_name,
       attribute.attidentity::text AS identity_kind,
       pg_catalog.pg_get_serial_sequence(pg_catalog.format('%I.%I', $1::text, '${table}'::text), 'id')::regclass
         = state.tableoid::regclass AS sequence_bound,
       sequence.seqincrement::text AS increment_by,
       sequence.seqmax::text AS maximum_value,
       sequence.seqcycle AS cycles,
       state.last_value::text AS last_value,
       state.is_called AS is_called,
       (SELECT pg_catalog.max(target.id) FROM ${schema}.${quotePostgresIdentifier(table)} target)::text AS max_id
  FROM ${schema}.${quotePostgresIdentifier(sequence)} state
  JOIN pg_catalog.pg_sequence sequence ON sequence.seqrelid = state.tableoid
  JOIN pg_catalog.pg_attribute attribute
    ON attribute.attrelid = pg_catalog.format('%I.%I', $1::text, '${table}'::text)::regclass
   AND attribute.attname = 'id' AND NOT attribute.attisdropped`;
  }).join("\nUNION ALL\n");
}

function decimal(value: unknown): bigint {
  if (typeof value !== "string" || !UNSIGNED_DECIMAL.test(value)) unavailable();
  return BigInt(value);
}

function assertHeadroom(row: IdentityStateRow | undefined): void {
  if (row === undefined || row.identity_kind !== "d" || row.sequence_bound !== true
      || row.increment_by !== "1" || row.cycles !== false || typeof row.is_called !== "boolean") {
    unavailable();
  }
  const maximumValue = decimal(row.maximum_value);
  const lastValue = decimal(row.last_value);
  const maxId = row.max_id === null ? 0n : decimal(row.max_id);
  const nextValue = row.is_called ? lastValue + 1n : lastValue;
  if (nextValue <= maxId || nextValue > maximumValue || nextValue > MAX_TYPED_ID) unavailable();
}

/**
 * Refuse service with 503 BACKEND_STORAGE_UNAVAILABLE unless, for every typed
 * table, the id column is a BY DEFAULT identity with increment 1 and no
 * cycle, and its next value is above max(id) and inside the id range.
 * Composition startup and the typed admission paths call this before any
 * live allocation.
 */
export async function verifyPostgresTypedIdentityHeadroom(
  client: PostgresClient,
  schema: PostgresSchemaOptions = {},
): Promise<void> {
  assertClient(client);
  const schemaName = primarySchemaName(schema);
  let rows: readonly IdentityStateRow[];
  try {
    rows = (await client.query<IdentityStateRow>(
      identityStateSql(quotePostgresIdentifier(schemaName)),
      [schemaName],
    )).rows;
  } catch {
    unavailable();
  }
  if (!Array.isArray(rows) || rows.length !== POSTGRES_TYPED_IDENTITY_TABLES.length) unavailable();
  for (const table of POSTGRES_TYPED_IDENTITY_TABLES) {
    const matching = rows.filter((row) => row?.table_name === table);
    if (matching.length !== 1) unavailable();
    assertHeadroom(matching[0]);
  }
}

/**
 * Move every typed identity to max(id)+1 (1 when empty) without lowering one
 * that already allocated further. The transfer calls this after import and
 * before routing, as the schema-owner role; the runtime role cannot execute
 * it. The SQL function holds ACCESS EXCLUSIVE locks on all nine tables until
 * the caller's transaction ends, so run it before live traffic and under a
 * lock timeout. A failure, including an exhausted id range, is 503 without
 * detail.
 */
export async function restartPostgresTypedIdentities(
  client: PostgresClient,
  schema: PostgresSchemaOptions = {},
): Promise<void> {
  assertClient(client);
  const primary = quotePostgresIdentifier(primarySchemaName(schema));
  try {
    await client.query(`SELECT ${primary}.${quotePostgresIdentifier("typed_telemetry_restart_identities")}()`);
  } catch {
    unavailable();
  }
}
