-- Qualification schema only. Not a deployment migration or a full D1 port.
-- All writes use insert_contribution; direct table writes are test fixture setup.
-- Additional transactional projections are installed by projections.sql and
-- quota-fit.sql; computation/publication workers remain separate adapters.
CREATE SCHEMA tibotattle_v1_test;
REVOKE ALL ON SCHEMA tibotattle_v1_test FROM PUBLIC;
SET search_path = tibotattle_v1_test, pg_catalog;
CREATE TABLE participants (
  id text PRIMARY KEY, state text NOT NULL CHECK (state IN ('active','deleting')),
  owner_kind text NOT NULL CHECK(owner_kind IN ('social','accountless')),
  transport_floor integer NOT NULL DEFAULT 10 CHECK(transport_floor IN (10,20))
);
CREATE TABLE devices (
  id text PRIMARY KEY, participant_id text NOT NULL REFERENCES participants,
  state text NOT NULL CHECK(state IN ('active','revoked')),
  issued_at timestamptz NOT NULL, expires_at timestamptz NOT NULL
);
CREATE TABLE consents (
  participant_id text NOT NULL REFERENCES participants,
  device_id text NOT NULL REFERENCES devices,
  schema_version text NOT NULL, dictionary_version text NOT NULL, privacy_version text NOT NULL,
  PRIMARY KEY(participant_id,device_id)
);
CREATE TABLE authorizations (
  id text PRIMARY KEY, participant_id text NOT NULL REFERENCES participants,
  device_id text NOT NULL REFERENCES devices, envelope_digest text NOT NULL,
  CHECK(envelope_digest ~ '^[0-9a-f]{64}$'),
  state text NOT NULL CHECK(state IN ('consuming','consumed','revoked')),
  lease_expires_at timestamptz, expires_at timestamptz NOT NULL,
  consumed_contribution_id text, consumed_at timestamptz
);
CREATE TABLE chunks (
  id text PRIMARY KEY, participant_id text NOT NULL REFERENCES participants,
  device_id text NOT NULL REFERENCES devices, stream text NOT NULL CHECK(stream IN ('usage','quota','session')),
  chunk_day date NOT NULL, chunk_seq integer NOT NULL CHECK(chunk_seq >= 0), revision integer NOT NULL CHECK(revision > 0),
  chunk_digest text NOT NULL CHECK(chunk_digest ~ '^[0-9a-f]{64}$'),
  envelope_digest text NOT NULL CHECK(envelope_digest ~ '^[0-9a-f]{64}$'),
  parser_version text NOT NULL, record_count integer NOT NULL CHECK(record_count BETWEEN 1 AND 200),
  accepted_record_count integer NOT NULL CHECK(accepted_record_count BETWEEN 0 AND record_count),
  object_key text NOT NULL UNIQUE, authorization_id text NOT NULL UNIQUE REFERENCES authorizations,
  created_at timestamptz NOT NULL, superseded_at timestamptz,
  UNIQUE(participant_id,envelope_digest),
  UNIQUE(participant_id,device_id,stream,chunk_day,chunk_seq,revision)
);
CREATE UNIQUE INDEX chunks_current ON chunks(participant_id,device_id,stream,chunk_day,chunk_seq)
  WHERE superseded_at IS NULL;
CREATE TABLE records (
  id bigint GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL CHECK(id BETWEEN 1 AND 9007199254740991),
  chunk_id text NOT NULL REFERENCES chunks,
  participant_id text NOT NULL REFERENCES participants, device_id text NOT NULL REFERENCES devices,
  stream text NOT NULL, occurrence_id text NOT NULL, observed_at timestamptz NOT NULL, payload jsonb NOT NULL,
  observed_day date NOT NULL, provider text, plan_type text, plan_variant text, limit_id text, slot text,
  used_percent double precision, window_duration_minutes integer, resets_at timestamptz,
  PRIMARY KEY(participant_id,device_id,stream,occurrence_id)
);
CREATE INDEX records_chunk ON records(chunk_id);
CREATE TABLE admission_windows (
  participant_id text NOT NULL REFERENCES participants, device_id text NOT NULL REFERENCES devices,
  window_day date NOT NULL, accepted_count integer NOT NULL CHECK(accepted_count >= 0),
  PRIMARY KEY(participant_id,device_id,window_day)
);
CREATE TABLE input_versions (participant_id text PRIMARY KEY REFERENCES participants, revision bigint NOT NULL);

-- This base-schema PostgreSQL projection effect
-- mirrors the v1 dependency trigger from migrations/0051 and the social-owner
-- gate added by migrations/0059. Dependencies are participant-scoped; the
-- composition cache has no participant identity, so a social source evicts
-- every matching retained history day in the affected inclusive 100-day
-- range. This is a test-only projection fragment, not full D1 parity.
CREATE TABLE community_model_history_dependencies (
  participant_id text NOT NULL REFERENCES participants(id) ON DELETE CASCADE,
  day date NOT NULL,
  from_day date NOT NULL,
  dependency_revision bigint NOT NULL DEFAULT 0
    CHECK(dependency_revision >= 0 AND dependency_revision < 9007199254740991),
  input_fingerprint text CHECK(input_fingerprint IS NULL OR input_fingerprint ~ '^[0-9a-f]{64}$'),
  verified_input_revision bigint CHECK(verified_input_revision IS NULL OR
    (verified_input_revision >= 0 AND verified_input_revision < 9007199254740991)),
  PRIMARY KEY(participant_id, day),
  CHECK(from_day = day - 100)
);
CREATE INDEX community_model_history_dependencies_day
  ON community_model_history_dependencies(day, participant_id);

CREATE TABLE community_model_composition_days (
  day date PRIMARY KEY,
  payload_json text NOT NULL,
  computed_at timestamptz NOT NULL,
  history_method_version text
);

-- Separate durable object journal: insert does not delete this row on success or failure.
CREATE TABLE pending_objects (contribution_id text PRIMARY KEY, object_key text NOT NULL UNIQUE);

CREATE FUNCTION insert_contribution(input jsonb) RETURNS TABLE(accepted_records integer)
LANGUAGE plpgsql SET search_path = tibotattle_v1_test, pg_catalog AS $$
DECLARE
  p participants%ROWTYPE; d devices%ROWTYPE; a authorizations%ROWTYPE;
  current_chunk chunks%ROWTYPE;
  chunk jsonb := input->'chunk';
  records_input jsonb := chunk->'records';
  pid text := input->>'participantId'; did text := input->>'deviceId';
  cid text := input->>'chunkId'; aid text := input->>'uploadAuthorizationId';
  old_id text := input->'supersedes'->>'id';
  stream_name text := chunk->>'stream'; day_value date := (chunk->>'chunkDay')::date;
  sequence_value integer := (chunk->>'chunkSeq')::integer;
  revision_value integer := (chunk->>'chunkRevision')::integer;
  created timestamptz := (input->>'createdAt')::timestamptz;
  n integer := jsonb_array_length(records_input);
  accepted integer; maximum integer; changed integer;
BEGIN
  IF n IS NULL OR n NOT BETWEEN 1 AND 200 THEN RAISE EXCEPTION USING ERRCODE='P1005', MESSAGE='invalid chunk'; END IF;
  -- A real row lock serializes all writers for this participant, including
  -- first admission where no window/current-chunk row exists yet.
  SELECT * INTO p FROM participants WHERE id=pid FOR UPDATE;
  IF NOT FOUND OR p.state <> 'active' THEN RAISE EXCEPTION USING ERRCODE='P1001', MESSAGE='participant unavailable'; END IF;
  IF p.owner_kind <> 'social' OR p.transport_floor > 10 THEN RAISE EXCEPTION USING ERRCODE='P1007', MESSAGE='transport blocked'; END IF;
  SELECT * INTO d FROM devices WHERE id=did AND participant_id=pid FOR UPDATE;
  IF NOT FOUND OR d.state <> 'active' OR d.expires_at <= clock_timestamp() THEN
    RAISE EXCEPTION USING ERRCODE='P1002', MESSAGE='upload unavailable'; END IF;
  PERFORM 1 FROM consents WHERE participant_id=pid AND device_id=did
    AND schema_version='telemetry-contribution-v1.0'
    AND dictionary_version='telemetry-v1.0-registry-2026-08-07.1'
    AND privacy_version='ongoing-privacy-safe-telemetry-v1.0'
    AND schema_version=chunk->'consent'->>'telemetrySchemaVersion'
    AND dictionary_version=chunk->'consent'->>'fieldDictionaryVersion'
    AND privacy_version=chunk->'consent'->>'privacyContractVersion' FOR SHARE;
  IF NOT FOUND THEN RAISE EXCEPTION USING ERRCODE='P1006', MESSAGE='consent unavailable'; END IF;
  SELECT * INTO a FROM authorizations WHERE id=aid AND participant_id=pid AND device_id=did FOR UPDATE;
  IF NOT FOUND OR a.state <> 'consuming' OR a.envelope_digest <> input->>'envelopeDigest'
    OR a.lease_expires_at IS NULL OR a.lease_expires_at <= clock_timestamp() OR a.expires_at <= clock_timestamp() THEN
    RAISE EXCEPTION USING ERRCODE='P1002', MESSAGE='upload unavailable'; END IF;
  SELECT * INTO current_chunk FROM chunks WHERE participant_id=pid AND device_id=did
    AND stream=stream_name AND chunk_day=day_value AND chunk_seq=sequence_value AND superseded_at IS NULL FOR UPDATE;
  IF old_id IS NULL THEN
    IF current_chunk.id IS NOT NULL OR revision_value <> 1 OR EXISTS(
      SELECT 1 FROM chunks WHERE participant_id=pid AND device_id=did AND stream=stream_name
      AND chunk_day=day_value AND chunk_seq=sequence_value) THEN
      RAISE EXCEPTION USING ERRCODE='P1005', MESSAGE='revision conflict'; END IF;
  ELSE
    IF current_chunk.id IS DISTINCT FROM old_id OR revision_value IS DISTINCT FROM current_chunk.revision+1 THEN
      RAISE EXCEPTION USING ERRCODE='P1005', MESSAGE='revision conflict'; END IF;
  END IF;
  maximum := CASE WHEN d.issued_at > created - interval '7 days' THEN 20000 ELSE 2000 END;
  SELECT accepted_count INTO accepted FROM admission_windows
    WHERE participant_id=pid AND device_id=did AND window_day=(created AT TIME ZONE 'UTC')::date;
  IF COALESCE(accepted,0) >= maximum THEN RAISE EXCEPTION USING ERRCODE='P1003', MESSAGE='admission exhausted'; END IF;
  PERFORM begin_graph_scope(input);
  IF old_id IS NOT NULL THEN
    UPDATE chunks SET superseded_at=created WHERE id=old_id AND superseded_at IS NULL;
    GET DIAGNOSTICS changed = ROW_COUNT;
    IF changed <> 1 THEN RAISE EXCEPTION USING ERRCODE='P1005', MESSAGE='revision conflict'; END IF;
    DELETE FROM records WHERE chunk_id=old_id;
  END IF;
  BEGIN
    INSERT INTO chunks(id,participant_id,device_id,stream,chunk_day,chunk_seq,revision,chunk_digest,
      envelope_digest,parser_version,record_count,accepted_record_count,object_key,authorization_id,created_at)
    VALUES(cid,pid,did,stream_name,day_value,sequence_value,revision_value,chunk->>'chunkDigest',
      input->>'envelopeDigest',chunk->>'parserVersion',n,n,input->>'objectKey',aid,created);
  EXCEPTION WHEN unique_violation THEN RAISE EXCEPTION USING ERRCODE='P1005', MESSAGE='revision conflict'; END;
  BEGIN
    INSERT INTO records(chunk_id,participant_id,device_id,stream,occurrence_id,observed_at,payload,
      observed_day,provider,plan_type,plan_variant,limit_id,slot,used_percent,window_duration_minutes,resets_at)
      SELECT cid,pid,did,stream_name,
        CASE stream_name WHEN 'usage' THEN r->>'eventId' WHEN 'quota' THEN r->>'observationId' ELSE r->>'sessionUuid' END,
        (CASE stream_name WHEN 'usage' THEN r->>'eventTime' WHEN 'quota' THEN r->>'observedTime' ELSE r->>'firstEventTime' END)::timestamptz,r,
        ((CASE stream_name WHEN 'usage' THEN r->>'eventTime' WHEN 'quota' THEN r->>'observedTime' ELSE r->>'firstEventTime' END)::timestamptz AT TIME ZONE 'UTC')::date,
        r->>'provider',CASE WHEN stream_name='quota' THEN r->>'planType' END,
        CASE WHEN stream_name='quota' THEN r->>'planVariant' END,CASE WHEN stream_name='quota' THEN r->>'limitId' END,
        CASE WHEN stream_name='quota' THEN r->>'slot' END,CASE WHEN stream_name='quota' THEN (r->>'usedPercent')::double precision END,
        CASE WHEN stream_name='quota' THEN (r->>'windowDurationMinutes')::integer END,
        CASE WHEN stream_name='quota' THEN (r->>'resetsAt')::timestamptz END
      FROM jsonb_array_elements(records_input) AS r;
  EXCEPTION WHEN unique_violation THEN RAISE EXCEPTION USING ERRCODE='P1004', MESSAGE='record owned'; END;
  UPDATE authorizations SET state='consumed',consumed_contribution_id=cid,consumed_at=created,lease_expires_at=NULL WHERE id=aid;
  INSERT INTO admission_windows VALUES(pid,did,(created AT TIME ZONE 'UTC')::date,1)
    ON CONFLICT(participant_id,device_id,window_day) DO UPDATE SET accepted_count=admission_windows.accepted_count+1;
  RETURN QUERY SELECT n;
END;
$$;
REVOKE ALL ON FUNCTION insert_contribution(jsonb) FROM PUBLIC;

-- Keep the model-history invalidation in the same transaction as the chunk
-- journal. An append invalidates the participant's dependency rows and, only
-- for social owners, evicts matching history composition days. A correction
-- is intentionally two source mutations in this harness (supersede then
-- insert), so it produces the same +2 dependency revision effect as the D1
-- update/insert path. The composition DELETE is global across the
-- materialized day table while retaining the D1 day-range bound.
CREATE FUNCTION invalidate_model_history_v1_insert() RETURNS trigger
LANGUAGE plpgsql SET search_path = tibotattle_v1_test, pg_catalog AS $$
BEGIN
  UPDATE community_model_history_dependencies
     SET dependency_revision = dependency_revision + 1,
         input_fingerprint = NULL,
         verified_input_revision = NULL
   WHERE participant_id = NEW.participant_id
     AND day BETWEEN NEW.chunk_day AND NEW.chunk_day + 100;

  IF EXISTS (
    SELECT 1 FROM participants
     WHERE id = NEW.participant_id AND owner_kind = 'social'
  ) THEN
    DELETE FROM community_model_composition_days
     WHERE history_method_version IS NOT NULL
       AND day BETWEEN NEW.chunk_day AND NEW.chunk_day + 100;
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER community_model_history_v1_insert
AFTER INSERT ON chunks FOR EACH ROW
WHEN (NEW.superseded_at IS NULL)
EXECUTE FUNCTION invalidate_model_history_v1_insert();

CREATE FUNCTION invalidate_model_history_v1_update() RETURNS trigger
LANGUAGE plpgsql SET search_path = tibotattle_v1_test, pg_catalog AS $$
BEGIN
  UPDATE community_model_history_dependencies
     SET dependency_revision = dependency_revision + 1,
         input_fingerprint = NULL,
         verified_input_revision = NULL
   WHERE (participant_id = OLD.participant_id
          AND day BETWEEN OLD.chunk_day AND OLD.chunk_day + 100)
      OR (participant_id = NEW.participant_id
          AND day BETWEEN NEW.chunk_day AND NEW.chunk_day + 100);

  IF EXISTS (
    SELECT 1 FROM participants
     WHERE owner_kind = 'social'
       AND (id = OLD.participant_id OR id = NEW.participant_id)
  ) THEN
    DELETE FROM community_model_composition_days
     WHERE history_method_version IS NOT NULL
       AND (day BETWEEN OLD.chunk_day AND OLD.chunk_day + 100
            OR day BETWEEN NEW.chunk_day AND NEW.chunk_day + 100);
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER community_model_history_v1_update
AFTER UPDATE ON chunks FOR EACH ROW
WHEN ((OLD.superseded_at IS NULL OR NEW.superseded_at IS NULL)
 AND (OLD.id IS DISTINCT FROM NEW.id
      OR OLD.participant_id IS DISTINCT FROM NEW.participant_id
      OR OLD.device_id IS DISTINCT FROM NEW.device_id
      OR OLD.stream IS DISTINCT FROM NEW.stream
      OR OLD.chunk_day IS DISTINCT FROM NEW.chunk_day
      OR OLD.chunk_seq IS DISTINCT FROM NEW.chunk_seq
      OR OLD.revision IS DISTINCT FROM NEW.revision
      OR OLD.chunk_digest IS DISTINCT FROM NEW.chunk_digest
      OR OLD.parser_version IS DISTINCT FROM NEW.parser_version
      OR OLD.record_count IS DISTINCT FROM NEW.record_count
      OR OLD.accepted_record_count IS DISTINCT FROM NEW.accepted_record_count
      OR OLD.authorization_id IS DISTINCT FROM NEW.authorization_id
      OR OLD.created_at IS DISTINCT FROM NEW.created_at
      OR OLD.superseded_at IS DISTINCT FROM NEW.superseded_at))
EXECUTE FUNCTION invalidate_model_history_v1_update();

CREATE FUNCTION invalidate_model_history_v1_delete() RETURNS trigger
LANGUAGE plpgsql SET search_path = tibotattle_v1_test, pg_catalog AS $$
BEGIN
  UPDATE community_model_history_dependencies
     SET dependency_revision = dependency_revision + 1,
         input_fingerprint = NULL,
         verified_input_revision = NULL
   WHERE participant_id = OLD.participant_id
     AND day BETWEEN OLD.chunk_day AND OLD.chunk_day + 100;

  IF EXISTS (
    SELECT 1 FROM participants
     WHERE id = OLD.participant_id AND owner_kind = 'social'
  ) THEN
    DELETE FROM community_model_composition_days
     WHERE history_method_version IS NOT NULL
       AND day BETWEEN OLD.chunk_day AND OLD.chunk_day + 100;
  END IF;
  RETURN OLD;
END;
$$;

CREATE TRIGGER community_model_history_v1_delete
AFTER DELETE ON chunks FOR EACH ROW
WHEN (OLD.superseded_at IS NULL)
EXECUTE FUNCTION invalidate_model_history_v1_delete();

RESET search_path;
