packages:
  - packages/*

overrides:
  fast-uri: 3.1.7

allowBuilds:
  '@github/keytar': false
  electron-winstaller: false

patchedDependencies:
  app-builder-lib@26.15.7: config/patches/app-builder-lib@26.15.7.patch
