#!/bin/zsh
# MEAS-SYNTH cloud measurement: the full-recompute analytics refresh over the
# PRODUCTION-SHAPED synthetic corpus, in the TEST project `tibotattle` only
# (the fast-path test database tibotattle_fastpath on the test primary).
# Never production or staging. Modelled on the parity home's
# receipts/run-dense-deploy.sh.
#
#   zsh apps/worker/scripts/gcp-fastpath-prod-shape/run-cloud-measurement.sh
#
# Environment (all optional):
#   MEAS_CORPUS     seed-source.mjs work directory (default
#                   ~/Library/Caches/tibotattle-meas-synth/full/seed); it must
#                   be the full-scale corpus (own3.matches all true)
#   MEAS_OUT        receipt directory (default
#                   ~/Documents/Coding/tibotattle-gcp-parity/receipts/gcp-meas-synth-<UTC stamp>)
#   MEAS_IMAGE      reuse an image digest built from this commit (skips build)
#   MEAS_SKIP_SEED=1 and MEAS_SCHEMA=<schema>   reuse a schema an earlier run seeded
#   MEAS_UNCAPPED=1 after the guarded run, execute the same Job once more with a
#                   24 h task timeout (and the guard at 24 h) to time a run to
#                   its end; costs up to 24 h of a 4 vCPU / 16 GiB task
#
# Steps:
#   preflight  clean checkout of HEAD for every path the seed and image use;
#              corpus manifest present, full scale, OWN-3 matched
#   build      gcp-fastpath-test-deploy.mjs build --commit=HEAD
#   migrate    deploy + execute the migrate Job (fast-path test database)
#   verify-database
#   seed       gcp-fastpath-seed.mjs seed --sealed-corpus (the reviewed importer
#              chain through the Cloud SQL connector as the migrator IAM user;
#              runs on THIS machine, Node 26, large heap; expect hours)
#   refresh    the refresh Job with the production task profile (dense: 4 vCPU,
#              16 GiB, heap 12,288 MiB, budget 10,752 MiB, 14,400 s task
#              timeout) and the production time guard
#              (ANALYTICS_V2_REFRESH_TASK_TIMEOUT_SECONDS=14400), at the
#              corpus clock 2026-10-01T12:46:00.000Z
#   uncapped   (MEAS_UNCAPPED=1 only) the same Job, one execution with a 24 h
#              task timeout and guard
#
# Expected (docs/receipts/2026-10-03-gcp-meas-synth.md): the local run took
# 15,530 s and projects to 13.6-19.1 h on Cloud Run, so the guarded refresh
# should refuse ANALYTICS_V2_REFRESH_DEADLINE_PROJECTED partway (its time model
# plans 10,998 s) and publish nothing; run with MEAS_UNCAPPED=1 to measure the
# real duration, which sets the task timeout, the recalibrated rates and C3.
#   protected  read the shared test services' revisions (never written)
set -u
setopt pipefail
H=${MEAS_PARITY_HOME:-$HOME/Documents/Coding/tibotattle-gcp-parity}
SCRIPT_DIR=${0:A:h}
WT=$(git -C "$SCRIPT_DIR" rev-parse --show-toplevel) || { echo "not in a git checkout"; exit 2; }
WORKER=$WT/apps/worker
COMMIT=$(git -C "$WT" rev-parse HEAD)
CORPUS=${MEAS_CORPUS:-$HOME/Library/Caches/tibotattle-meas-synth/full/seed}
OUT=${MEAS_OUT:-$H/receipts/gcp-meas-synth-$(date -u +%Y%m%dT%H%M%SZ)}
NODE26=${MEAS_NODE26:-$HOME/.nvm/versions/node/v26.2.0/bin/node}
NOW=2026-10-01T12:46:00.000Z
JOB=tibotattle-fastpath-test-analytics-refresh
D() { "$NODE26" scripts/gcp-fastpath-test-deploy.mjs "$@"; }
step() { echo "== $(date -u +%H:%M:%S) $1"; }
mkdir -p -m 700 "$OUT"
echo "commit $COMMIT"; echo "corpus $CORPUS"; echo "out $OUT"
cd "$WORKER" || exit 2

step preflight
if [[ -n "$(git -C "$WT" status --porcelain -- apps/worker packages apps/web/public)" ]]; then
  echo "preflight FAILED: the checkout differs from HEAD under apps/worker, packages or apps/web/public"; exit 1
fi
"$NODE26" -e '
  const fs = require("fs"), path = require("path"), crypto = require("crypto");
  const m = JSON.parse(fs.readFileSync(process.argv[1] + "/corpus-manifest.json", "utf8"));
  // The corpus was generated by the seeder files this checkout holds.
  const blob = (file) => { const bytes = fs.readFileSync(file);
    return crypto.createHash("sha1").update(`blob ${bytes.length}\0`).update(bytes).digest("hex"); };
  const seeders = Object.entries(m.seederFiles).map(([file, id]) => blob(path.join(process.argv[2], file)) === id);
  const ok = m.corpus.scale === 1 && m.corpus.owners === "all" && m.own3.matches
    && Object.values(m.own3.matches).every(Boolean) && m.sealed.sealReady === true && seeders.every(Boolean);
  console.log(JSON.stringify({ scale: m.corpus.scale, owners: m.owners.length, totals: m.totals,
    own3: m.own3.matches, sealed: m.sealed.sha256, seederFilesMatch: seeders.every(Boolean) }));
  process.exit(ok ? 0 : 1);' "$CORPUS" "$WT" > "$OUT/preflight.json" || { echo "preflight FAILED: corpus"; cat "$OUT/preflight.json"; exit 1; }
cat "$OUT/preflight.json"
"$NODE26" scripts/gcp-fastpath-seed.mjs plan --commit="$COMMIT" --sealed-corpus="$CORPUS" > "$OUT/seed-plan.json" \
  || { echo "preflight FAILED: seed plan"; exit 1; }
grep -q '"decision": "run"' "$OUT/seed-plan.json" || { echo "preflight FAILED: seed plan refuses"; cat "$OUT/seed-plan.json"; exit 1; }

if [[ -n "${MEAS_IMAGE:-}" ]]; then
  IMG=$MEAS_IMAGE
else
  step build; D build --commit="$COMMIT" --out="$OUT/build" > "$OUT/build.log" 2>&1 || { echo "build FAILED"; exit 1; }
  IMG=$("$NODE26" -e 'const fs=require("fs"),p=require("path");const d=process.argv[1];
    const f=fs.readdirSync(d).filter(n=>/^build-.*\.json$/.test(n)).sort().at(-1);
    console.log(JSON.parse(fs.readFileSync(p.join(d,f),"utf8")).image)' "$OUT/build")
fi
echo "image $IMG"
step migrate; D migrate --commit="$COMMIT" --image="$IMG" --out="$OUT/migrate" > "$OUT/migrate.log" 2>&1 || { echo "migrate FAILED"; exit 1; }
step verify-database; D verify-database --commit="$COMMIT" --out="$OUT/verifydb" > "$OUT/verifydb.log" 2>&1 || { echo "verify-database FAILED"; exit 1; }

if [[ "${MEAS_SKIP_SEED:-}" == "1" ]]; then
  SCHEMA=${MEAS_SCHEMA:?MEAS_SCHEMA is required with MEAS_SKIP_SEED=1}
else
  step seed
  "$NODE26" --max-old-space-size=49152 scripts/gcp-fastpath-seed.mjs seed --target=gcp-fastpath --commit="$COMMIT" \
    --sealed-corpus="$CORPUS" > "$OUT/seed.json" 2> "$OUT/seed.log" || { echo "seed FAILED"; tail -c 600 "$OUT/seed.log"; exit 1; }
  SCHEMA=$("$NODE26" -e 'console.log(JSON.parse(require("fs").readFileSync(process.argv[1],"utf8")).schema)' "$OUT/seed.json")
fi
echo "schema $SCHEMA"

step refresh
D refresh --commit="$COMMIT" --image="$IMG" --schema="$SCHEMA" --now="$NOW" --refresh-profile=dense \
  --refresh-env=ANALYTICS_V2_REFRESH_TASK_TIMEOUT_SECONDS=14400 --out="$OUT/refresh" > "$OUT/refresh.log" 2>&1
echo "refresh rc=$?"; tail -c 1500 "$OUT/refresh.log"; echo

if [[ "${MEAS_UNCAPPED:-}" == "1" ]]; then
  # One execution of the Job just deployed, with execution-level overrides only
  # (the Job's configuration is unchanged): a 24 h task timeout and the guard at 24 h.
  step uncapped
  gcloud run jobs execute "$JOB" --project=tibotattle --region=us-east1 --task-timeout=86400s \
    --update-env-vars=ANALYTICS_V2_REFRESH_TASK_TIMEOUT_SECONDS=86400 --wait --format=json \
    > "$OUT/uncapped.json" 2> "$OUT/uncapped.log"
  echo "uncapped rc=$?"
  EXEC=$("$NODE26" -e 'try{console.log(JSON.parse(require("fs").readFileSync(process.argv[1],"utf8")).metadata.name)}catch{console.log("")}' "$OUT/uncapped.json")
  if [[ -n "$EXEC" ]]; then
    gcloud logging read "resource.type=\"cloud_run_job\" AND labels.\"run.googleapis.com/execution_name\"=\"$EXEC\"" \
      --project=tibotattle --limit=50 --format=json > "$OUT/uncapped-logs.json" 2>> "$OUT/uncapped.log"
  fi
fi

step protected; D protected --commit="$COMMIT" --out="$OUT/protected" > "$OUT/protected.log" 2>&1; echo "protected rc=$?"
step done
echo "receipts in $OUT"
