import test from 'node:test';import assert from 'node:assert/strict';import {Miniflare} from 'miniflare';
import {storageSha256} from './d1-storage-plan.mjs';
import {identityDigest} from '../../../scripts/lib/release-operation.mjs';
import {admitMigrationContinuation,verifyMigrationHandoffEvidence,MIGRATION_CONTINUATION_READ_SQL,migrationRolloverStatement,migrationRolloverDisposition} from './d1-storage-migration-continuation.mjs';
import {MIGRATION_JOURNAL_DDL,createStorageMigrationWorker} from './d1-storage-migration-worker.mjs';
import {createStorageMigrationBackend,createStorageMigrationFront} from './d1-storage-migration-placed.mjs';
import {SYNTHETIC_D1_WORKER,syntheticD1Binding,closeSyntheticD1Bindings} from './d1-storage-local-d1.mjs';
const now=Date.parse('2026-09-12T15:00:00.000Z'),iso=ms=>new Date(ms).toISOString(),hash='a'.repeat(64),version='11111111-1111-4111-8111-111111111111';
function fixture(){
 const topology={schema:'d1-storage-placed-topology-v1',frontName:'synthetic-front',backendName:'synthetic-backend',queueName:'synthetic-queue',queueId:'a'.repeat(32),source:{name:'synthetic-source',id:version},target:{name:'synthetic-target',id:'22222222-2222-4222-8222-222222222222'},region:'gcp:us-east4'};
 const contract={version:'authority-restore-v1',runId:'synthetic',sourceId:'synthetic',sourceNamespace:'synthetic',sourceSnapshotDigest:'b'.repeat(64),sourceSchema:[],sourceSchemaDigest:identityDigest([]),targetBaseSchemaDigest:'synthetic-base',tables:[],authoritySequences:[]};
 const previous={schema:'d1-storage-placed-migration-preparation-v1',executionFenceVersion:1,frozenSource:true,mode:'disabled',sourceCommit:'c'.repeat(40),roleInputSha256:hash,contractDigest:identityDigest(contract),expiresAt:iso(now-1000),topology,topologyDigest:identityDigest(topology)};
 previous.executionDigest=identityDigest({sourceCommit:previous.sourceCommit,roleInputSha256:previous.roleInputSha256,contractDigest:previous.contractDigest,expiresAt:previous.expiresAt,topology});
 const evidence={},encode=x=>Buffer.from(JSON.stringify(x)),provider=x=>encode({success:true,result:x}),result=rows=>encode([{success:true,results:rows}]);
 for(const lane of ['front','backend']){const bindings=[{name:'STORAGE_RESTORE_MODE',type:'plain_text',text:'disabled'},...(lane==='front'?[{name:'STORAGE_RESTORE_EXECUTOR',type:'service',service:topology.backendName},{name:'STORAGE_RESTORE_QUEUE',type:'queue',queue_name:topology.queueName,queue_id:topology.queueId}]:[{name:'SOURCE',type:'d1',id:topology.source.id},{name:'TARGET',type:'d1',id:topology.target.id}])];
  evidence[lane+'-settings']=provider({bindings,placement:lane==='backend'?{mode:'targeted',target:[10]}:{}});evidence[lane+'-version']=provider({id:version,resources:{bindings,script:{placement:lane==='backend'?{mode:'targeted',target:[{id:10,type:'region',region:topology.region}]}:undefined}}});
  evidence[lane+'-deployments']=provider({deployments:[{created_on:iso(now-2000),versions:[{version_id:version,percentage:100}]}]});evidence[lane+'-enabled']=encode({status:'passed',lane,mode:'enabled',sourceCommit:previous.sourceCommit,executionDigest:previous.executionDigest,versionId:version,checkedAt:iso(now-4000)});
  evidence[lane+'-subdomain']=provider({enabled:false,previews_enabled:false});evidence[lane+'-routes']=provider([]);evidence[lane+'-domains']=provider([]);
  }
 evidence['resource-pins']=encode({reviewed:true,accountId:'a'.repeat(32),sourceCommit:previous.sourceCommit,contractDigest:previous.contractDigest,topology});
 for(const key of ['front-schedules','front-consumers'])evidence[key]=provider([]);
 const schema=[{type:'table',name:'_authority_snapshot',tbl_name:'_authority_snapshot',sql:'CREATE TABLE _authority_snapshot(id INTEGER PRIMARY KEY CHECK(id=1),contract_digest TEXT NOT NULL,namespace TEXT NOT NULL,snapshot_digest TEXT NOT NULL) STRICT'}];
 for(const verb of ['INSERT','UPDATE','DELETE']){const name='_authority_freeze_'+verb.toLowerCase()+'__authority_snapshot';schema.push({type:'trigger',name,tbl_name:'_authority_snapshot',sql:`CREATE TRIGGER "${name}" BEFORE ${verb} ON "_authority_snapshot" BEGIN SELECT RAISE(ABORT,'AUTHORITY_SNAPSHOT_FROZEN'); END`});}
 evidence['source-schema']=result(schema);evidence['source-snapshot']=result([{contract_digest:previous.contractDigest,namespace:contract.sourceNamespace,snapshot_digest:contract.sourceSnapshotDigest}]);evidence['source-sequences']=result([]);evidence['target-schema']=result([{type:'table',name:'_authority_operator_progress',sql:MIGRATION_JOURNAL_DDL}]);evidence['target-checkpoint']=result([{contract_digest:previous.contractDigest,execution_digest:previous.executionDigest,stage:'copy-v11',steps:4,intent:null}]);
 const handoff={schema:'d1-storage-migration-handoff-v1',accountId:'a'.repeat(32),previousPreparationSha256:hash,executionDigest:previous.executionDigest,sourceCommit:previous.sourceCommit,contractDigest:previous.contractDigest,topologyDigest:previous.topologyDigest,stoppedAt:iso(now-2000),observedAt:iso(now),front:{name:topology.frontName,versionId:version,mode:'disabled',cron:[],consumerAttached:false,ingressClosed:true},backend:{name:topology.backendName,versionId:version,mode:'disabled',ingressClosed:true},source:{databaseId:topology.source.id,contractDigest:previous.contractDigest,namespace:contract.sourceNamespace,snapshotDigest:contract.sourceSnapshotDigest,schemaDigest:contract.sourceSchemaDigest,freezeTriggersExact:true,sequencesExact:true},target:{databaseId:topology.target.id,contractDigest:previous.contractDigest,executionDigest:previous.executionDigest,stage:'copy-v11',steps:4,intent:null},evidence:Object.keys(evidence).sort().map(name=>({name,path:name+'.json',sha256:hash,...(MIGRATION_CONTINUATION_READ_SQL[name]?{querySha256:storageSha256(MIGRATION_CONTINUATION_READ_SQL[name])}:{})}))};
 const approval={schema:'d1-storage-migration-continuation-approval-v1',originalPreparationSha256:hash,previousPreparationSha256:hash,previousContinuationSha256:null,handoffSha256:hash,approvedAt:iso(now),expiresAt:iso(now+23*3600000)};
 return {previous,previousPreparationSha256:hash,contract,handoff,handoffSha256:hash,approval,approvedApprovalSha256:identityDigest(approval),now,evidence};
}
test('clean approved checkpoint admits a changed execution identity and exact read evidence',()=>{const f=fixture(),before=structuredClone({...f,evidence:undefined});const r=admitMigrationContinuation(f);assert.equal(r.window,1);assert.deepEqual(r.checkpoint,f.handoff.target);assert.notEqual(r.executionDigest,f.previous.executionDigest);assert.deepEqual({...f,evidence:undefined},before);assert.equal(verifyMigrationHandoffEvidence(f),true);});
test('approval, expiry, source, topology, checkpoint and drain drift refuse',()=>{for(const mutate of [f=>f.approvedApprovalSha256='b'.repeat(64),f=>f.approval.expiresAt=iso(now),f=>f.approval.expiresAt=iso(now+86400001),f=>f.approval.previousContinuationSha256=hash,f=>f.handoff.target.intent='copy-v11',f=>f.handoff.target.steps=-1,f=>f.handoff.source.databaseId='foreign',f=>f.handoff.source.snapshotDigest='wrong',f=>f.previous.executionFenceVersion=undefined,f=>f.handoff.front.consumerAttached=true,f=>f.handoff.front.mode='enabled',f=>f.handoff.stoppedAt=iso(now+1),f=>f.handoff.observedAt=iso(now-16*60000),f=>f.previous.sourceCommit='d'.repeat(40),f=>f.previous.topology.region='gcp:us-west1']){const f=fixture();mutate(f);if(f.approvedApprovalSha256===identityDigest(fixture().approval))f.approvedApprovalSha256=identityDigest(f.approval);assert.throws(()=>admitMigrationContinuation(f));}});
test('raw provider/source/checkpoint proof drift refuses despite unchanged summary flags',()=>{for(const [name,mutate]of [['front-settings',v=>v.result.bindings[0].text='enabled'],['backend-version',v=>v.result.resources.bindings[1].id='foreign'],['front-consumers',v=>v.result.push({script:'synthetic-front'})],['front-deployments',v=>v.result.deployments[0].versions[0].percentage=50],['target-checkpoint',v=>v[0].results[0].intent='copy-v11'],['target-schema',v=>v[0].results.push({type:'trigger',name:'extra',sql:'unreviewed'})],['source-schema',v=>v[0].results.pop()],['source-snapshot',v=>v[0].results[0].snapshot_digest='wrong'],['backend-enabled',v=>v.executionDigest='wrong']]){const f=fixture(),value=JSON.parse(f.evidence[name]);mutate(value);f.evidence[name]=Buffer.from(JSON.stringify(value));assert.throws(()=>verifyMigrationHandoffEvidence(f));}});
test('later approval link pins prior output and refuses reordered or rolled-back checkpoints',()=>{const f=fixture(),first=admitMigrationContinuation(f),previousPreparationSha256='e'.repeat(64),previousContinuationSha256='f'.repeat(64);const receipt={schema:'d1-storage-migration-continuation-v1',executionFenceVersion:1,status:'prepared-disabled',originalPreparationSha256:hash,previousPreparationSha256:hash,previousContinuationSha256:null,approval:f.approval,approvedApprovalSha256:f.approvedApprovalSha256,handoffSha256:hash,checkpoint:first.checkpoint,sourceCommit:f.previous.sourceCommit,roleInputSha256:f.previous.roleInputSha256,contractDigest:f.previous.contractDigest,topologyDigest:f.previous.topologyDigest,previousExecutionDigest:f.previous.executionDigest,executionDigest:first.executionDigest,nextPreparationSha256:previousPreparationSha256,rolloverSha256:hash,window:1,remoteOperations:false};const previous={...f.previous,expiresAt:f.approval.expiresAt,executionDigest:first.executionDigest},later=now+23*3600000+1000;const handoff={...f.handoff,previousPreparationSha256,executionDigest:first.executionDigest,target:{...f.handoff.target,executionDigest:first.executionDigest},stoppedAt:iso(later-1000),observedAt:iso(later)};const approval={...f.approval,previousPreparationSha256,previousContinuationSha256,approvedAt:iso(later),expiresAt:iso(later+3600000)};const args={...f,previous,previousPreparationSha256,previousContinuation:receipt,previousContinuationSha256,handoff,approval,approvedApprovalSha256:identityDigest(approval),now:later};assert.equal(admitMigrationContinuation(args).window,2);for(const mutate of [a=>a.previousContinuation.nextPreparationSha256=hash,a=>a.handoff.target.steps=3,a=>a.previousContinuationSha256=hash]){const b=structuredClone(args);mutate(b);assert.throws(()=>admitMigrationContinuation(b));}});

test('native D1 expiry during a page commits once and a second window continues both formats',async t=>{
 // Real D1 and original claim/step/commit; small synthetic copy APIs, injected
 // fetch transport. Full telemetry/runtime and cloud rollover are separate.
 const mf=new Miniflare({host:'127.0.0.1',cf:false,modules:true,script:SYNTHETIC_D1_WORKER,compatibilityDate:'2026-07-26',d1Databases:['SOURCE','TARGET']});t.after(async()=>{await closeSyntheticD1Bindings(mf);await mf.dispose();});const source=syntheticD1Binding(mf,'SOURCE'),target=syntheticD1Binding(mf,'TARGET');for(const d of [source,target])await d.prepare('CREATE TABLE synthetic_rows(id INTEGER PRIMARY KEY,format TEXT,value TEXT)').run();for(let i=1;i<=4;i++)await source.prepare('INSERT INTO synthetic_rows VALUES(?,?,?)').bind(i,i<3?'v1':'v11','value-'+i).run();
 const f=fixture();let clock=now-2000;const copied=[],api={authorityRestoreContractDigest:async()=>f.previous.contractDigest,authoritySchemaInventory:async()=>[],authoritySchemaDigest:async()=>'synthetic-base'};for(const n of ['freezeAuthorityRestoreSource','beginAuthorityRestore','sealAuthorityRestore','completeAuthorityVerification','promoteAuthorityRestore','finalizeAuthorityRestore','initializeAuthorityRestoreBootstrap'])api[n]=async()=>({});api.copyAuthorityPage=async()=>({state:'complete'});api.adoptAuthorityTypedPage=async()=>({done:true});api.bootstrapAuthorityRestorePage=async()=>({completed:true});
 api.copyAuthorityTypedPage=async(s,d,_c,_h,format)=>{copied.push(format);const rows=(await s.prepare('SELECT * FROM synthetic_rows WHERE format=? ORDER BY id').bind(format).all()).results;await d.batch(rows.map(r=>d.prepare('INSERT INTO synthetic_rows VALUES(?,?,?)').bind(r.id,r.format,r.value)));if(format==='v1')clock=now;return {reachedEnd:true};};api.verifyAuthorityTypedPage=async(s,d,_c,_h,format)=>{assert.deepEqual((await s.prepare('SELECT * FROM synthetic_rows WHERE format=? ORDER BY id').bind(format).all()).results,(await d.prepare('SELECT * FROM synthetic_rows WHERE format=? ORDER BY id').bind(format).all()).results);return {reachedEnd:true};};
 function window(executionDigest,expiresAt){const backend=createStorageMigrationBackend({api,contract:f.contract,contractDigest:f.previous.contractDigest,executionDigest,expiresAt,frozenSource:true,clock:()=>clock}),front=createStorageMigrationFront({contractDigest:f.previous.contractDigest,executionDigest,expiresAt,clock:()=>clock}),queue=[];const env={STORAGE_RESTORE_MODE:'enabled',STORAGE_RESTORE_EXECUTOR:{fetch:r=>backend.fetch(r,{STORAGE_RESTORE_MODE:'enabled',SOURCE:source,TARGET:target})},STORAGE_RESTORE_QUEUE:{send:async r=>queue.push(r)}};return {front,env,queue,deliver:body=>front.queue({messages:[{body,ack(){}}]},env)};}
 const first=window(f.previous.executionDigest,now-1000);await first.front.scheduled({},first.env);let stale;for(let i=0;i<4;i++){stale=first.queue.shift();if(i===3)await assert.rejects(first.deliver(stale));else await first.deliver(stale);}const checkpoint=await target.prepare('SELECT contract_digest,stage,steps,intent FROM _authority_operator_progress').first();assert.equal(checkpoint.steps,4);assert.equal(checkpoint.intent,null);assert.deepEqual(copied,['v1']);clock=now;await assert.rejects(first.deliver(first.queue[0]));assert.deepEqual(await target.prepare('SELECT contract_digest,stage,steps,intent FROM _authority_operator_progress').first(),checkpoint);
 const admitted=admitMigrationContinuation(f),roll=migrationRolloverStatement({contractDigest:f.previous.contractDigest,previousExecutionDigest:f.previous.executionDigest,executionDigest:admitted.executionDigest,expiresAt:admitted.expiresAt,checkpoint:admitted.checkpoint});assert.equal((await target.prepare(roll.sql).bind(...roll.params).all()).results.length,1);const next=window(admitted.executionDigest,Date.parse(admitted.expiresAt));await next.deliver(stale);assert.deepEqual(copied,['v1']);await next.front.scheduled({},next.env);while(next.queue.length)await next.deliver(next.queue.shift());assert.deepEqual(copied,['v1','v11']);assert.deepEqual((await source.prepare('SELECT * FROM synthetic_rows ORDER BY id').all()).results,(await target.prepare('SELECT * FROM synthetic_rows ORDER BY id').all()).results);assert.deepEqual(await target.prepare('SELECT stage,steps,intent FROM _authority_operator_progress').first(),{stage:null,steps:19,intent:null});
});

test('filesystem preparation reuses the generator, pins raw evidence, preserves old package and refuses overwrite/drift',async t=>{
 const {mkdtemp,mkdir,writeFile,readFile,rm,symlink,realpath}=await import('node:fs/promises'),{tmpdir}=await import('node:os'),{join}=await import('node:path'),{execFileSync}=await import('node:child_process');
 const {storageSha256}=await import('./d1-storage-plan.mjs'),{prepareStorageMigrationWorker}=await import('./d1-storage-migration-package.mjs'),{prepareMigrationContinuation}=await import('./d1-storage-migration-continuation.mjs');
 const root=await realpath(await mkdtemp(join(tmpdir(),'storage-continuation-')));t.after(()=>rm(root,{recursive:true,force:true}));const workerRoot=join(root,'worker');await mkdir(workerRoot);
 const write=(p,v)=>writeFile(p,typeof v==='string'||Buffer.isBuffer(v)?v:JSON.stringify(v),{mode:0o600});
 await write(join(workerRoot,'package.json'),{type:'module'});await write(join(workerRoot,'.gitignore'),'node_modules\n');await symlink(join(import.meta.dirname,'../node_modules'),join(workerRoot,'node_modules'));
 for(const d of ['migrations','typed-ingestion-migrations','ingestion-bridge-migrations','typed-v11-admission-migrations','typed-v1-admission-migrations','ingestion-isolation-migrations']){await mkdir(join(workerRoot,d));await write(join(workerRoot,d,'0001_synthetic.sql'),'CREATE TABLE synthetic_'+d.replaceAll('-','_')+'(id INTEGER PRIMARY KEY);');}
 await mkdir(join(workerRoot,'scripts'));for(const name of ['d1-storage-migration-worker.mjs','d1-storage-migration-placed.mjs','d1-storage-restore-runner.mjs'])await write(join(workerRoot,'scripts',name),await readFile(join(import.meta.dirname,name)));
 await mkdir(join(workerRoot,'src'));for(const name of ['authority-restore.ts','authority-restore-bootstrap.ts'])await write(join(workerRoot,'src',name),'export {};');
 const git=args=>execFileSync('git',args,{cwd:workerRoot,stdio:'pipe'});git(['init','-q']);git(['add','.']);git(['-c','user.name=Synthetic Test','-c','user.email=synthetic@example.invalid','commit','-qm','Synthetic frozen package']);
 const f=fixture(),contract={...f.contract,targetBaseSchema:[],targetBaseSchemaDigest:identityDigest([]),finalSchema:[],finalSchemaDigest:identityDigest([])},contractPath=join(root,'contract.json'),topologyPath=join(root,'topology.json');await write(contractPath,contract);await write(topologyPath,f.previous.topology);
 const previousDirectory=join(root,'previous');await prepareStorageMigrationWorker({workerRoot,contractPath,contractDigest:identityDigest(contract),directory:previousDirectory,expiresAt:iso(Date.now()+3600000),placedTopologyPath:topologyPath,placedTopologyDigest:f.previous.topologyDigest});
 const previous=JSON.parse(await readFile(join(previousDirectory,'preparation.json'))),priorBytes=await readFile(join(previousDirectory,'preparation.json')),previousPreparationSha256=storageSha256(priorBytes),time=Date.now(),handoff={...f.handoff,previousPreparationSha256,sourceCommit:previous.sourceCommit,contractDigest:previous.contractDigest,executionDigest:previous.executionDigest,stoppedAt:iso(time-2000),observedAt:iso(time),source:{...f.handoff.source,contractDigest:previous.contractDigest},target:{...f.handoff.target,contractDigest:previous.contractDigest,executionDigest:previous.executionDigest}};
 for(const [name,bytes]of Object.entries(f.evidence)){const value=JSON.parse(bytes);if(name.endsWith('-enabled'))Object.assign(value,{sourceCommit:previous.sourceCommit,executionDigest:previous.executionDigest,checkedAt:iso(time-4000)});if(name==='resource-pins')Object.assign(value,{sourceCommit:previous.sourceCommit,contractDigest:previous.contractDigest});if(name.endsWith('-deployments'))value.result.deployments[0].created_on=iso(time-2000);if(name.endsWith('-tail')){value.eventTimestamp=time-3000;value.logs[0].timestamp=time-2500;}if(['source-snapshot','target-checkpoint'].includes(name))value[0].results[0].contract_digest=previous.contractDigest;if(name==='target-checkpoint')value[0].results[0].execution_digest=previous.executionDigest;const path=join(root,name+'.json');await write(path,value);const item=handoff.evidence.find(x=>x.name===name);item.path=path;item.sha256=storageSha256(await readFile(path));}
 const handoffPath=join(root,'handoff.json');await write(handoffPath,handoff);const handoffSha256=storageSha256(await readFile(handoffPath)),approval={...f.approval,originalPreparationSha256:previousPreparationSha256,previousPreparationSha256,handoffSha256,approvedAt:iso(time),expiresAt:iso(time+2*3600000)},approvalPath=join(root,'approval.json');await write(approvalPath,approval);
 const options={workerRoot,previousDirectory,previousPreparationSha256,contractPath,handoffPath,handoffSha256,approvalPath,approvedApprovalSha256:identityDigest(approval),directory:join(root,'next')};
 const r=await prepareMigrationContinuation(options);assert.equal(r.status,'prepared-disabled');assert.equal(r.remoteOperations,false);assert.notEqual(r.executionDigest,previous.executionDigest);assert.deepEqual(await readFile(join(previousDirectory,'preparation.json')),priorBytes);const next=JSON.parse(await readFile(join(options.directory,'package/preparation.json')));assert.equal(next.sourceCommit,previous.sourceCommit);assert.equal(next.contractDigest,previous.contractDigest);assert.equal(next.mode,'disabled');
 const {DatabaseSync}=await import('node:sqlite'),db=new DatabaseSync(':memory:');t.after(()=>db.close());db.exec(MIGRATION_JOURNAL_DDL);db.prepare('INSERT INTO _authority_operator_progress VALUES(1,?,?,?,?,NULL)').run(previous.contractDigest,previous.executionDigest,handoff.target.stage,handoff.target.steps);const rolloverSql=await readFile(join(options.directory,'package/rollover.sql'),'utf8');assert.equal(db.prepare(rolloverSql).all().length,1);assert.equal(db.prepare('SELECT execution_digest FROM _authority_operator_progress').get().execution_digest,next.executionDigest);const receipt=JSON.parse(await readFile(join(options.directory,'package/continuation.json')));assert.equal(receipt.rolloverSha256,storageSha256(rolloverSql));assert.equal(receipt.executionFenceVersion,1);
 await assert.rejects(prepareMigrationContinuation(options));await write(join(root,'front-consumers.json'),{success:true,result:[{script:'foreign'}]});await assert.rejects(prepareMigrationContinuation({...options,directory:join(root,'tampered-evidence')}));await write(join(workerRoot,'src/authority-restore.ts'),'export const changed=true;');await assert.rejects(prepareMigrationContinuation({...options,directory:join(root,'dirty-source')}));
});

test('atomic execution rollover fences a hidden old claim and preserves uncertain outcomes',async t=>{
 for(const scenario of ['old-before-claim','already-claimed','rollover-response-lost','expired-rollover'])await t.test(scenario,async t=>{
  const mf=new Miniflare({host:'127.0.0.1',cf:false,modules:true,script:SYNTHETIC_D1_WORKER,compatibilityDate:'2026-07-26',d1Databases:['SOURCE','TARGET']});
  t.after(async()=>{await closeSyntheticD1Bindings(mf);await mf.dispose();});
  const source=syntheticD1Binding(mf,'SOURCE'),target=syntheticD1Binding(mf,'TARGET'),f=fixture();
  await target.prepare(MIGRATION_JOURNAL_DDL).run();
  await target.prepare("INSERT INTO _authority_operator_progress VALUES(1,?,?,'begin',1,NULL)").bind(f.previous.contractDigest,f.previous.executionDigest).run();
  const checkpoint={...f.handoff.target,stage:'begin',steps:1},nextDigest='e'.repeat(64),input={contractDigest:f.previous.contractDigest,previousExecutionDigest:f.previous.executionDigest,executionDigest:nextDigest,expiresAt:iso(Date.now()+3600000),checkpoint};
  const read=()=>target.prepare(MIGRATION_CONTINUATION_READ_SQL['target-checkpoint']).first();
  const original=await read(),statement=migrationRolloverStatement(scenario==='expired-rollover'?{...input,expiresAt:iso(Date.now()-1000)}:input);
  let entered,release;const paused=new Promise(r=>{entered=r;}),resume=new Promise(r=>{release=r;});let apiCalls=0,rolloverCalls=0;
  const api={authorityRestoreContractDigest:async()=>f.previous.contractDigest,beginAuthorityRestore:async()=>{apiCalls++;if(scenario==='already-claimed'){entered();await resume;}return {};}};
  const observed=new Proxy(target,{get(db,key){if(key!=='prepare'){const v=db[key];return typeof v==='function'?v.bind(db):v;}return sql=>{
   const st=db.prepare(sql);if(!sql.startsWith('UPDATE _authority_operator_progress SET intent='))return st;
   return {bind(...args){const bound=st.bind(...args);return {async all(){if(scenario==='old-before-claim'){entered();await resume;}return bound.all();}};}};
  };}});
  const old=createStorageMigrationWorker({api,contract:f.contract,contractDigest:f.previous.contractDigest,executionDigest:f.previous.executionDigest,expiresAt:now+1000,frozenSource:true,clock:()=>now});
  let acknowledgements=0;const env={SOURCE:source,TARGET:observed,STORAGE_RESTORE_MODE:'enabled',STORAGE_RESTORE_QUEUE:{send:async()=>{}}};
  const message={body:{schema:'d1-storage-restore-wakeup-v1',contractDigest:f.previous.contractDigest,stage:'begin',steps:1},ack(){acknowledgements++;}};
  const rollover=async()=>{rolloverCalls++;const r=await target.prepare(statement.sql).bind(...statement.params).all();if(scenario==='rollover-response-lost')throw Error('synthetic response lost');return r;};
  if(scenario==='expired-rollover'){assert.equal((await rollover()).results.length,0);assert.deepEqual(await read(),original);assert.equal(migrationRolloverDisposition(input,await read()),'not-applied');}
  else if(scenario==='rollover-response-lost'){
   await assert.rejects(rollover());assert.equal(migrationRolloverDisposition(input,await read()),'applied');assert.equal(rolloverCalls,1);
   assert.deepEqual(await read(),{...original,execution_digest:nextDigest});await assert.rejects(old.queue({messages:[message]},env));assert.equal(apiCalls,0);
   assert.throws(()=>migrationRolloverDisposition(input,{...original,steps:2}));
  }else{
   const running=old.queue({messages:[message]},env).then(()=>({ok:true}),error=>({error}));await paused;
   if(scenario==='old-before-claim'){
    assert.deepEqual(await read(),original);assert.equal((await rollover()).results.length,1);release();assert.ok((await running).error);
    assert.equal(apiCalls,0);assert.equal(acknowledgements,0);assert.deepEqual(await read(),{...original,execution_digest:nextDigest});
   }else{
    assert.equal((await read()).intent,'begin');assert.equal((await rollover()).results.length,0);
    const claimed=await read();assert.throws(()=>migrationRolloverDisposition(input,claimed));
    release();assert.equal((await running).ok,true);assert.equal(apiCalls,1);assert.equal((await read()).execution_digest,f.previous.executionDigest);
    assert.equal((await read()).steps,2);
   }
  }
 });
});


test('legacy unfenced journal refuses without mutation or automatic upgrade',async t=>{
 const mf=new Miniflare({host:'127.0.0.1',cf:false,modules:true,script:SYNTHETIC_D1_WORKER,compatibilityDate:'2026-07-26',d1Databases:['SOURCE','TARGET']});t.after(async()=>{await closeSyntheticD1Bindings(mf);await mf.dispose();});
 const target=syntheticD1Binding(mf,'TARGET'),source=syntheticD1Binding(mf,'SOURCE'),f=fixture(),ddl=MIGRATION_JOURNAL_DDL.replace('execution_digest TEXT NOT NULL,','');
 await target.prepare(ddl).run();await target.prepare("INSERT INTO _authority_operator_progress VALUES(1,?,'begin',1,NULL)").bind(f.previous.contractDigest).run();
 const worker=createStorageMigrationWorker({api:{authorityRestoreContractDigest:async()=>f.previous.contractDigest},contract:f.contract,contractDigest:f.previous.contractDigest,executionDigest:f.previous.executionDigest,expiresAt:now+1000,frozenSource:true,clock:()=>now});
 await assert.rejects(worker.scheduled({},{SOURCE:source,TARGET:target,STORAGE_RESTORE_MODE:'enabled',STORAGE_RESTORE_QUEUE:{send:async()=>assert.fail('no wakeup')}}),/MIGRATION_JOURNAL_INVALID/);
 assert.equal(await target.prepare("SELECT sql FROM sqlite_schema WHERE name='_authority_operator_progress'").first('sql'),ddl);
 assert.deepEqual(await target.prepare('SELECT * FROM _authority_operator_progress').first(),{id:1,contract_digest:f.previous.contractDigest,stage:'begin',steps:1,intent:null});
});
