import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, realpath, mkdir, writeFile, rm, readFile } from 'node:fs/promises';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { runProductionMaintenance, maintenanceHash, validateMaintenancePlan, renderMaintenanceEntry, maintenanceConfig, parseMaintenanceArguments } from './production-maintenance.mjs';
import { readOperation, openOperation } from '../../../scripts/lib/release-operation.mjs';

const previous='11111111-1111-4111-8111-111111111111',next='22222222-2222-4222-8222-222222222222',owner='a'.repeat(40);
async function fixture(t){
  const root=await realpath(await mkdtemp(join(tmpdir(),'maintenance-check-')));t.after(()=>rm(root,{recursive:true,force:true}));
  const assetDirectory=join(root,'assets');await mkdir(assetDirectory,{mode:0o700});
  const assets=[];for(const path of ['index.html','release-site-manifest.json',...Array.from({length:22},(_,i)=>`asset-${i}.js`)]){const bytes='synthetic '+path;await writeFile(join(assetDirectory,path),bytes,{mode:0o600});assets.push({path,bytes:Buffer.byteLength(bytes),sha256:maintenanceHash(bytes)});}
  const plan={schema:'production-maintenance-v1',toolingCommit:'b'.repeat(40),expiresAt:Date.now()+3600000,accountId:'c'.repeat(32),workerName:'synthetic-worker',databaseId:previous,origin:'https://synthetic.example',restoreSchemaDigest:'d'.repeat(64),wranglerSha256:'e'.repeat(64),predecessor:{sourceCommit:'f'.repeat(40),versionId:previous,bindingDigest:'1'.repeat(64),inventoryDigest:'3'.repeat(64),cron:['* * * * *'],durableNamespaceId:'2'.repeat(32),migrationTag:'upload-ingress-budget-v1',secretBindings:[]},assets};
  const events=[];let held=null,failAt=null,unknownLock=null,readMatches=true;
  const lock={createOwner:()=>owner,status:()=>held,acquire:o=>{events.push('acquire');assert.equal(held,null);held=o;if(unknownLock==='acquire')throw Error('lost');},assertOwned:o=>assert.equal(held,o),release:o=>{assert.equal(held,o);events.push('release');if(unknownLock==='release-before')throw Error('lost before');held=null;if(unknownLock==='release')throw Error('lost');}};
  const provider={dryRun:async()=>events.push('dry'),assertPredecessor:async()=>events.push('predecessor'),before:async n=>events.push('before:'+n),mutate:async n=>{events.push(n);if(failAt===n)throw Error('lost');return n==='upload'?{versionId:next}:{};},reconcile:async(n,id)=>{events.push('read:'+n);return {matched:readMatches,...(n==='upload'?{versionId:id??next}:{})};},verifyContained:async()=>events.push('contained'),assertRestoreSafe:async()=>events.push('restore-safe')};
  const options={plan,assetDirectory,operationDirectory:join(root,'operation'),repositoryRoot:root,cliPath:'unused',provider,checkSource:()=>{},coordinationFactory:()=>lock};
  return {root,plan,options,events,held:()=>held,fail:n=>{failAt=n;},lockFail:n=>{unknownLock=n;},matches:n=>{readMatches=n;},run:(action,extra={})=>runProductionMaintenance({...options,action,...(action==='enter'?{confirmation:'ENTER_PRODUCTION_MAINTENANCE'}:action==='restore'?{confirmation:'RESTORE_PRODUCTION_FROM_MAINTENANCE'}:action==='reconcile'?{confirmation:'RECONCILE_PRODUCTION_MAINTENANCE',executorStopped:true}:{}),...extra})};
}
test('inspection and dry build do not acquire or mutate; maintenance is a distinct journal kind',async t=>{const f=await fixture(t);assert.equal((await f.run('inspect')).remoteWrites,false);assert.deepEqual(f.events,[]);await f.run('dry-run');assert.deepEqual(f.events,['dry']);const r=await readOperation(f.options.operationDirectory);assert.equal(r.kind,'maintenance');await assert.rejects(openOperation({directory:f.options.operationDirectory,kind:'production',binding:{planDigest:r.bindingDigest},resume:true}));});
test('approved enter holds shared lock through verified containment; separately approved restore releases after both checks',async t=>{const f=await fixture(t);await assert.rejects(f.run('enter',{confirmation:null}),{code:'PRODUCTION_MAINTENANCE_CONFIRMATION_REQUIRED'});const r=await f.run('enter');assert.equal(r.coordination,'held');assert.equal(r.drainProven,false);assert.equal(f.held(),owner);assert.deepEqual(f.events.filter(x=>['upload','activate','disable_cron'].includes(x)),['upload','activate','disable_cron']);await f.run('restore');assert.equal(f.held(),null);assert.equal(f.events.at(-1),'release');});
test('lost activation response preserves intent/owner, never auto retries, and read-first recovery resumes only remaining step',async t=>{const f=await fixture(t);f.fail('activate');await assert.rejects(f.run('enter'));assert.equal(f.held(),owner);assert.equal((await readOperation(f.options.operationDirectory)).state.intent,'activate');await assert.rejects(f.run('enter',{resume:true}),{code:'PRODUCTION_MAINTENANCE_RECONCILE_REQUIRED'});f.matches(false);await assert.rejects(f.run('reconcile'),{code:'PRODUCTION_MAINTENANCE_RECONCILIATION_UNVERIFIED'});f.matches(true);f.fail(null);await f.run('reconcile');await f.run('enter',{resume:true});assert.equal(f.events.filter(x=>x==='activate').length,1);assert.equal(f.events.filter(x=>x==='disable_cron').length,1);});
test('lost acquire and release responses reconcile only their journaled exact boundaries',async t=>{const f=await fixture(t);f.lockFail('acquire');await assert.rejects(f.run('enter'));assert.equal((await readOperation(f.options.operationDirectory)).state.intent,'lock_acquire');await f.run('reconcile');f.lockFail(null);await f.run('enter',{resume:true});assert.equal(f.events.filter(x=>x==='acquire').length,1);f.lockFail('release');await assert.rejects(f.run('restore'));assert.equal((await readOperation(f.options.operationDirectory)).state.intent,'lock_release');await f.run('reconcile');assert.equal((await readOperation(f.options.operationDirectory)).state.lock,'released');assert.equal(f.events.filter(x=>x==='release').length,1);});
test('expired entry refuses while separately approved pinned restoration remains available',async t=>{const f=await fixture(t);await f.run('enter');await assert.rejects(f.run('enter',{resume:true,clock:()=>f.plan.expiresAt+1}),{code:'PRODUCTION_MAINTENANCE_PLAN_EXPIRED'});await f.run('restore',{clock:()=>f.plan.expiresAt+1});assert.equal(f.held(),null);});
test('source/package drift and changed schema prevent recovery writes without releasing owner',async t=>{const f=await fixture(t);await f.run('enter');f.options.provider.assertRestoreSafe=async()=>{throw Error('schema changed');};await assert.rejects(f.run('restore'));assert.equal(f.held(),owner);assert.equal(f.events.includes('restore'),false);await writeFile(join(f.options.operationDirectory,'candidate','entry.mjs'),'changed',{mode:0o600});await assert.rejects(f.run('restore'),{code:'PRODUCTION_MAINTENANCE_PACKAGE_CHANGED'});});
test('reconcile requires stopped executor and never releases still-owned completed restoration',async t=>{const f=await fixture(t);f.fail('restore_cron');await f.run('enter');await assert.rejects(f.run('restore'));await assert.rejects(f.run('reconcile',{executorStopped:false}),{code:'PRODUCTION_MAINTENANCE_EXECUTOR_NOT_STOPPED'});f.fail(null);await f.run('reconcile');assert.equal(f.held(),owner);await f.run('restore');assert.equal(f.held(),null);});
test('plan and CLI are closed; generated config has no production resource bindings',async t=>{const f=await fixture(t);assert.throws(()=>validateMaintenancePlan({...f.plan,extra:true}));assert.throws(()=>validateMaintenancePlan({...f.plan,assets:f.plan.assets.slice(1)}));assert.throws(()=>parseMaintenanceArguments(['--action','inspect','--action','enter']));const c=maintenanceConfig(f.plan,'./assets');assert.equal(c.d1_databases,undefined);assert.equal(c.r2_buckets,undefined);assert.deepEqual(c.durable_objects.bindings,[]);assert.deepEqual(c.triggers.crons,[]);assert.equal(c.migrations[0].new_sqlite_classes[0],'UploadIngressBudget');});
test('generated entry preserves static bytes, closes all dynamic methods/hosts, and exports inert DO methods',async t=>{const f=await fixture(t);const source=renderMaintenanceEntry(f.plan).replace("import {DurableObject} from 'cloudflare:workers';",'class DurableObject {}');const mod=await import('data:text/javascript;base64,'+Buffer.from(source).toString('base64'));let assets=0;const env={ASSETS:{fetch:async request=>{assets++;return new Response('exact synthetic static');}}};const fetch=(url,method='GET')=>mod.default.fetch(new Request(url,{method}),env);assert.equal(await (await fetch(f.plan.origin+'/')).text(),'exact synthetic static');assert.equal((await fetch('https://www.synthetic.example/')).status,308);for(const url of [f.plan.origin+'/api/health',f.plan.origin+'/api/v1/admin/action','https://admin.synthetic.example/','https://foreign.example/']){const r=await fetch(url);assert.equal(r.status,503);assert.equal(r.headers.get('retry-after'),'300');}for(const method of ['POST','PUT','DELETE','PATCH','OPTIONS'])assert.equal((await fetch(f.plan.origin+'/',method)).status,503);assert.equal(assets,1);const d=new mod.UploadIngressBudget();for(const method of ['acquire','renew','probe','status','release','alarm'])await assert.rejects(d[method](),/MAINTENANCE_ACTIVE/);assert.equal(d.fetch().status,503);assert.throws(()=>mod.default.queue(),/MAINTENANCE_ACTIVE/);});
test('expired pre-activation operation can only abort after stopped-executor and exact predecessor proof',async t=>{const f=await fixture(t);f.options.provider.before=async()=>{throw Error('read failed');};await assert.rejects(f.run('enter'));assert.equal(f.held(),owner);await assert.rejects(f.run('abort',{confirmation:'ABORT_UNACTIVATED_MAINTENANCE'}),{code:'PRODUCTION_MAINTENANCE_EXECUTOR_NOT_STOPPED'});await f.run('abort',{confirmation:'ABORT_UNACTIVATED_MAINTENANCE',executorStopped:true,clock:()=>f.plan.expiresAt+1});assert.equal(f.held(),null);assert.equal(f.events.includes('upload'),false);});
test('known still-owned release is read-reconciled before separate explicit release continuation',async t=>{const f=await fixture(t);await f.run('enter');f.lockFail('release-before');await assert.rejects(f.run('restore'));assert.equal(f.held(),owner);await f.run('reconcile');assert.equal(f.held(),owner);assert.equal((await readOperation(f.options.operationDirectory)).state.intent,null);f.lockFail(null);f.matches(false);await assert.rejects(f.run('restore'),{code:'PRODUCTION_MAINTENANCE_RESTORE_UNVERIFIED'});assert.equal(f.events.filter(x=>x==='release').length,1);f.matches(true);await f.run('restore');assert.equal(f.held(),null);});
test('pinned secret names inherit without retaining old plain-text variables or exposing values',async t=>{const f=await fixture(t);f.plan.predecessor.secretBindings=['secret_text:SYNTHETIC_AUTH','secret_key:SYNTHETIC_KEY'];const c=maintenanceConfig(f.plan,'./assets');assert.deepEqual(c.secrets.required,['SYNTHETIC_AUTH','SYNTHETIC_KEY']);assert.equal(c.keep_vars,undefined);assert.deepEqual(Object.keys(c.vars),['MAINTENANCE_PLAN_DIGEST']);});
