import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,mkdir,writeFile,readFile,rm,realpath,readdir} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {execFileSync} from 'node:child_process';
import {createMaintenanceAnalyticsProvider,parseMaintenanceTailCapture,proveMaintenanceAnalyticsInvocation} from './production-maintenance-analytics-provider.mjs';
import {maintenanceHash} from './production-maintenance.mjs';
const ids=Array.from({length:6},(_,i)=>`${i+1}`.repeat(8)+'-'+`${i+1}`.repeat(4)+'-'+`${i+1}`.repeat(4)+'-'+`${i+1}`.repeat(4)+'-'+`${i+1}`.repeat(12));
async function fixture(t){
 const root=await realpath(await mkdtemp(join(tmpdir(),'maintenance-analytics-')));t.after(()=>rm(root,{recursive:true,force:true}));
 const worker=join(root,'apps/worker');await mkdir(worker,{recursive:true});await mkdir(join(root,'.release-build'));await mkdir(join(worker,'node_modules/wrangler/wrangler-dist'),{recursive:true});
 await writeFile(join(root,'.gitignore'),'.release-build/\nnode_modules/\n');await writeFile(join(worker,'wrangler.analytics.example.jsonc'),await readFile(new URL('../wrangler.analytics.example.jsonc',import.meta.url)));
 const git=args=>execFileSync('/usr/bin/git',['-C',root,...args],{encoding:'utf8'}).trim();git(['init','-q']);git(['add','.']);git(['-c','user.name=Synthetic','-c','user.email=synthetic@example.invalid','commit','-qm','synthetic immutable fixture']);const commit=git(['rev-parse','HEAD']);
 const cliPath=join(worker,'node_modules/wrangler/wrangler-dist/cli.js');await writeFile(cliPath,'// synthetic pinned Wrangler\n');await writeFile(join(worker,'node_modules/wrangler/package.json'),JSON.stringify({name:'wrangler',version:'4.114.0',main:'wrangler-dist/cli.js'}));
 const plan={accountId:'c'.repeat(32),workerName:'synthetic-main',databaseId:ids[0],wranglerSha256:maintenanceHash(await readFile(cliPath))};
 const cutover={operationId:ids[1],analytics:{workerName:'tibotattle-analytics-synthetic'},candidate:{sourceCommit:commit,dependencyDigest:'a'.repeat(64),sourceId:'synthetic-source',sourceNamespace:'synthetic.namespace',ingestionDatabaseId:ids[2],ingestionDatabaseName:'synthetic-ingestion',analyticsDatabaseId:ids[3],analyticsDatabaseName:'synthetic-analytics',deletionLedgerDatabaseId:ids[4],deletionLedgerDatabaseName:'synthetic-ledger'}};
 const snapshot={repositoryRoot:root,workerDirectory:worker,dependencyPath:join(worker,'node_modules'),sourceCommit:commit,dependencyDigest:cutover.candidate.dependencyDigest};
 const state={exists:false,active:ids[0],cron:[],versionMode:new Map([[ids[0],'disabled'],[ids[5],'enabled']]),extra:false,duplicate:false,http:false,badDatabase:false,failCommand:false};const calls=[],spawns=[];let descriptor;
 const fetcher=async(url,options)=>{calls.push({url,method:options.method});assert.equal(options.method,'GET');const path=new URL(url).pathname;let result;
  if(path.endsWith('/workers/scripts'))result=state.exists?[{id:cutover.analytics.workerName}]:[];
  else if(path.endsWith('/deployments'))result={deployments:[{versions:[{version_id:state.active,percentage:100}]}]};
  else if(path.endsWith('/versions'))result={items:[...state.versionMode].map(([id,mode])=>({id,annotations:{'workers/tag':`analytics-${mode}-${cutover.operationId}`}}))};
  else if(path.includes('/versions/')){const id=path.split('/').at(-1),mode=state.versionMode.get(id),config=JSON.parse(await readFile(descriptor.files[mode].path));const bindings=[...config.d1_databases.map(d=>({type:'d1',name:d.binding,id:state.badDatabase?ids[0]:d.database_id})),...Object.entries(config.vars).map(([name,text])=>({type:'plain_text',name,text}))];if(state.extra)bindings.push({type:'secret_text',name:'FORBIDDEN'});if(state.duplicate)bindings[0]={...bindings[1]};result={id,annotations:{'workers/tag':`analytics-${mode}-${cutover.operationId}`},resources:{bindings}};}
  else if(path.endsWith('/subdomain'))result={enabled:state.http,previews_enabled:false};
  else if(path.endsWith('/routes')||path.endsWith('/records'))result=[];
  else if(path.endsWith('/schedules'))result={schedules:state.cron.map(cron=>({cron}))};
  else throw Error('unexpected synthetic request');
  return Response.json({success:true,result});
 };
 const options={plan,cutover,operationDirectory:join(root,'.release-build'),cliPath,fetcher,environment:{HOME:root,PATH:'/usr/bin',CLOUDFLARE_API_TOKEN:'synthetic-not-real-credential'},dependencyDigest:async()=>cutover.candidate.dependencyDigest,spawn:(cmd,args,opts)=>{spawns.push({cmd,args,opts});return {status:state.failCommand?1:0,stdout:'synthetic',stderr:''};}};
 const provider=createMaintenanceAnalyticsProvider(options);descriptor=await provider.prepare(snapshot);
 return {root,worker,plan,cutover,snapshot,descriptor,provider,options,state,calls,spawns};
}
const capture=(overrides={},value={})=>({scriptName:'tibotattle-analytics-synthetic',scriptVersion:{id:ids[5]},outcome:'ok',event:{cron:'* * * * *',scheduledTime:1000},exceptions:[],truncated:false,logs:[{level:'log',message:[JSON.stringify({event:'storage_analytics_schedule',state:'progress',reason:'step_limit',steps:8,recordsRead:200,queriesUsed:800,dailyPublications:1,graphCalculations:1,...value})]}],...overrides});
const pins={workerName:'tibotattle-analytics-synthetic',versionId:ids[5],notBeforeMs:500,nowMs:2000};
test('immutable local preparation pins exact three databases, no HTTP/secrets, and separates code from cron',async t=>{const f=await fixture(t);assert.equal(f.calls.length,0);assert.equal(f.spawns.length,0);for(const key of ['disabled','enabled','cron']){const c=JSON.parse(await readFile(f.descriptor.files[key].path));assert.equal(c.workers_dev,false);assert.equal(c.preview_urls,false);assert.deepEqual(c.routes,[]);assert.equal(c.secrets,undefined);assert.equal(c.d1_databases.length,3);assert.equal(c.vars.STORAGE_ANALYTICS_MODE,key==='disabled'?'disabled':'enabled');assert.deepEqual(c.triggers.crons,key==='cron'?['* * * * *']:[]);}await f.provider.dryRun(f.snapshot,f.descriptor);assert.equal(f.spawns.length,2);assert.ok(f.spawns.every(x=>x.args.includes('--dry-run')&&!x.opts.env.CLOUDFLARE_API_TOKEN));});
test('each explicit mutation issues one command; unique discovery and readback remain independent',async t=>{const f=await fixture(t),s=f.snapshot,d=f.descriptor;await f.provider.assertAbsent();await f.provider.deployDisabled(s,d);assert.equal(f.spawns.length,1);assert.equal(f.spawns[0].args[1],'deploy');assert.ok(f.spawns[0].args.includes('--tag'));assert.ok(f.spawns[0].args.includes('--message'));f.state.exists=true;assert.equal(await f.provider.discoverDisabled(s,d),ids[0]);await f.provider.activateDisabled(s,d,ids[0]);await f.provider.verifyDisabled(s,d,ids[0]);assert.equal(f.spawns.length,2);await f.provider.uploadEnabled(s,d);assert.equal(f.spawns.length,3);assert.equal(await f.provider.discoverEnabled(s,d),ids[5]);await f.provider.activateEnabled(s,d,ids[5]);assert.equal(f.spawns.length,4);f.state.active=ids[5];await f.provider.verifyEnabledUnscheduled(s,d,ids[5]);await f.provider.enableCron(s,d,ids[5]);assert.equal(f.spawns.length,5);f.state.cron=['* * * * *'];await f.provider.verifyEnabled(s,d,ids[5]);assert.equal(f.spawns.length,5);});
test('existing Worker, foreign/duplicate/secret bindings, and HTTP ingress refuse',async t=>{const f=await fixture(t),s=f.snapshot,d=f.descriptor;f.state.exists=true;await assert.rejects(f.provider.deployDisabled(s,d),{code:'PRODUCTION_MAINTENANCE_ANALYTICS_WORKER_ALREADY_EXISTS'});for(const key of ['extra','duplicate','badDatabase','http']){f.state[key]=true;await assert.rejects(f.provider.verifyDisabled(s,d,ids[0]));f.state[key]=false;}assert.equal(f.spawns.length,0);});
test('source, dependency, descriptor and configuration changes refuse before commands',async t=>{const f=await fixture(t);await assert.rejects(f.provider.dryRun({...f.snapshot,sourceCommit:'e'.repeat(40)},f.descriptor));await assert.rejects(f.provider.dryRun(f.snapshot,{...f.descriptor,workerName:'foreign'}));await writeFile(f.descriptor.files.enabled.path,'{}',{mode:0o600});await assert.rejects(f.provider.dryRun(f.snapshot,f.descriptor));assert.equal(f.spawns.length,0);});
test('unknown command failure is retained and never automatically retried',async t=>{const f=await fixture(t);f.state.failCommand=true;await assert.rejects(f.provider.deployDisabled(f.snapshot,f.descriptor),{code:'PRODUCTION_MAINTENANCE_COMMAND_UNCERTAIN'});assert.equal(f.spawns.length,1);for(const name of await readdir(join(f.root,'.release-build')))if(name.startsWith('provider-'))assert.equal((await readFile(join(f.root,'.release-build',name),'utf8')).includes('synthetic-not-real-credential'),false);});
test('pretty concatenated raw tail supports escaped braces and actual scheduled version proof',()=>{const event=capture();event.logs.unshift({level:'log',message:['ignored {"quoted":"}\\\\"}']});const bytes=Buffer.from(JSON.stringify({unrelated:true},null,2)+'\n'+JSON.stringify(event,null,2)+'\n'+JSON.stringify(capture()));assert.equal(parseMaintenanceTailCapture(bytes).length,3);const proof=proveMaintenanceAnalyticsInvocation(bytes,pins);assert.equal(proof.qualifiedInvocations,2);assert.equal(proof.captureSha256,maintenanceHash(bytes));});
test('manual HTTP, wrong version, preactivation and future events cannot satisfy natural proof',()=>{for(const value of [{event:{request:{url:'https://synthetic.invalid'}}},{scriptVersion:{id:ids[0]}},{event:{cron:'* * * * *',scheduledTime:499}},{event:{cron:'* * * * *',scheduledTime:2001}}])assert.throws(()=>proveMaintenanceAnalyticsInvocation(Buffer.from(JSON.stringify(capture(value))),pins),{code:'PRODUCTION_MAINTENANCE_ANALYTICS_NATURAL_INVOCATION_MISSING'});});
test('tail failures, capacity deferral, missing/malformed meters, truncation and oversize captures refuse',()=>{for(const value of [{outcome:'exception'},{truncated:true},{exceptions:[{name:'Synthetic'}]},{logs:[]}])assert.throws(()=>proveMaintenanceAnalyticsInvocation(Buffer.from(JSON.stringify(capture(value))),pins));for(const value of [{reason:'capacity'},{state:'unavailable'},{queriesUsed:901},{steps:9},{queriesUsed:0.5},{unreviewed:'private'}])assert.throws(()=>proveMaintenanceAnalyticsInvocation(Buffer.from(JSON.stringify(capture({},value))),pins));for(const b of [Buffer.from('connected\n{}'),Buffer.from('{'),Buffer.alloc(2_000_001),Buffer.from('{}'.repeat(257))])assert.throws(()=>parseMaintenanceTailCapture(b));});
test('natural proof reads the bounded private raw file and rechecks live exact scheduler',async t=>{const f=await fixture(t);f.state.active=ids[5];f.state.cron=['* * * * *'];const path=join(f.root,'.release-build/capture.json');const event=capture({event:{cron:'* * * * *',scheduledTime:Date.now()}});await writeFile(path,JSON.stringify(event,null,2),{mode:0o600});const proof=await f.provider.verifyNaturalInvocation(f.snapshot,f.descriptor,ids[5],path,Date.now()-10000);assert.equal(proof.qualifiedInvocations,1);assert.equal(f.spawns.length,0);f.state.http=true;await assert.rejects(f.provider.verifyNaturalInvocation(f.snapshot,f.descriptor,ids[5],path,0));});

test('stopped upload recovery distinguishes exact zero tagged versions from ambiguous or already uploaded state',async t=>{const f=await fixture(t);await assert.rejects(f.provider.verifyEnabledUploadAbsent(f.snapshot,f.descriptor,ids[0]),{code:'PRODUCTION_MAINTENANCE_ANALYTICS_UPLOAD_UNCERTAIN'});f.state.versionMode.delete(ids[5]);await f.provider.verifyEnabledUploadAbsent(f.snapshot,f.descriptor,ids[0]);assert.equal(f.spawns.length,0);f.state.cron=['* * * * *'];await assert.rejects(f.provider.verifyEnabledUploadAbsent(f.snapshot,f.descriptor,ids[0]),{code:'PRODUCTION_MAINTENANCE_ANALYTICS_SCHEDULE_CHANGED'});});
