import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,mkdir,readFile,writeFile,cp,realpath,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {execFileSync} from 'node:child_process';
import {createMaintenanceCutoverProvider} from './production-maintenance-cutover-provider.mjs';
import {maintenanceHash} from './production-maintenance.mjs';
import {maintenanceBindingDigest} from './production-maintenance-provider.mjs';
const ids=Array.from({length:6},(_,i)=>`${i+1}`.repeat(8)+'-'+`${i+1}`.repeat(4)+'-'+`${i+1}`.repeat(4)+'-'+`${i+1}`.repeat(4)+'-'+`${i+1}`.repeat(12));
async function fixture(t){
 const root=await realpath(await mkdtemp(join(tmpdir(),'cutover-provider-')));t.after(()=>rm(root,{recursive:true,force:true}));
 const worker=join(root,'apps/worker'),deps=join(worker,'node_modules');await mkdir(join(deps,'wrangler/wrangler-dist'),{recursive:true});await mkdir(join(worker,'scripts'));await mkdir(join(root,'.release-build/public-release-site'),{recursive:true});
 await writeFile(join(root,'.gitignore'),'.release-build/\nnode_modules\n');
 const config={name:'synthetic-main',main:'src/index.ts',workers_dev:false,preview_urls:false,routes:['synthetic.example','www.synthetic.example','admin.synthetic.example'].map(pattern=>({pattern,custom_domain:true})),vars:{PUBLIC_ORIGIN:'https://synthetic.example',ACCOUNTLESS_ENROLLMENT_MODE:'enabled'},assets:{binding:'ASSETS',directory:'old',not_found_handling:'404-page',run_worker_first:true},migrations:[{tag:'upload-ingress-budget-v1',new_sqlite_classes:['UploadIngressBudget']}],durable_objects:{bindings:[{name:'UPLOAD_INGRESS_BUDGET',class_name:'UploadIngressBudget'}]},r2_buckets:[{binding:'QUARANTINE',bucket_name:'synthetic'}],d1_databases:[{binding:'USAGE_MONITOR_DB',database_id:ids[0]},{binding:'DELETION_LEDGER',database_id:ids[4]}],env:{production:{}}};
 await writeFile(join(worker,'wrangler.jsonc'),JSON.stringify(config));for(const name of ['check-local-workspace-packages.mjs','check-deployment-endpoints.mjs','release-preflight.mjs'])await writeFile(join(worker,'scripts',name),'// synthetic source check fixture\n');
 const git=args=>execFileSync('/usr/bin/git',['-C',root,...args],{encoding:'utf8'}).trim();git(['init','-q']);git(['add','.']);git(['-c','user.name=Synthetic','-c','user.email=synthetic@example.invalid','commit','-qm','fixture']);const sourceCommit=git(['rev-parse','HEAD']);
 const cliPath=join(deps,'wrangler/wrangler-dist/cli.js');await writeFile(cliPath,'// synthetic pinned cli\n');await writeFile(join(deps,'wrangler/package.json'),JSON.stringify({name:'wrangler',version:'4.114.0',main:'wrangler-dist/cli.js'}));
 const assets=[];for(const path of ['index.html','release-site-manifest.json',...Array.from({length:22},(_,i)=>`asset-${i}.js`)]){const body='synthetic '+path;await writeFile(join(root,'.release-build/public-release-site',path),body);assets.push({path,bytes:Buffer.byteLength(body),sha256:maintenanceHash(body)});}
 const ordinary=[{name:'ASSETS',type:'assets'},{name:'QUARANTINE',type:'r2_bucket',bucket_name:'synthetic'}];
 const oldBindings=[...ordinary,{name:'DELETION_LEDGER',type:'d1',id:ids[4]}];
 const plan={accountId:'a'.repeat(32),workerName:config.name,databaseId:ids[0],origin:config.vars.PUBLIC_ORIGIN,wranglerSha256:maintenanceHash(await readFile(cliPath)),assets,predecessor:{versionId:ids[0],bindingDigest:maintenanceBindingDigest(oldBindings),migrationTag:'upload-ingress-budget-v1',secretBindings:['secret_text:SYNTHETIC'],durableNamespaceId:'b'.repeat(32),cron:['* * * * *']}};
 const cutover={operationId:ids[1],maintenanceVersionId:ids[1],inventoryDigest:'f'.repeat(64),analytics:{workerName:'tibotattle-analytics-synthetic'},candidate:{sourceCommit,dependencyDigest:'c'.repeat(64),ingestionDatabaseId:ids[2],analyticsDatabaseId:ids[3],deletionLedgerDatabaseId:ids[4],ingestionDatabaseName:'synthetic-ingestion',analyticsDatabaseName:'synthetic-analytics',deletionLedgerDatabaseName:'synthetic-ledger',sourceNamespace:'synthetic namespace',sourceId:'synthetic-source'}};
 const operation=join(root,'.release-build/operation');await mkdir(operation);const state={duplicate:null,active:ids[1],badCommand:false},calls=[],commands=[];let snapshot;
 const fetcher=async url=>{calls.push(url);const path=new URL(url).pathname;let result;
  if(path.endsWith('/deployments'))result={deployments:[{versions:[{version_id:state.active,percentage:100}]}]};
  else if(path.endsWith('/versions'))result={items:[{id:ids[5],annotations:{'workers/tag':`typed-cutover-${cutover.operationId}`}}]};
  else if(path.endsWith('/versions/'+ids[0]))result={id:ids[0],resources:{bindings:oldBindings}};
  else if(path.endsWith('/versions/'+ids[5])){const c=JSON.parse(await readFile(snapshot.configurationPath));const bindings=[...ordinary,...c.d1_databases.map(d=>({name:d.binding,type:'d1',id:d.database_id})),...Object.entries(c.vars).map(([name,text])=>({name,type:'plain_text',text})),{name:'SYNTHETIC',type:'secret_text'},{name:'UPLOAD_INGRESS_BUDGET',type:'durable_object_namespace',namespace_id:plan.predecessor.durableNamespaceId}];if(state.duplicate){const rows=bindings.filter(b=>b.type===state.duplicate);Object.assign(rows[1],rows[0]);}result={id:ids[5],annotations:{'workers/tag':`typed-cutover-${cutover.operationId}`},resources:{bindings}};}
  else throw Error('unexpected network path');return Response.json({success:true,result});};
 const provider=await createMaintenanceCutoverProvider({plan,cutover,operationDirectory:operation,candidateWorkerDirectory:worker,qualificationRoot:root,restoreContractPath:join(root,'unused'),ledgerSchemaPath:join(root,'unused-ledger'),cliPath,fetcher,environment:{PATH:process.env.PATH,HOME:root,CLOUDFLARE_API_TOKEN:'synthetic-not-real-token'},dependencyDigest:async()=>cutover.candidate.dependencyDigest,snapshotFactory:async()=>({repositoryRoot:root,workerDirectory:worker,dependencyPath:deps,dependencyDigest:cutover.candidate.dependencyDigest,git}),stageAssets:async options=>{assert.equal(options.expectedSourceCommit,sourceCommit);await cp(join(root,'.release-build/public-release-site'),options.destinationDirectory,{recursive:true});},spawn:(command,args)=>{commands.push(args);return {status:state.badCommand?1:0,stdout:'',stderr:''};}});
 snapshot=await provider.prepare();return {root,provider,plan,cutover,state,calls,commands,snapshot};
}
test('snapshot preparation and dry run are local, exact config/asset/dependency pins remain immutable',async t=>{const f=await fixture(t);assert.equal(f.calls.length,0);assert.equal(f.commands.length,3);await f.provider.dryRun(f.snapshot);assert.equal(f.commands.at(-1).includes('--dry-run'),true);assert.equal(f.calls.length,0);const cron=JSON.parse(await readFile(f.snapshot.cronConfigurationPath));assert.deepEqual(cron.triggers.crons,['* * * * *']);await writeFile(f.snapshot.cronConfigurationPath,'{}',{mode:0o600});await assert.rejects(f.provider.verifySnapshot(f.snapshot),{code:'PRODUCTION_MAINTENANCE_CUTOVER_CONFIG_CHANGED'});});
test('actual provider readback rejects duplicated D1 or variable names even when total counts match',async t=>{const f=await fixture(t);assert.equal(await f.provider.reconcileUpload(null,f.snapshot),ids[5]);for(const type of ['d1','plain_text']){f.state.duplicate=type;await assert.rejects(f.provider.reconcileUpload(ids[5],f.snapshot),{code:'PRODUCTION_MAINTENANCE_CUTOVER_CONFIG_BINDINGS_CHANGED'});}assert.equal(f.commands.length,3);});
test('unknown upload command stops after one invocation, retaining exact files for read reconciliation',async t=>{const f=await fixture(t);f.state.badCommand=true;await assert.rejects(f.provider.upload(f.snapshot),{code:'PRODUCTION_MAINTENANCE_COMMAND_UNCERTAIN'});assert.equal(f.commands.length,4);await f.provider.verifySnapshot(f.snapshot);assert.equal(f.commands.length,4);});
