import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, realpath, rm } from 'node:fs/promises';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { identityDigest, openOperation, readOperation } from '../../../scripts/lib/release-operation.mjs';
import { runProductionMaintenanceCutover, validateMaintenanceCutoverPlan } from './production-maintenance-cutover.mjs';
import { runProductionMaintenance } from './production-maintenance.mjs';
import { renderMaintenanceCutoverConfig, proveMaintenanceLifecycleInvocation } from './production-maintenance-cutover-provider.mjs';
const old='11111111-1111-4111-8111-111111111111',maintenance='22222222-2222-4222-8222-222222222222',ingestion='33333333-3333-4333-8333-333333333333',analytics='44444444-4444-4444-8444-444444444444',ledger='55555555-5555-4555-8555-555555555555',newVersion='66666666-6666-4666-8666-666666666666',owner='a'.repeat(40);
async function fixture(t){
 const root=await realpath(await mkdtemp(join(tmpdir(),'maintenance-cutover-')));t.after(()=>rm(root,{recursive:true,force:true}));
 const plan={schema:'production-maintenance-v1',toolingCommit:'b'.repeat(40),expiresAt:Date.now()+3600000,accountId:'c'.repeat(32),workerName:'synthetic-worker',databaseId:old,origin:'https://synthetic.example',restoreSchemaDigest:'d'.repeat(64),wranglerSha256:'e'.repeat(64),predecessor:{sourceCommit:'f'.repeat(40),versionId:old,bindingDigest:'1'.repeat(64),inventoryDigest:'3'.repeat(64),cron:['* * * * *'],durableNamespaceId:'2'.repeat(32),migrationTag:'upload-ingress-budget-v1',secretBindings:['secret_text:SYNTHETIC_SECRET']},assets:['index.html','release-site-manifest.json',...Array.from({length:22},(_,i)=>`asset-${i}.js`)].map(path=>({path,bytes:1,sha256:'1'.repeat(64)}))};
 const directory=join(root,'operation'),op=await openOperation({directory,kind:'maintenance',binding:{planDigest:identityDigest(plan)}});
 await op.save({schema:1,owner,phase:'contained',intent:null,uploadedVersion:maintenance,everActivated:true,lock:'held',cutover:null});const id=op.record.id;op.close();
 const proof={schema:'production-maintenance-typed-proof-v1',...Object.fromEntries(['restoreContractSha256','restoreContractDigest','ingestionQualificationSha256','analyticsQualificationSha256','ledgerSchemaFileSha256','ledgerMigrationInputsSha256','ledgerStateSha256'].map(k=>[k,'1'.repeat(64)]))};
 const cutover={analytics:{workerName:'tibotattle-analytics-synthetic'},inventoryDigest:'7'.repeat(64),schema:'production-maintenance-cutover-v1',maintenancePlanDigest:identityDigest(plan),operationId:id,owner,maintenanceVersionId:maintenance,expiresAt:Date.now()+3600000,candidate:{sourceCommit:'9'.repeat(40),dependencyDigest:'8'.repeat(64),ingestionDatabaseId:ingestion,analyticsDatabaseId:analytics,deletionLedgerDatabaseId:ledger,ingestionDatabaseName:'synthetic-ingestion',analyticsDatabaseName:'synthetic-analytics',deletionLedgerDatabaseName:'synthetic-ledger',sourceNamespace:'synthetic namespace',sourceId:'synthetic-source'},proof};
 const events=[];let held=owner,failAt=null,verified=true,drift=false,pending=false;
 const lock={status:()=>held,assertOwned:id=>assert.equal(held,id),release:id=>{assert.equal(held,id);events.push('release');if(failAt==='release-before')throw Error('before');held=null;if(failAt==='release-after')throw Error('after');}};
 const provider={prepare:async()=>{events.push('prepare');return {admissionDigest:null};},initializeAnalytics:async()=>{events.push('initialize');const c=(await readOperation(directory)).state.cutover;assert.equal(c.oldRestoreForbidden,true);assert.equal(c.intent,'analytics_initialize');if(failAt==='initialize')throw Error('lost');return {state:'present',analyticsCaughtUp:false,privacyReady:false};},readAnalyticsRegistration:async()=>({state:'present',writeAttempted:false}),verifySnapshot:async()=>{events.push('snapshot');if(drift)throw Error('drift');},dryRun:async()=>events.push('dry'),verifyContained:async()=>events.push('contained'),admit:async(s,stage)=>{events.push('admit');if(failAt==='proof')throw Error('proof');return {contractDigest:proof.restoreContractDigest,stage,analyticsCaughtUp:stage==='full'};},upload:async()=>{events.push('upload');if(failAt==='upload')throw Error('lost');},reconcileUpload:async()=>{events.push('read-upload');return newVersion;},activate:async()=>{events.push('activate');const c=(await readOperation(directory)).state.cutover;assert.equal(c.oldRestoreForbidden,true);assert.equal(c.intent,'activate');assert.match(c.snapshot.admissionDigest,/^[a-f0-9]{64}$/);if(failAt==='activate')throw Error('lost');},verifyActivated:async()=>{events.push('read-active');if(!verified)throw Error('not active');},verifyActivationPending:async()=>{if(!pending)throw Error('not exact maintenance');events.push('read-maintenance');},enableMainCron:async()=>{events.push('main-cron');if(failAt==='main-cron')throw Error('lost');},verifyMainNaturalInvocation:async()=>{events.push('main-natural');return {actualScheduled:true};}};
 const analyticsProvider={prepare:async()=>({schema:'synthetic-descriptor'}),dryRun:async()=>events.push('analytics-dry'),assertAbsent:async()=>{},deployDisabled:async()=>events.push('analytics-disabled'),discoverDisabled:async()=>old,verifyDisabled:async()=>{},uploadEnabled:async()=>events.push('analytics-upload'),discoverEnabled:async()=>newVersion,activateEnabled:async()=>{events.push('analytics-activate');const c=(await readOperation(directory)).state.cutover;assert.equal(c.oldRestoreForbidden,true);assert.equal(c.intent,'analytics_activate');if(failAt==='analytics-activate')throw Error('lost');},verifyEnabledUnscheduled:async()=>{},enableCron:async()=>events.push('analytics-cron'),verifyEnabled:async()=>{},verifyNaturalInvocation:async()=>{events.push('analytics-natural');return {actualScheduled:true};}};
 const options={analyticsProvider,analyticsCapturePath:'synthetic-tail',lifecycleCapturePath:'synthetic-tail',plan,cutover,operationDirectory:directory,repositoryRoot:root,candidateWorkerDirectory:root,qualificationRoot:root,restoreContractPath:join(root,'contract'),ledgerSchemaPath:join(root,'ledger'),cliPath:'unused',provider,coordinationFactory:()=>lock,checkSource:()=>{}};
 return {root,plan,cutover,options,events,held:()=>held,fail:x=>{failAt=x;},drift:x=>{drift=x;},verified:x=>{verified=x;},pending:x=>{pending=x;},state:async()=>(await readOperation(directory)).state,run:(action,extra={})=>runProductionMaintenanceCutover({...options,action,...(action==='apply'?{confirmation:'CUT_OVER_QUALIFIED_TYPED_PRODUCTION'}:action==='reconcile'?{confirmation:'RECONCILE_TYPED_PRODUCTION_CUTOVER',executorStopped:true}:{}),...extra})};
}
test('dry preparation uses existing owner; approved activation latches old restore forbidden before call and releases only verified',async t=>{const f=await fixture(t);await f.run('dry-run');assert.deepEqual(f.events,['prepare','dry','analytics-dry']);assert.equal(f.held(),owner);await assert.rejects(f.run('apply',{confirmation:null}),{code:'PRODUCTION_MAINTENANCE_CUTOVER_CONFIRMATION_REQUIRED'});await f.run('apply');assert.equal(f.held(),null);const s=await f.state();assert.equal(s.cutover.phase,'verified');assert.equal(s.cutover.oldRestoreForbidden,true);assert.equal(f.events.filter(x=>x==='activate').length,1);assert.equal(f.events.at(-1),'release');});
test('lost activation is forward-only and cannot fall back to ordinary old-source restoration',async t=>{const f=await fixture(t);f.fail('activate');await assert.rejects(f.run('apply'));assert.equal(f.held(),owner);assert.equal((await f.state()).cutover.oldRestoreForbidden,true);await assert.rejects(runProductionMaintenance({plan:f.plan,operationDirectory:f.options.operationDirectory,repositoryRoot:f.root,action:'restore',confirmation:'RESTORE_PRODUCTION_FROM_MAINTENANCE',provider:{},coordinationFactory:f.options.coordinationFactory,checkSource:()=>{}}),{code:'PRODUCTION_MAINTENANCE_CUTOVER_FORWARD_ONLY'});await assert.rejects(f.run('apply'),{code:'PRODUCTION_MAINTENANCE_CUTOVER_RECONCILE_REQUIRED'});f.verified(false);await assert.rejects(f.run('reconcile'));assert.equal((await f.state()).cutover.intent,'activate');f.verified(true);await f.run('reconcile');assert.equal(f.held(),owner);await f.run('apply');assert.equal(f.events.filter(x=>x==='activate').length,1);assert.equal(f.held(),null);});
test('copy/ledger proof refusal and snapshot drift prevent target activation',async t=>{const f=await fixture(t);f.fail('proof');await assert.rejects(f.run('apply'));assert.equal((await f.state()).cutover.oldRestoreForbidden,false);assert.equal(f.events.includes('upload'),false);f.fail(null);f.drift(true);await assert.rejects(f.run('apply'));assert.equal(f.events.includes('activate'),false);assert.equal(f.held(),owner);});
test('pending upload is read reconciled without a second upload; changed plan is refused',async t=>{const f=await fixture(t);f.fail('upload');await assert.rejects(f.run('apply'));assert.equal((await f.state()).cutover.oldRestoreForbidden,false);await assert.rejects(f.run('apply',{cutover:{...f.cutover,expiresAt:f.cutover.expiresAt+1000}}),{code:'PRODUCTION_MAINTENANCE_CUTOVER_PLAN_CHANGED'});await f.run('reconcile');f.fail(null);await f.run('apply');assert.equal(f.events.filter(x=>x==='upload').length,1);});
test('expired entry blocks activation but exact already-verified release can finish after expiry',async t=>{const f=await fixture(t);await assert.rejects(f.run('apply',{clock:()=>f.cutover.expiresAt+1}),{code:'PRODUCTION_MAINTENANCE_CUTOVER_PLAN_EXPIRED'});f.fail('release-before');await assert.rejects(f.run('apply'));await f.run('reconcile');assert.equal(f.held(),owner);f.fail(null);await f.run('apply',{clock:()=>f.cutover.expiresAt+1});assert.equal(f.held(),null);});
test('lost successful release is read-only reconciled; unrelated owner or unstopped executor never qualifies',async t=>{const f=await fixture(t);f.fail('release-after');await assert.rejects(f.run('apply'));await assert.rejects(f.run('reconcile',{executorStopped:false}),{code:'PRODUCTION_MAINTENANCE_CUTOVER_RECONCILIATION_CONFIRMATION_REQUIRED'});await f.run('reconcile');assert.equal((await f.state()).lock,'released');assert.equal(f.events.filter(x=>x==='release').length,1);});
test('cutover plan refuses source/target/ledger aliasing and unknown descriptors',async t=>{const f=await fixture(t);assert.throws(()=>validateMaintenanceCutoverPlan({...f.cutover,candidate:{...f.cutover.candidate,analyticsDatabaseId:ingestion}},f.plan));assert.throws(()=>validateMaintenanceCutoverPlan({...f.cutover,proof:{...f.cutover.proof,verified:true}},f.plan));});
test('configuration changes only typed targets/mode/source while preserving production security and DO lineage',async t=>{const f=await fixture(t);const baseline={name:f.plan.workerName,main:'src/index.ts',workers_dev:false,preview_urls:false,routes:['synthetic.example','www.synthetic.example','admin.synthetic.example'].map(pattern=>({pattern,custom_domain:true})),vars:{PUBLIC_ORIGIN:f.plan.origin,ACCOUNTLESS_ENROLLMENT_MODE:'enabled',ACCESS_AUD:'synthetic-audience',TELEMETRY_STORAGE_MODE:'json'},assets:{binding:'ASSETS',directory:'old',not_found_handling:'404-page',run_worker_first:true},migrations:[{tag:f.plan.predecessor.migrationTag,new_sqlite_classes:['UploadIngressBudget']}],durable_objects:{bindings:[{name:'UPLOAD_INGRESS_BUDGET',class_name:'UploadIngressBudget'}]},r2_buckets:[{binding:'QUARANTINE',bucket_name:'synthetic-quarantine'}],d1_databases:[{binding:'USAGE_MONITOR_DB',database_id:old},{binding:'DELETION_LEDGER',database_id:ledger}],env:{production:{}}};const c=renderMaintenanceCutoverConfig(baseline,f.plan,f.cutover);assert.deepEqual(c.r2_buckets,baseline.r2_buckets);assert.deepEqual(c.durable_objects,baseline.durable_objects);assert.deepEqual(c.migrations,baseline.migrations);assert.equal(c.vars.ACCESS_AUD,'synthetic-audience');assert.equal(c.vars.ACCOUNTLESS_ENROLLMENT_MODE,'enabled');assert.equal(c.vars.TELEMETRY_STORAGE_MODE,'typed');assert.deepEqual(c.d1_databases.map(d=>d.database_id),[ingestion,analytics,ledger]);assert.deepEqual(c.triggers.crons,[]);assert.deepEqual(c.secrets.required,['SYNTHETIC_SECRET']);assert.throws(()=>renderMaintenanceCutoverConfig({...baseline,d1_databases:[{binding:'USAGE_MONITOR_DB',database_id:ingestion},{binding:'DELETION_LEDGER',database_id:ledger}]},f.plan,f.cutover));});
test('D1 labels share the maintained operator contract, independently of63-character Worker names',async t=>{const f=await fixture(t);f.cutover.candidate.ingestionDatabaseName='tibotattle-production-ingestion-'+f.cutover.operationId;f.cutover.candidate.analyticsDatabaseName='tibotattle-production-analytics-'+f.cutover.operationId;assert.ok(f.cutover.candidate.ingestionDatabaseName.length>63);assert.equal(validateMaintenanceCutoverPlan(f.cutover,f.plan),f.cutover);assert.throws(()=>validateMaintenanceCutoverPlan({...f.cutover,candidate:{...f.cutover.candidate,ingestionDatabaseName:'a'.repeat(97)}},f.plan));});

test('both natural schedules are mandatory and the original owner stays held between observations',async t=>{const f=await fixture(t);let r=await f.run('apply',{analyticsCapturePath:null});assert.equal(r.code,'MAINTENANCE_ANALYTICS_NATURAL_PROOF_REQUIRED');assert.equal(f.held(),owner);assert.equal(f.events.includes('activate'),false);assert.equal((await f.state()).cutover.oldRestoreForbidden,true);r=await f.run('apply',{lifecycleCapturePath:null});assert.equal(r.code,'MAINTENANCE_LIFECYCLE_NATURAL_PROOF_REQUIRED');assert.equal(f.held(),owner);assert.equal(f.events.includes('main-cron'),true);await f.run('apply');assert.equal(f.held(),null);assert.equal(f.events.filter(x=>x==='analytics-activate').length,1);assert.equal(f.events.filter(x=>x==='activate').length,1);});
test('activation before-effect recovery allows only an exact forward retry and never repeats pristine proof',async t=>{const f=await fixture(t);f.fail('activate');await assert.rejects(f.run('apply'));const proofs=f.events.filter(x=>x==='admit').length;f.verified(false);f.pending(true);await f.run('reconcile');assert.equal((await f.state()).cutover.phase,'uploaded');assert.equal((await f.state()).cutover.oldRestoreForbidden,true);f.fail(null);f.verified(true);await f.run('apply');assert.equal(f.events.filter(x=>x==='activate').length,2);assert.equal(f.events.filter(x=>x==='admit').length,proofs);assert.equal(f.held(),null);});
test('an enabled analytics lost response permanently forbids old-source restoration before app activation',async t=>{const f=await fixture(t);f.fail('analytics-activate');await assert.rejects(f.run('apply'));const s=await f.state();assert.equal(s.cutover.intent,'analytics_activate');assert.equal(s.cutover.oldRestoreForbidden,true);assert.equal(f.events.includes('activate'),false);await f.run('reconcile');f.fail(null);await f.run('apply');assert.equal(f.events.filter(x=>x==='analytics-activate').length,1);assert.equal(f.held(),null);});
test('full proof stage is enforced immediately before application activation',async t=>{const f=await fixture(t);const original=f.options.provider.admit;f.options.provider.admit=async(s,stage)=>{const p=await original(s,stage);return stage==='full'?{...p,stage:'pre-analytics',analyticsCaughtUp:false}:p;};await assert.rejects(f.run('apply'),{code:'PRODUCTION_MAINTENANCE_CUTOVER_ADMISSION_STAGE_INVALID'});assert.equal(f.events.includes('activate'),false);assert.equal(f.held(),owner);});
test('lifecycle proof requires actual scheduled typed maintenance completion, not HTTP/manual or incomplete logs',()=>{const flags=['lifecycleComplete','quarantineRetentionComplete','restoreReplayComplete','quarantineReconciliationComplete','expiredIdentityHandoffPurgeComplete','deletionTombstonePurgeComplete','primaryIdentityReenrollmentCooldownPurgeComplete','identityReenrollmentCooldownPurgeComplete','signInAdmissionPurgeComplete','aggregateRebuildDelegated'];const counts=['expiredIdentityHandoffsPurged','expiredDeletionTombstonesPurged','expiredPrimaryIdentityReenrollmentCooldownsPurged','expiredIdentityReenrollmentCooldownsPurged','expiredSignInAdmissionsPurged','staleDevicePairingsRevoked','staleDeviceCredentialsRevoked','staleDeviceUploadAuthorizationsRevoked','expiredDeviceCredentialRotationsPurged','expiredDevicePairingEventsPurged'];const log={level:'info',event:'scheduled_backend_maintenance',outcome:'success',code:'OK',...Object.fromEntries(flags.map(k=>[k,true])),...Object.fromEntries(counts.map(k=>[k,0])),publicationEnabled:true,aggregateRebuildComplete:false};const event={scriptName:'synthetic-worker',scriptVersion:{id:newVersion},event:{cron:'* * * * *',scheduledTime:1000},outcome:'ok',truncated:false,exceptions:[],logs:[{message:[JSON.stringify(log)]}]};const pins={workerName:'synthetic-worker',versionId:newVersion,notBeforeMs:500,nowMs:2000};assert.equal(proveMaintenanceLifecycleInvocation(Buffer.from(JSON.stringify(event)),pins).qualifiedInvocations,1);for(const change of [{event:{request:{}}},{scriptVersion:{id:old}},{outcome:'exception'},{truncated:true},{logs:[{message:[JSON.stringify({...log,code:'MAINTENANCE_INCOMPLETE'})]}]}])assert.throws(()=>proveMaintenanceLifecycleInvocation(Buffer.from(JSON.stringify({...event,...change})),pins));});

test('a pre-analytics proof crossing the deadline cannot introduce the first target-writing latch',async t=>{const f=await fixture(t);let now=f.cutover.expiresAt-100;let calls=0;const original=f.options.provider.admit;f.options.provider.admit=async(s,stage)=>{const value=await original(s,stage);if(++calls===2)now=f.cutover.expiresAt+1;return value;};await assert.rejects(f.run('apply',{clock:()=>now}),{code:'PRODUCTION_MAINTENANCE_CUTOVER_PLAN_EXPIRED'});assert.equal((await f.state()).cutover.oldRestoreForbidden,false);assert.equal(f.events.includes('analytics-activate'),false);assert.equal(f.held(),owner);});

test('unknown immutable registration is read reconciled without a duplicate INSERT and keeps the forward latch',async t=>{const f=await fixture(t);f.fail('initialize');await assert.rejects(f.run('apply'));assert.equal((await f.state()).cutover.intent,'analytics_initialize');assert.equal((await f.state()).cutover.oldRestoreForbidden,true);assert.equal(f.events.includes('analytics-activate'),false);await f.run('reconcile');f.fail(null);await f.run('apply');assert.equal(f.events.filter(x=>x==='initialize').length,1);assert.equal(f.held(),null);});
