-- PostgreSQL primary migration 0004: telemetry contribution v1.0.
--
-- This is the operational v1 journal. It deliberately uses the same table
-- names as the D1 contract so writer, replay reader, sync, analytics, and
-- owner erasure all observe one dataset. The authority tables referenced here
-- are created by 0002/0003; v1.1/v1.2 transport fences and analytics triggers
-- are additive later migrations.

CREATE TABLE telemetry_v1_chunks (
  id text PRIMARY KEY,
  participant_id text NOT NULL REFERENCES participants(id) ON DELETE CASCADE,
  device_id text NOT NULL REFERENCES device_credentials(id) ON DELETE CASCADE,
  stream text NOT NULL CHECK (stream IN ('usage', 'quota', 'session')),
  chunk_day date NOT NULL,
  chunk_seq integer NOT NULL CHECK (chunk_seq BETWEEN 0 AND 99999),
  revision integer NOT NULL CHECK (revision >= 1),
  chunk_digest text NOT NULL CHECK (chunk_digest ~ '^[0-9a-f]{64}$'),
  envelope_digest text NOT NULL CHECK (envelope_digest ~ '^[0-9a-f]{64}$'),
  parser_version text NOT NULL CHECK (length(parser_version) BETWEEN 1 AND 128),
  record_count integer NOT NULL CHECK (record_count BETWEEN 1 AND 200),
  accepted_record_count integer NOT NULL
    CHECK (accepted_record_count BETWEEN 0 AND record_count),
  r2_key text NOT NULL UNIQUE,
  device_upload_authorization_id text NOT NULL UNIQUE
    REFERENCES device_upload_authorizations(id),
  superseded_at timestamptz,
  quarantine_deleted_at timestamptz,
  created_at timestamptz NOT NULL,
  UNIQUE (participant_id, envelope_digest),
  UNIQUE (participant_id, device_id, stream, chunk_day, chunk_seq, revision)
);

CREATE UNIQUE INDEX telemetry_v1_chunks_current_identity
  ON telemetry_v1_chunks(participant_id, device_id, stream, chunk_day, chunk_seq)
  WHERE superseded_at IS NULL;

CREATE UNIQUE INDEX telemetry_v1_chunks_current_content
  ON telemetry_v1_chunks(participant_id, device_id, stream, chunk_day, chunk_seq, chunk_digest)
  WHERE superseded_at IS NULL;

CREATE INDEX telemetry_v1_chunks_device_day
  ON telemetry_v1_chunks(participant_id, device_id, chunk_day, stream, chunk_seq)
  WHERE superseded_at IS NULL;

CREATE INDEX telemetry_v1_chunks_device
  ON telemetry_v1_chunks(device_id);

CREATE INDEX telemetry_v1_chunks_participant_created
  ON telemetry_v1_chunks(participant_id, created_at, id);

CREATE TABLE telemetry_v1_records (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
    CHECK (id BETWEEN 1 AND 9007199254740991),
  chunk_row_id text NOT NULL REFERENCES telemetry_v1_chunks(id) ON DELETE CASCADE,
  participant_id text NOT NULL REFERENCES participants(id) ON DELETE CASCADE,
  device_id text NOT NULL REFERENCES device_credentials(id) ON DELETE CASCADE,
  stream text NOT NULL CHECK (stream IN ('usage', 'quota', 'session')),
  occurrence_id text NOT NULL CHECK (length(occurrence_id) BETWEEN 1 AND 256),
  observed_at timestamptz NOT NULL,
  observed_day date NOT NULL,
  provider text,
  model_id text,
  session_uuid text,
  plan_type text,
  plan_variant text,
  limit_id text,
  slot text,
  used_percent double precision,
  window_duration_minutes integer,
  resets_at timestamptz,
  input_uncached_tokens bigint,
  input_cache_read_tokens bigint,
  input_cache_write_tokens bigint,
  output_text_tokens bigint,
  output_reasoning_tokens bigint,
  output_combined_tokens bigint,
  record_json jsonb NOT NULL,
  UNIQUE (participant_id, device_id, stream, occurrence_id)
);

CREATE INDEX telemetry_v1_records_chunk
  ON telemetry_v1_records(chunk_row_id);

CREATE INDEX telemetry_v1_records_aggregate_day
  ON telemetry_v1_records(observed_day, stream, provider, model_id);

CREATE INDEX telemetry_v1_records_participant
  ON telemetry_v1_records(participant_id, observed_day, id);

CREATE TABLE telemetry_v1_device_consents (
  participant_id text NOT NULL REFERENCES participants(id) ON DELETE CASCADE,
  device_id text NOT NULL REFERENCES device_credentials(id) ON DELETE CASCADE,
  telemetry_schema_version text NOT NULL
    CHECK (telemetry_schema_version = 'telemetry-contribution-v1.0'),
  field_dictionary_version text NOT NULL
    CHECK (field_dictionary_version = 'telemetry-v1.0-registry-2026-08-07.1'),
  privacy_contract_version text NOT NULL
    CHECK (privacy_contract_version = 'ongoing-privacy-safe-telemetry-v1.0'),
  consented_at timestamptz NOT NULL,
  PRIMARY KEY (participant_id, device_id)
);

CREATE INDEX telemetry_v1_device_consents_device
  ON telemetry_v1_device_consents(device_id);

CREATE TABLE telemetry_v1_chunk_admission_windows (
  participant_id text NOT NULL REFERENCES participants(id) ON DELETE CASCADE,
  device_id text NOT NULL REFERENCES device_credentials(id) ON DELETE CASCADE,
  window_day date NOT NULL,
  accepted_count integer NOT NULL CHECK (accepted_count BETWEEN 1 AND 20000),
  last_accepted_at timestamptz NOT NULL,
  PRIMARY KEY (participant_id, device_id, window_day)
);

CREATE INDEX telemetry_v1_chunk_admission_windows_device
  ON telemetry_v1_chunk_admission_windows(device_id, window_day);

-- Object cleanup state is primary ingest state. It is intentionally separate
-- from the ledger schema: no cross-database transaction is implied.
CREATE TABLE pending_objects (
  contribution_id text PRIMARY KEY,
  object_key text NOT NULL UNIQUE
);

CREATE OR REPLACE FUNCTION insert_telemetry_v1_contribution(input jsonb)
RETURNS TABLE(accepted_records integer)
LANGUAGE plpgsql
AS $$
DECLARE
  participant_row participants%ROWTYPE;
  device_row device_credentials%ROWTYPE;
  authorization_row device_upload_authorizations%ROWTYPE;
  current_chunk telemetry_v1_chunks%ROWTYPE;
  chunk_value jsonb := input->'chunk';
  records_value jsonb := chunk_value->'records';
  participant_value text := input->>'participantId';
  device_value text := input->>'deviceId';
  contribution_value text := input->>'chunkId';
  authorization_value text := input->>'uploadAuthorizationId';
  lease_value timestamptz := (input->>'uploadAuthorizationLeaseExpiresAt')::timestamptz;
  predecessor_value text := input->'supersedes'->>'id';
  stream_value text := chunk_value->>'stream';
  day_value date := (chunk_value->>'chunkDay')::date;
  sequence_value integer := (chunk_value->>'chunkSeq')::integer;
  revision_value integer := (chunk_value->>'chunkRevision')::integer;
  created_value timestamptz := (input->>'createdAt')::timestamptz;
  record_count_value integer := jsonb_array_length(records_value);
  accepted_value integer;
  maximum_value integer;
  changed_value integer;
BEGIN
  IF record_count_value IS NULL OR record_count_value NOT BETWEEN 1 AND 200 THEN
    RAISE EXCEPTION USING ERRCODE = 'P1005';
  END IF;

  -- The participant lock serializes first admission, correction, and all
  -- concurrent writers for one owner. This makes the daily counter and current
  -- identity check one bounded decision.
  SELECT * INTO participant_row
    FROM participants WHERE id = participant_value FOR UPDATE;
  IF NOT FOUND OR participant_row.state <> 'active' THEN
    RAISE EXCEPTION USING ERRCODE = 'P1001';
  END IF;
  IF participant_row.owner_kind <> 'social' THEN
    RAISE EXCEPTION USING ERRCODE = 'P1007';
  END IF;

  SELECT * INTO device_row
   FROM device_credentials
   WHERE id = device_value AND participant_id = participant_value
     AND authority_kind = 'social'
   FOR UPDATE;
  IF NOT FOUND OR device_row.state <> 'active'
      OR device_row.expires_at <= clock_timestamp() THEN
    RAISE EXCEPTION USING ERRCODE = 'P1002';
  END IF;

  PERFORM 1 FROM telemetry_v1_device_consents
   WHERE participant_id = participant_value
     AND device_id = device_value
     AND telemetry_schema_version = 'telemetry-contribution-v1.0'
     AND field_dictionary_version = 'telemetry-v1.0-registry-2026-08-07.1'
     AND privacy_contract_version = 'ongoing-privacy-safe-telemetry-v1.0'
     AND telemetry_schema_version = chunk_value->'consent'->>'telemetrySchemaVersion'
     AND field_dictionary_version = chunk_value->'consent'->>'fieldDictionaryVersion'
     AND privacy_contract_version = chunk_value->'consent'->>'privacyContractVersion'
   FOR SHARE;
  IF NOT FOUND THEN
    RAISE EXCEPTION USING ERRCODE = 'P1006';
  END IF;

  SELECT * INTO authorization_row
   FROM device_upload_authorizations
   WHERE id = authorization_value
     AND participant_id = participant_value
     AND issued_by_device_id = device_value
   FOR UPDATE;
  IF NOT FOUND OR authorization_row.state <> 'consuming'
      OR authorization_row.envelope_digest <> input->>'envelopeDigest'
      OR authorization_row.consume_lease_expires_at IS DISTINCT FROM lease_value
      OR authorization_row.consume_lease_expires_at IS NULL
      OR authorization_row.consume_lease_expires_at <= clock_timestamp()
      OR authorization_row.expires_at <= clock_timestamp() THEN
    RAISE EXCEPTION USING ERRCODE = 'P1002';
  END IF;

  SELECT * INTO current_chunk
    FROM telemetry_v1_chunks
   WHERE participant_id = participant_value
     AND device_id = device_value
     AND stream = stream_value
     AND chunk_day = day_value
     AND chunk_seq = sequence_value
     AND superseded_at IS NULL
   FOR UPDATE;
  IF predecessor_value IS NULL THEN
    IF current_chunk.id IS NOT NULL OR revision_value <> 1 OR EXISTS (
      SELECT 1 FROM telemetry_v1_chunks
       WHERE participant_id = participant_value AND device_id = device_value
         AND stream = stream_value AND chunk_day = day_value
         AND chunk_seq = sequence_value
    ) THEN
      RAISE EXCEPTION USING ERRCODE = 'P1005';
    END IF;
  ELSE
    IF current_chunk.id IS DISTINCT FROM predecessor_value
        OR revision_value IS DISTINCT FROM current_chunk.revision + 1 THEN
      RAISE EXCEPTION USING ERRCODE = 'P1005';
    END IF;
  END IF;

  SELECT accepted_count INTO accepted_value
    FROM telemetry_v1_chunk_admission_windows
   WHERE participant_id = participant_value
     AND device_id = device_value
     AND window_day = (created_value AT TIME ZONE 'UTC')::date
   FOR UPDATE;
  maximum_value := CASE
    WHEN device_row.issued_at > created_value - interval '7 days' THEN 20000
    ELSE 2000
  END;
  IF COALESCE(accepted_value, 0) >= maximum_value THEN
    RAISE EXCEPTION USING ERRCODE = 'P1003';
  END IF;

  -- Register the object in the same primary transaction as admission. A
  -- caller that already registered the same contribution is idempotent; a
  -- different contribution may never claim the same object key.
  BEGIN
    INSERT INTO pending_objects (contribution_id, object_key)
      VALUES (contribution_value, input->>'objectKey')
      ON CONFLICT (contribution_id) DO NOTHING;
  EXCEPTION WHEN unique_violation THEN
    RAISE EXCEPTION USING ERRCODE = 'P1005';
  END;

  IF predecessor_value IS NOT NULL THEN
    UPDATE telemetry_v1_chunks SET superseded_at = created_value
     WHERE id = predecessor_value
       AND participant_id = participant_value
       AND superseded_at IS NULL;
    GET DIAGNOSTICS changed_value = ROW_COUNT;
    IF changed_value <> 1 THEN RAISE EXCEPTION USING ERRCODE = 'P1005'; END IF;
    DELETE FROM telemetry_v1_records WHERE chunk_row_id = predecessor_value;
  END IF;

  BEGIN
    INSERT INTO telemetry_v1_chunks (
      id, participant_id, device_id, stream, chunk_day, chunk_seq, revision,
      chunk_digest, envelope_digest, parser_version, record_count,
      accepted_record_count, r2_key, device_upload_authorization_id, created_at
    ) VALUES (
      contribution_value, participant_value, device_value, stream_value,
      day_value, sequence_value, revision_value, chunk_value->>'chunkDigest',
      input->>'envelopeDigest', chunk_value->>'parserVersion',
      record_count_value, record_count_value, input->>'objectKey',
      authorization_value, created_value
    );
  EXCEPTION WHEN unique_violation THEN
    RAISE EXCEPTION USING ERRCODE = 'P1005';
  END;

  BEGIN
    INSERT INTO telemetry_v1_records (
      chunk_row_id, participant_id, device_id, stream, occurrence_id,
      observed_at, observed_day, provider, model_id, session_uuid,
      plan_type, plan_variant, limit_id, slot, used_percent,
      window_duration_minutes, resets_at, input_uncached_tokens,
      input_cache_read_tokens, input_cache_write_tokens, output_text_tokens,
      output_reasoning_tokens, output_combined_tokens, record_json
    )
    SELECT contribution_value, participant_value, device_value, stream_value,
      CASE stream_value
        WHEN 'usage' THEN record_value->>'eventId'
        WHEN 'quota' THEN record_value->>'observationId'
        ELSE record_value->>'sessionUuid'
      END,
      (CASE stream_value
        WHEN 'usage' THEN record_value->>'eventTime'
        WHEN 'quota' THEN record_value->>'observedTime'
        ELSE record_value->>'firstEventTime'
      END)::timestamptz,
      ((CASE stream_value
        WHEN 'usage' THEN record_value->>'eventTime'
        WHEN 'quota' THEN record_value->>'observedTime'
        ELSE record_value->>'firstEventTime'
      END)::timestamptz AT TIME ZONE 'UTC')::date,
      COALESCE(record_value->>'provider', NULL),
      CASE WHEN stream_value = 'usage' THEN record_value->>'modelId' END,
      CASE WHEN stream_value = 'usage' THEN record_value->>'sessionUuid'
        WHEN stream_value = 'session' THEN record_value->>'sessionUuid' END,
      CASE WHEN stream_value = 'quota' THEN record_value->>'planType' END,
      CASE WHEN stream_value = 'quota' THEN record_value->>'planVariant' END,
      CASE WHEN stream_value = 'quota' THEN record_value->>'limitId' END,
      CASE WHEN stream_value = 'quota' THEN record_value->>'slot' END,
      CASE WHEN stream_value = 'quota' THEN (record_value->>'usedPercent')::double precision END,
      CASE WHEN stream_value = 'quota' THEN (record_value->>'windowDurationMinutes')::integer END,
      CASE WHEN stream_value = 'quota' THEN (record_value->>'resetsAt')::timestamptz END,
      CASE WHEN stream_value = 'usage' THEN (record_value->'components'->>'inputUncachedTokens')::bigint END,
      CASE WHEN stream_value = 'usage' THEN (record_value->'components'->>'inputCacheReadTokens')::bigint END,
      CASE WHEN stream_value = 'usage' THEN (record_value->'components'->>'inputCacheWriteTokens')::bigint END,
      CASE WHEN stream_value = 'usage' THEN (record_value->'components'->>'outputTextTokens')::bigint END,
      CASE WHEN stream_value = 'usage' THEN (record_value->'components'->>'outputReasoningTokens')::bigint END,
      CASE WHEN stream_value = 'usage' THEN (record_value->'components'->>'outputCombinedTokens')::bigint END,
      record_value
    FROM jsonb_array_elements(records_value) AS record_value;
  EXCEPTION WHEN unique_violation THEN
    RAISE EXCEPTION USING ERRCODE = 'P1004';
  END;

  UPDATE device_upload_authorizations
     SET state = 'consumed', consumed_at = created_value,
         consume_lease_expires_at = NULL,
         consumed_contribution_id = contribution_value
   WHERE id = authorization_value AND participant_id = participant_value
     AND issued_by_device_id = device_value AND state = 'consuming';
  IF NOT FOUND THEN RAISE EXCEPTION USING ERRCODE = 'P1002'; END IF;

  INSERT INTO telemetry_v1_chunk_admission_windows (
    participant_id, device_id, window_day, accepted_count, last_accepted_at
  ) VALUES (
    participant_value, device_value, (created_value AT TIME ZONE 'UTC')::date,
    1, created_value
  ) ON CONFLICT (participant_id, device_id, window_day)
    DO UPDATE SET accepted_count = telemetry_v1_chunk_admission_windows.accepted_count + 1,
      last_accepted_at = EXCLUDED.last_accepted_at;

  RETURN QUERY SELECT record_count_value;
END;
$$;

REVOKE ALL ON FUNCTION insert_telemetry_v1_contribution(jsonb) FROM PUBLIC;
