-- PostgreSQL primary migration 0011: retained contribution source.
--
-- The retained source is the compatibility dataset used by legacy transport
-- policy, owner erasure, and the account dashboard.  It intentionally keeps
-- the D1 table names and identity keys: a PostgreSQL authority read must see
-- the same accepted v0.2 history as a D1 read.  v1/v1.1/v1.2 journals remain
-- in their format-specific tables; this table is not a substitute for those
-- journals and does not activate any staged format.

CREATE TABLE telemetry_contributions (
  id text PRIMARY KEY,
  participant_id text NOT NULL REFERENCES participants(id) ON DELETE CASCADE,
  plaintext_digest text NOT NULL CHECK (plaintext_digest ~ '^[0-9a-f]{64}$'),
  envelope_digest text NOT NULL CHECK (envelope_digest ~ '^[0-9a-f]{64}$'),
  r2_key text NOT NULL UNIQUE,
  status text NOT NULL DEFAULT 'accepted' CHECK (status IN ('accepted', 'deleting')),
  schema_version text NOT NULL CHECK (schema_version = 'telemetry-contribution-v0.1'),
  transport_schema_version text NOT NULL DEFAULT 'telemetry-contribution-v0.1'
    CHECK (transport_schema_version IN (
      'telemetry-contribution-v0.1', 'telemetry-contribution-v0.2',
      'telemetry-contribution-v1.0', 'telemetry-contribution-v1.1',
      'telemetry-contribution-v1.2'
    )),
  dataset_id text,
  dataset_part_index integer CHECK (dataset_part_index IS NULL OR dataset_part_index BETWEEN 1 AND 100),
  dataset_part_count integer CHECK (dataset_part_count IS NULL OR dataset_part_count BETWEEN 1 AND 100),
  dataset_completeness text CHECK (dataset_completeness IS NULL OR dataset_completeness IN ('complete', 'partial')),
  dataset_range_start timestamptz,
  dataset_range_end timestamptz,
  range_start timestamptz NOT NULL,
  range_end timestamptz NOT NULL,
  client_platform text NOT NULL,
  provider_policy_epoch text NOT NULL,
  estimated_api_cost_usd numeric,
  priced_event_coverage_percent double precision NOT NULL,
  unknown_model_event_count integer NOT NULL CHECK (unknown_model_event_count >= 0),
  unknown_billable_units integer NOT NULL CHECK (unknown_billable_units >= 0),
  price_basis text NOT NULL,
  declared_record_count integer NOT NULL CHECK (declared_record_count >= 0),
  accepted_record_count integer CHECK (accepted_record_count IS NULL OR accepted_record_count >= 0),
  upload_authorization_id text REFERENCES upload_authorizations(id),
  device_upload_authorization_id text REFERENCES device_upload_authorizations(id),
  created_at timestamptz NOT NULL,
  quarantine_deleted_at timestamptz,
  server_cost_nanousd bigint NOT NULL DEFAULT 0 CHECK (server_cost_nanousd >= 0),
  server_priced_event_count integer NOT NULL DEFAULT 0 CHECK (server_priced_event_count >= 0),
  server_partially_priced_event_count integer NOT NULL DEFAULT 0 CHECK (server_partially_priced_event_count >= 0),
  server_unpriced_event_count integer NOT NULL DEFAULT 0 CHECK (server_unpriced_event_count >= 0),
  server_pricing_method_version text,
  server_price_registry_version text,
  server_price_registry_sha256 text,
  server_price_basis text,
  server_price_epoch_basis text,
  server_price_event_time_start timestamptz,
  server_price_event_time_end timestamptz,
  UNIQUE (participant_id, plaintext_digest),
  UNIQUE (participant_id, envelope_digest),
  UNIQUE (upload_authorization_id),
  UNIQUE (device_upload_authorization_id)
);

CREATE INDEX telemetry_contributions_participant_created
  ON telemetry_contributions(participant_id, created_at, id);
CREATE INDEX telemetry_contributions_transport
  ON telemetry_contributions(participant_id, transport_schema_version, status, created_at);
CREATE INDEX telemetry_contributions_quarantine
  ON telemetry_contributions(created_at, id)
  WHERE quarantine_deleted_at IS NULL;

CREATE TABLE telemetry_records (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  origin_contribution_id text REFERENCES telemetry_contributions(id) ON DELETE SET NULL,
  participant_id text NOT NULL REFERENCES participants(id) ON DELETE CASCADE,
  record_kind text NOT NULL CHECK (record_kind IN ('usage', 'quota', 'activity')),
  occurrence_id text NOT NULL,
  observed_at timestamptz NOT NULL,
  provider text,
  model_id text,
  model_fingerprint text,
  speed_mode text,
  api_service_tier text,
  surface text,
  billing_surface text,
  plan_type text,
  plan_variant text,
  limit_id text,
  slot text,
  used_percent double precision,
  window_duration_minutes integer,
  resets_at timestamptz,
  total_input_context_tokens bigint,
  reasoning_effort text,
  agent_scope text,
  input_uncached_tokens bigint,
  input_cache_read_tokens bigint,
  input_cache_write_tokens bigint,
  output_text_tokens bigint,
  output_reasoning_tokens bigint,
  output_combined_tokens bigint,
  tool_units bigint,
  estimated_api_cost_usd numeric,
  pricing_coverage_percent double precision,
  unknown_billable_units integer,
  server_cost_usd numeric,
  server_cost_nanousd bigint,
  server_pricing_coverage_percent double precision,
  server_unknown_billable_units integer,
  server_pricing_status text,
  server_pricing_method_version text,
  server_price_registry_version text,
  server_price_registry_sha256 text,
  server_price_card_ids jsonb,
  server_unpriced_reason_codes jsonb,
  server_price_epoch_basis text,
  server_tier_basis text,
  server_api_service_tier text,
  server_price_basis text,
  server_price_event_time timestamptz,
  dataset_id text,
  account_track_id text NOT NULL DEFAULT 'unattributed',
  policy_epoch text,
  record_json jsonb NOT NULL,
  UNIQUE (participant_id, record_kind, occurrence_id)
);

CREATE INDEX telemetry_records_participant_time
  ON telemetry_records(participant_id, observed_at, id);
CREATE INDEX telemetry_records_origin_contribution
  ON telemetry_records(origin_contribution_id);
CREATE INDEX telemetry_records_usage_account_time
  ON telemetry_records(participant_id, account_track_id, provider, dataset_id, observed_at, id)
  WHERE record_kind = 'usage';

CREATE TABLE telemetry_contribution_occurrences (
  contribution_id text NOT NULL REFERENCES telemetry_contributions(id) ON DELETE CASCADE,
  participant_id text NOT NULL,
  record_kind text NOT NULL,
  occurrence_id text NOT NULL,
  dataset_id text,
  account_track_id text NOT NULL DEFAULT 'unattributed',
  policy_epoch text,
  PRIMARY KEY (contribution_id, record_kind, occurrence_id),
  FOREIGN KEY (participant_id, record_kind, occurrence_id)
    REFERENCES telemetry_records(participant_id, record_kind, occurrence_id)
    ON DELETE CASCADE
);

CREATE INDEX telemetry_contribution_occurrences_record
  ON telemetry_contribution_occurrences(participant_id, record_kind, occurrence_id);

CREATE UNIQUE INDEX telemetry_contributions_upload_authorization
  ON telemetry_contributions(upload_authorization_id)
  WHERE upload_authorization_id IS NOT NULL;
CREATE UNIQUE INDEX telemetry_contributions_device_upload_authorization
  ON telemetry_contributions(device_upload_authorization_id)
  WHERE device_upload_authorization_id IS NOT NULL;

CREATE OR REPLACE FUNCTION telemetry_contributions_require_active_participant()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM participants
     WHERE id = NEW.participant_id AND state = 'active'
  ) THEN
    RAISE EXCEPTION 'participant unavailable' USING ERRCODE = 'P1001';
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER telemetry_contributions_active_participant
BEFORE INSERT ON telemetry_contributions
FOR EACH ROW EXECUTE FUNCTION telemetry_contributions_require_active_participant();

CREATE OR REPLACE FUNCTION telemetry_contributions_enforce_participant_limit()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE contribution_count integer;
BEGIN
  SELECT count(*) INTO contribution_count
    FROM telemetry_contributions
   WHERE participant_id = NEW.participant_id;
  IF contribution_count >= 100 THEN
    RAISE EXCEPTION 'contribution limit reached' USING ERRCODE = 'P1003';
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER telemetry_contributions_participant_limit
BEFORE INSERT ON telemetry_contributions
FOR EACH ROW EXECUTE FUNCTION telemetry_contributions_enforce_participant_limit();

-- v1.2 is a staged source, but once an operator advances its runtime it must
-- participate in the same source revision fence as the older analytical
-- lanes.  Keep this hook in the post-0010 fragment because input_versions and
-- its queue triggers are introduced there; the v1.2 transport fragment itself
-- intentionally remains independent of analytical lifecycle ownership.
CREATE OR REPLACE FUNCTION telemetry_v12_source_revision()
RETURNS trigger
LANGUAGE plpgsql SET search_path FROM CURRENT AS $$
BEGIN
  INSERT INTO input_versions(participant_id, revision)
    VALUES (NEW.participant_id, 1)
    ON CONFLICT (participant_id) DO UPDATE SET revision = input_versions.revision + 1;
  RETURN NULL;
END;
$$;

CREATE TRIGGER telemetry_v12_source_revision_insert
AFTER INSERT ON telemetry_v12_chunks
FOR EACH ROW EXECUTE FUNCTION telemetry_v12_source_revision();

CREATE OR REPLACE FUNCTION telemetry_v12_domain_revision()
RETURNS trigger
LANGUAGE plpgsql SET search_path FROM CURRENT AS $$
BEGIN
  UPDATE input_versions SET revision = revision + 1
   WHERE participant_id = NEW.participant_id;
  RETURN NULL;
END;
$$;

CREATE TRIGGER telemetry_v12_domain_revision_publish
AFTER INSERT OR UPDATE ON telemetry_v12_domain_heads
FOR EACH ROW EXECUTE FUNCTION telemetry_v12_domain_revision();
