-- Additive typed v1.2 ingestion storage. The older PostgreSQL 0006 contract
-- retains record_json for source compatibility; new admission writes only to
-- these normalized tables. No v1.2 record JSON is stored here.

CREATE TABLE typed_telemetry_dictionary (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  value text NOT NULL UNIQUE CHECK (length(value) BETWEEN 1 AND 64)
);

CREATE TABLE telemetry_v12_typed_runtime (
  id integer PRIMARY KEY CHECK (id = 1),
  schema_version text NOT NULL CHECK (schema_version = 'telemetry-contribution-v1.2'),
  envelope_schema_version text NOT NULL CHECK (envelope_schema_version = 'telemetry-envelope-v1.2'),
  field_dictionary_version text NOT NULL CHECK (field_dictionary_version = 'telemetry-v1.2-registry-2026-09-20.1'),
  privacy_contract_version text NOT NULL CHECK (privacy_contract_version = 'ongoing-privacy-safe-telemetry-v1.2'),
  state text NOT NULL CHECK (state IN ('staged', 'active')),
  policy_revision integer NOT NULL CHECK (policy_revision >= 1),
  max_day_chunks integer NOT NULL CHECK (max_day_chunks BETWEEN 1 AND 4096),
  max_chunk_records integer NOT NULL CHECK (max_chunk_records BETWEEN 1 AND 200),
  max_day_bytes integer NOT NULL CHECK (max_day_bytes BETWEEN 1 AND 64000000),
  changed_at timestamptz NOT NULL
);
INSERT INTO telemetry_v12_typed_runtime (
  id, schema_version, envelope_schema_version, field_dictionary_version,
  privacy_contract_version, state, policy_revision, max_day_chunks,
  max_chunk_records, max_day_bytes, changed_at
) VALUES (
  1, 'telemetry-contribution-v1.2', 'telemetry-envelope-v1.2',
  'telemetry-v1.2-registry-2026-09-20.1',
  'ongoing-privacy-safe-telemetry-v1.2', 'staged', 1, 4096, 200, 64000000,
  TIMESTAMPTZ '1970-01-01 00:00:00+00'
);

-- The original PostgreSQL v1.2 accountless grant table predates the exact
-- successor authorization metadata. These constants make the authority proof
-- explicit and keep it distinct from the v1.1 grant.
ALTER TABLE accountless_v12_device_authorizations
  ADD COLUMN schema_version text NOT NULL DEFAULT 'accountless-upload-owner-v1.2'
    CHECK (schema_version = 'accountless-upload-owner-v1.2'),
  ADD COLUMN policy_version text NOT NULL DEFAULT 'accountless-telemetry-v1.2-policy-v1'
    CHECK (policy_version = 'accountless-telemetry-v1.2-policy-v1'),
  ADD COLUMN authorization_basis text NOT NULL DEFAULT 'accountless-policy-v1.2'
    CHECK (authorization_basis = 'accountless-policy-v1.2');

-- Single write-authority predicate for the typed source lane. The accountless
-- branch proves the active enrollment lease and owner row as well as its exact
-- v1.2 authorization. Runtime starts staged, so this view grants nothing until
-- an explicit owner-operated activation changes both runtime states.
CREATE VIEW telemetry_v12_typed_active_authorizations AS
SELECT c.participant_id, c.device_id, 'social'::text AS authority_kind
  FROM telemetry_v12_device_capabilities c
  JOIN telemetry_v12_runtime r ON r.id = 1 AND r.state = 'active'
  JOIN telemetry_v12_typed_runtime typed_runtime
    ON typed_runtime.id = 1 AND typed_runtime.state = 'active'
  JOIN participants p ON p.id = c.participant_id
  JOIN device_credentials d ON d.id = c.device_id AND d.participant_id = p.id
 WHERE c.state = 'accepted'
   AND c.telemetry_schema_version = typed_runtime.schema_version
   AND c.field_dictionary_version = typed_runtime.field_dictionary_version
   AND c.privacy_contract_version = typed_runtime.privacy_contract_version
   AND p.state = 'active' AND p.owner_kind = 'social'
   AND d.state = 'active' AND d.authority_kind = 'social'
UNION ALL
SELECT a.participant_id, a.device_credential_id AS device_id, 'accountless'::text AS authority_kind
  FROM accountless_v12_device_authorizations a
  JOIN telemetry_v12_runtime r ON r.id = 1 AND r.state = 'active'
  JOIN telemetry_v12_typed_runtime typed_runtime
    ON typed_runtime.id = 1 AND typed_runtime.state = 'active'
  JOIN participants p ON p.id = a.participant_id
  JOIN device_credentials d ON d.id = a.device_credential_id AND d.participant_id = p.id
  JOIN accountless_enrollment_ledger ledger ON ledger.device_id = a.enrollment_device_id
  JOIN accountless_upload_owners owner ON owner.enrollment_device_id = a.enrollment_device_id
 WHERE a.state = 'active' AND a.expires_at > now()
   AND a.schema_version = 'accountless-upload-owner-v1.2'
   AND a.policy_version = 'accountless-telemetry-v1.2-policy-v1'
   AND a.authorization_basis = 'accountless-policy-v1.2'
   AND a.telemetry_schema_version = typed_runtime.schema_version
   AND a.field_dictionary_version = typed_runtime.field_dictionary_version
   AND a.privacy_contract_version = typed_runtime.privacy_contract_version
   AND p.state = 'active' AND p.owner_kind = 'accountless'
   AND d.state = 'active' AND d.authority_kind = 'accountless'
   AND d.accountless_enrollment_device_id = a.enrollment_device_id
   AND d.expires_at = a.expires_at
   AND ledger.state = 'active' AND ledger.expires_at = a.expires_at AND ledger.expires_at > now()
   AND owner.participant_id = a.participant_id
   AND owner.device_credential_id = a.device_credential_id
   AND owner.state = 'active' AND owner.expires_at = a.expires_at;

-- Read authority also includes retained accepted/revoked grants while their
-- storage owner link is active. This preserves owner-scoped retention semantics
-- without letting a retired or erased owner re-enter the effective source.
CREATE VIEW telemetry_v12_typed_retained_authorizations AS
SELECT active_auth.participant_id, active_auth.device_id
  FROM telemetry_v12_typed_active_authorizations active_auth
  JOIN storage_v11_owner_links owner_link
    ON owner_link.participant_id = active_auth.participant_id AND owner_link.state = 'active'
UNION
SELECT capability.participant_id, capability.device_id
  FROM telemetry_v12_device_capabilities capability
  JOIN participants participant ON participant.id = capability.participant_id AND participant.state = 'active'
  JOIN storage_v11_owner_links owner_link
    ON owner_link.participant_id = capability.participant_id AND owner_link.state = 'active'
 WHERE capability.state IN ('accepted', 'revoked')
   AND capability.telemetry_schema_version = 'telemetry-contribution-v1.2'
UNION
SELECT retained_auth.participant_id, retained_auth.device_credential_id AS device_id
  FROM accountless_v12_device_authorizations retained_auth
  JOIN participants participant ON participant.id = retained_auth.participant_id AND participant.state = 'active'
  JOIN storage_v11_owner_links owner_link
    ON owner_link.participant_id = retained_auth.participant_id AND owner_link.state = 'active'
 WHERE (retained_auth.state = 'active' AND retained_auth.expires_at <= now())
    OR (retained_auth.state = 'revoked' AND retained_auth.revocation_reason = 'user_opt_out');

CREATE TABLE telemetry_v12_typed_attributions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_basis smallint NOT NULL CHECK (account_basis BETWEEN 0 AND 2),
  account_track bytea NOT NULL,
  plan_basis smallint NOT NULL CHECK (plan_basis BETWEEN 0 AND 3),
  plan_type_id bigint NOT NULL REFERENCES typed_telemetry_dictionary(id),
  plan_era bytea NOT NULL,
  CHECK ((account_basis = 0 AND octet_length(account_track) = 0)
    OR (account_basis != 0 AND octet_length(account_track) BETWEEN 2 AND 257)),
  CHECK (octet_length(plan_era) = 0 OR octet_length(plan_era) BETWEEN 2 AND 257),
  CHECK (plan_basis IN (1, 2) OR octet_length(plan_era) = 0),
  UNIQUE (account_basis, account_track, plan_basis, plan_type_id, plan_era)
);

CREATE TABLE telemetry_v12_typed_records (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  chunk_id text NOT NULL REFERENCES telemetry_v12_chunks(id) ON DELETE CASCADE,
  manifest_id text NOT NULL REFERENCES telemetry_v12_day_manifests(id) ON DELETE CASCADE,
  stream text NOT NULL CHECK (stream IN ('quota', 'session', 'usage')),
  record_index integer NOT NULL CHECK (record_index BETWEEN 0 AND 199),
  occurrence_id bytea NOT NULL CHECK (octet_length(occurrence_id) BETWEEN 2 AND 257),
  observed_at_ms bigint NOT NULL CHECK (observed_at_ms BETWEEN -8640000000000000 AND 8640000000000000),
  observed_day integer NOT NULL CHECK (observed_day BETWEEN -100000 AND 100000),
  provider_id bigint NOT NULL REFERENCES typed_telemetry_dictionary(id),
  canonical_digest bytea NOT NULL CHECK (octet_length(canonical_digest) = 32),
  UNIQUE (chunk_id, record_index),
  UNIQUE (chunk_id, occurrence_id),
  UNIQUE (manifest_id, stream, occurrence_id)
);
CREATE INDEX telemetry_v12_typed_records_order
  ON telemetry_v12_typed_records(manifest_id, stream, observed_at_ms, occurrence_id);
CREATE INDEX telemetry_v12_typed_records_day
  ON telemetry_v12_typed_records(observed_day, stream, observed_at_ms, occurrence_id);

CREATE TABLE telemetry_v12_typed_usage (
  record_id bigint PRIMARY KEY REFERENCES telemetry_v12_typed_records(id) ON DELETE CASCADE,
  session_id bytea NOT NULL CHECK (octet_length(session_id) BETWEEN 2 AND 257),
  model_id bigint NOT NULL REFERENCES typed_telemetry_dictionary(id),
  speed_mode_id bigint NOT NULL REFERENCES typed_telemetry_dictionary(id),
  api_service_tier_id bigint NOT NULL REFERENCES typed_telemetry_dictionary(id),
  surface_id bigint NOT NULL REFERENCES typed_telemetry_dictionary(id),
  billing_surface_id bigint NOT NULL REFERENCES typed_telemetry_dictionary(id),
  reasoning_effort_id bigint NOT NULL REFERENCES typed_telemetry_dictionary(id),
  agent_scope_id bigint NOT NULL REFERENCES typed_telemetry_dictionary(id),
  outcome_id bigint NOT NULL REFERENCES typed_telemetry_dictionary(id),
  attribution_id bigint NOT NULL REFERENCES telemetry_v12_typed_attributions(id),
  total_input_context_tokens bigint CHECK (total_input_context_tokens BETWEEN 0 AND 1000000000000),
  input_uncached_tokens bigint CHECK (input_uncached_tokens BETWEEN 0 AND 1000000000000),
  input_cache_read_tokens bigint CHECK (input_cache_read_tokens BETWEEN 0 AND 1000000000000),
  input_cache_write_tokens bigint CHECK (input_cache_write_tokens BETWEEN 0 AND 1000000000000),
  output_text_tokens bigint CHECK (output_text_tokens BETWEEN 0 AND 1000000000000),
  output_reasoning_tokens bigint CHECK (output_reasoning_tokens BETWEEN 0 AND 1000000000000),
  output_combined_tokens bigint CHECK (output_combined_tokens BETWEEN 0 AND 1000000000000),
  boundary_flags integer CHECK (boundary_flags BETWEEN 0 AND 3),
  tie_order integer CHECK (tie_order BETWEEN 0 AND 819199),
  cache_write_ttl_five_minute_tokens bigint CHECK (cache_write_ttl_five_minute_tokens BETWEEN 0 AND 1000000000000),
  cache_write_ttl_one_hour_tokens bigint CHECK (cache_write_ttl_one_hour_tokens BETWEEN 0 AND 1000000000000),
  CHECK ((cache_write_ttl_five_minute_tokens IS NULL) = (cache_write_ttl_one_hour_tokens IS NULL)),
  CHECK (cache_write_ttl_five_minute_tokens IS NULL OR input_cache_write_tokens IS NOT NULL),
  CHECK (cache_write_ttl_five_minute_tokens IS NULL
    OR cache_write_ttl_five_minute_tokens + cache_write_ttl_one_hour_tokens = input_cache_write_tokens)
);

CREATE TABLE telemetry_v12_typed_quota (
  record_id bigint PRIMARY KEY REFERENCES telemetry_v12_typed_records(id) ON DELETE CASCADE,
  plan_type_id bigint NOT NULL REFERENCES typed_telemetry_dictionary(id),
  plan_variant_id bigint NOT NULL REFERENCES typed_telemetry_dictionary(id),
  limit_id bigint NOT NULL REFERENCES typed_telemetry_dictionary(id),
  slot_id bigint NOT NULL REFERENCES typed_telemetry_dictionary(id),
  used_percent double precision CHECK (used_percent BETWEEN 0 AND 100),
  window_duration_minutes integer CHECK (window_duration_minutes BETWEEN 1 AND 527040),
  resets_at_ms bigint CHECK (resets_at_ms BETWEEN -8640000000000000 AND 8640000000000000),
  attribution_id bigint NOT NULL REFERENCES telemetry_v12_typed_attributions(id)
);

CREATE TABLE telemetry_v12_typed_session_tools (
  record_id bigint NOT NULL REFERENCES telemetry_v12_typed_records(id) ON DELETE CASCADE,
  tool_class_id bigint NOT NULL REFERENCES typed_telemetry_dictionary(id),
  count bigint NOT NULL CHECK (count BETWEEN 0 AND 1000000000),
  PRIMARY KEY (record_id, tool_class_id)
);

CREATE FUNCTION telemetry_v12_typed_record_admission() RETURNS trigger
LANGUAGE plpgsql SET search_path FROM CURRENT AS $$
BEGIN
  PERFORM pg_advisory_xact_lock(hashtextextended(NEW.chunk_id, 12012));
  IF NOT EXISTS (
    SELECT 1 FROM telemetry_v12_chunks chunk
      JOIN telemetry_v12_day_manifests manifest ON manifest.id = chunk.manifest_id
      JOIN telemetry_v12_typed_active_authorizations active_auth
        ON active_auth.participant_id = chunk.participant_id AND active_auth.device_id = chunk.device_id
     WHERE chunk.id = NEW.chunk_id AND chunk.manifest_id = NEW.manifest_id
       AND chunk.stream = NEW.stream AND manifest.state = 'staged'
       AND NEW.observed_day = floor(NEW.observed_at_ms / 86400000.0)::integer
       AND (SELECT count(*) FROM telemetry_v12_typed_records record WHERE record.chunk_id = chunk.id)
         < chunk.record_count
  ) THEN
    RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'telemetry_v12_typed_record_staging_denied';
  END IF;
  RETURN NEW;
END;
$$;
CREATE TRIGGER telemetry_v12_typed_record_admission
BEFORE INSERT ON telemetry_v12_typed_records
FOR EACH ROW EXECUTE FUNCTION telemetry_v12_typed_record_admission();

CREATE FUNCTION telemetry_v12_typed_child_admission() RETURNS trigger
LANGUAGE plpgsql SET search_path FROM CURRENT AS $$
DECLARE expected_stream text;
BEGIN
  expected_stream := CASE TG_TABLE_NAME
    WHEN 'telemetry_v12_typed_usage' THEN 'usage'
    WHEN 'telemetry_v12_typed_quota' THEN 'quota'
    ELSE 'session'
  END;
  IF NOT EXISTS (SELECT 1 FROM telemetry_v12_typed_records record
    WHERE record.id = NEW.record_id AND record.stream = expected_stream) THEN
    RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'telemetry_v12_typed_child_stream_conflict';
  END IF;
  RETURN NEW;
END;
$$;
CREATE TRIGGER telemetry_v12_typed_usage_admission
BEFORE INSERT ON telemetry_v12_typed_usage
FOR EACH ROW EXECUTE FUNCTION telemetry_v12_typed_child_admission();
CREATE TRIGGER telemetry_v12_typed_quota_admission
BEFORE INSERT ON telemetry_v12_typed_quota
FOR EACH ROW EXECUTE FUNCTION telemetry_v12_typed_child_admission();
CREATE TRIGGER telemetry_v12_typed_session_admission
BEFORE INSERT ON telemetry_v12_typed_session_tools
FOR EACH ROW EXECUTE FUNCTION telemetry_v12_typed_child_admission();

CREATE FUNCTION telemetry_v12_typed_row_immutable() RETURNS trigger
LANGUAGE plpgsql SET search_path FROM CURRENT AS $$
BEGIN
  RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'telemetry_v12_typed_row_immutable';
END;
$$;
CREATE TRIGGER telemetry_v12_typed_record_immutable
BEFORE UPDATE ON telemetry_v12_typed_records FOR EACH ROW EXECUTE FUNCTION telemetry_v12_typed_row_immutable();
CREATE TRIGGER telemetry_v12_typed_usage_immutable
BEFORE UPDATE ON telemetry_v12_typed_usage FOR EACH ROW EXECUTE FUNCTION telemetry_v12_typed_row_immutable();
CREATE TRIGGER telemetry_v12_typed_quota_immutable
BEFORE UPDATE ON telemetry_v12_typed_quota FOR EACH ROW EXECUTE FUNCTION telemetry_v12_typed_row_immutable();
CREATE TRIGGER telemetry_v12_typed_session_tool_immutable
BEFORE UPDATE ON telemetry_v12_typed_session_tools FOR EACH ROW EXECUTE FUNCTION telemetry_v12_typed_row_immutable();
CREATE TRIGGER typed_telemetry_dictionary_immutable
BEFORE UPDATE ON typed_telemetry_dictionary FOR EACH ROW EXECUTE FUNCTION telemetry_v12_typed_row_immutable();
CREATE TRIGGER telemetry_v12_typed_attribution_immutable
BEFORE UPDATE ON telemetry_v12_typed_attributions FOR EACH ROW EXECUTE FUNCTION telemetry_v12_typed_row_immutable();
