-- Sampled, content-free request-failure diagnostics for the PostgreSQL host.
--
-- Port of D1 migrations/0019_admin_operations.sql diagnostic_error_events.
-- A request id is the diagnostic reference returned to the caller; it is not
-- a participant identifier and is never joined to contribution or record
-- contents. The table holds no personal data. The writer
-- (src/postgres-host-diagnostics.ts) samples server failures whose request id
-- ends in "00" and caps the table at 256 rows under a transaction-scoped
-- advisory lock; scheduled maintenance prunes rows older than 30 days.
--
-- The identity is BY DEFAULT so reviewed tooling can import rows with their
-- original ids. There are no grants: the host runtime and the scheduled job
-- share one database user.

CREATE TABLE diagnostic_error_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_id text NOT NULL
    CHECK (request_id ~ '^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'),
  route_class text NOT NULL
    CHECK (char_length(route_class) BETWEEN 1 AND 80),
  error_code text NOT NULL
    CHECK (char_length(error_code) BETWEEN 1 AND 80 AND error_code ~ '^[A-Z0-9_]+$'),
  status integer NOT NULL CHECK (status BETWEEN 400 AND 599),
  occurred_at timestamptz NOT NULL
);

CREATE INDEX diagnostic_error_events_recent
  ON diagnostic_error_events(occurred_at DESC, id DESC);

CREATE INDEX diagnostic_error_events_request
  ON diagnostic_error_events(request_id, occurred_at DESC);
