-- PostgreSQL primary migration 0052 (staged): live id allocation for the
-- retained typed v1/v1.1 telemetry family.
--
-- Migration 0030 created the nine id-keyed typed tables in import shape only:
-- every id is an explicit D1 INTEGER PRIMARY KEY copied by the importer, and
-- nothing could allocate a new one. Live v1.0 and v1.1 admission needs an
-- allocator whose values stay inside the same range as the D1 rowids (the
-- existing 1..2^53-1 CHECKs, kept unchanged). Each id column therefore
-- becomes GENERATED BY DEFAULT AS IDENTITY: an importer may still write the
-- exact source id, and a live insert that omits it receives the next value.
--
-- The identity starts at 1, so rows imported with explicit ids leave it
-- behind max(id). typed_telemetry_restart_identities() moves every identity
-- to max(id)+1 (1 for an empty table); the production transfer calls it after
-- import and before routing, and it runs once below so a schema that already
-- holds imported rows is never left with a colliding allocator. It never
-- lowers an identity that has already allocated past max(id), so a value is
-- never issued twice. The Worker-side verifyPostgresTypedIdentityHeadroom
-- (src/postgres-typed-live-allocators.ts) refuses service while any next
-- value is not above max(id).
--
-- The shared typed_telemetry_dictionary keeps its 0025 identity; the importer
-- and the transfer high-water own it. Every RAISE carries a constant message.

ALTER TABLE typed_telemetry_namespaces ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
  SEQUENCE NAME typed_telemetry_namespaces_id_seq
  START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9007199254740991 NO CYCLE CACHE 1);
ALTER TABLE typed_telemetry_owners ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
  SEQUENCE NAME typed_telemetry_owners_id_seq
  START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9007199254740991 NO CYCLE CACHE 1);
ALTER TABLE typed_telemetry_devices ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
  SEQUENCE NAME typed_telemetry_devices_id_seq
  START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9007199254740991 NO CYCLE CACHE 1);
ALTER TABLE typed_telemetry_manifests ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
  SEQUENCE NAME typed_telemetry_manifests_id_seq
  START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9007199254740991 NO CYCLE CACHE 1);
ALTER TABLE typed_telemetry_chunks ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
  SEQUENCE NAME typed_telemetry_chunks_id_seq
  START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9007199254740991 NO CYCLE CACHE 1);
ALTER TABLE typed_telemetry_identifiers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
  SEQUENCE NAME typed_telemetry_identifiers_id_seq
  START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9007199254740991 NO CYCLE CACHE 1);
ALTER TABLE typed_telemetry_attributions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
  SEQUENCE NAME typed_telemetry_attributions_id_seq
  START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9007199254740991 NO CYCLE CACHE 1);
ALTER TABLE typed_telemetry_quota_dimensions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
  SEQUENCE NAME typed_telemetry_quota_dimensions_id_seq
  START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9007199254740991 NO CYCLE CACHE 1);
ALTER TABLE typed_telemetry_records ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
  SEQUENCE NAME typed_telemetry_records_id_seq
  START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9007199254740991 NO CYCLE CACHE 1);

-- Move every typed identity to the first value above its imported rows.
-- SECURITY INVOKER: ALTER TABLE needs table ownership, so only the migration
-- or schema-owner role (the transfer uses SET ROLE) can run it; the runtime
-- role is not granted EXECUTE. All nine tables are locked up front, parent
-- before child, so no explicit-id insert can land between the max(id) read
-- and the restart. Names are qualified with the pinned schema so a caller's
-- temporary relation can never be selected instead.
CREATE FUNCTION typed_telemetry_restart_identities()
RETURNS void
LANGUAGE plpgsql SECURITY INVOKER SET search_path FROM CURRENT AS $$
DECLARE
  target_schema text := pg_catalog.current_schema();
  table_names text[] := ARRAY[
    'typed_telemetry_namespaces', 'typed_telemetry_owners', 'typed_telemetry_devices',
    'typed_telemetry_manifests', 'typed_telemetry_chunks', 'typed_telemetry_identifiers',
    'typed_telemetry_attributions', 'typed_telemetry_quota_dimensions', 'typed_telemetry_records'
  ];
  table_name text;
  relation text;
  identity_sequence regclass;
  maximum bigint;
  sequence_last bigint;
  called boolean;
  pending bigint;
  next_value bigint;
BEGIN
  IF target_schema IS NULL THEN
    RAISE EXCEPTION 'typed_telemetry_identity_missing' USING ERRCODE = '55000';
  END IF;
  EXECUTE 'LOCK TABLE ' || (
    SELECT pg_catalog.string_agg(pg_catalog.format('%I.%I', target_schema, listed.listed_name), ', '
             ORDER BY listed.ordinal)
      FROM pg_catalog.unnest(table_names) WITH ORDINALITY AS listed(listed_name, ordinal)
  ) || ' IN ACCESS EXCLUSIVE MODE';
  FOREACH table_name IN ARRAY table_names LOOP
    relation := pg_catalog.format('%I.%I', target_schema, table_name);
    identity_sequence := pg_catalog.pg_get_serial_sequence(relation, 'id')::regclass;
    IF identity_sequence IS NULL THEN
      RAISE EXCEPTION 'typed_telemetry_identity_missing' USING ERRCODE = '55000';
    END IF;
    EXECUTE pg_catalog.format('SELECT pg_catalog.max(id) FROM %s', relation) INTO maximum;
    EXECUTE pg_catalog.format('SELECT last_value, is_called FROM %s', identity_sequence)
      INTO sequence_last, called;
    pending := CASE WHEN called THEN sequence_last + 1 ELSE sequence_last END;
    next_value := GREATEST(COALESCE(maximum, 0) + 1, pending);
    IF next_value > 9007199254740991 THEN
      RAISE EXCEPTION 'typed_telemetry_identity_exhausted' USING ERRCODE = '2200H';
    END IF;
    EXECUTE pg_catalog.format('ALTER TABLE %s ALTER COLUMN id RESTART WITH %s', relation, next_value);
  END LOOP;
END;
$$;
REVOKE ALL ON FUNCTION typed_telemetry_restart_identities() FROM PUBLIC;
COMMENT ON FUNCTION typed_telemetry_restart_identities() IS
  'Owner-only: restart each typed v1/v1.1 id identity at max(id)+1 (1 when empty) without lowering it.';

SELECT typed_telemetry_restart_identities();
