steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --file=apps/worker/cloud-run/Dockerfile
      - --tag=${_IMAGE}
      - .
images:
  - ${_IMAGE}
options:
  logging: CLOUD_LOGGING_ONLY
serviceAccount: projects/tibotattle/serviceAccounts/tibotattle-test-builder@tibotattle.iam.gserviceaccount.com
substitutions:
  _IMAGE: us-east1-docker.pkg.dev/tibotattle/tibotattle-test/tibotattle-host:content-digest-required
