/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=gcs-test/wrangler.jsonc --include-runtime=false --env-interface=GcsTestRuntimeEnv gcs-test/worker-configuration.d.ts` (hash: 0cf2025e0893e4bc88d086bcc6693339)
interface __BaseEnv_GcsTestRuntimeEnv {
	TEST_RELEASE_NONCES: D1Database;
	GCS_TEST_BUCKET: string;
	GCS_TEST_RUN_ID: string;
	GCS_ACCESS_TOKEN: string;
	GCS_ACCESS_TOKEN_EXPIRES_AT: string;
	GCS_TEST_RELEASE_TOKEN: string;
	GCS_TEST_PUBLIC_ED_KEY: string;
	GCS_TEST_PUBLIC_ED_KEY_SHA256: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker");
	}
	interface Env extends __BaseEnv_GcsTestRuntimeEnv {}
}
interface GcsTestRuntimeEnv extends __BaseEnv_GcsTestRuntimeEnv {}
