PRAGMA foreign_keys = ON;

-- Bind every hosted sign-in handoff to the client that initiated it. The start
-- route stores SHA-256(verifier) here, where the raw verifier is generated by
-- and never leaves the initiating client. The result route delivers the proof
-- only to a caller that re-presents that verifier, and enrollment consumes the
-- proof only when the same verifier is presented again. The unguessable state
-- alone is therefore no longer a bearer capability: a state that leaks through
-- the provider round-trip, browser history, a referrer, or a log cannot be
-- redeemed by any party that does not also hold the initiator's verifier.
--
-- The column is added nullable so this is a forward-only rebuild that keeps the
-- existing rows: any handoff already in flight has a NULL binding and is
-- therefore unbound. The result and enrollment queries require a matching
-- binding_hash, so every such outstanding unbound handoff becomes undeliverable
-- and is purged on its normal five-minute expiry — it can simply be restarted.
ALTER TABLE apple_signin_handoffs ADD COLUMN binding_hash TEXT
  CHECK (binding_hash IS NULL OR (
    length(binding_hash) = 64
    AND binding_hash NOT GLOB '*[^0-9a-f]*'
  ));

ALTER TABLE google_signin_handoffs ADD COLUMN binding_hash TEXT
  CHECK (binding_hash IS NULL OR (
    length(binding_hash) = 64
    AND binding_hash NOT GLOB '*[^0-9a-f]*'
  ));
