import assert from "node:assert/strict";
import {
  mkdtemp,
  readFile,
  readdir,
  rm,
} from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";

import * as canonicalTelemetry
  from "../../../packages/telemetry-contract/index.js";
import {
  TELEMETRY_BROWSER_MIRROR_FILE,
  buildTelemetryBrowserMirror,
  checkTelemetryBrowserMirror,
  readVerifiedTelemetryBrowserMirror,
  verifyTelemetryBrowserMirrorSource,
  writeTelemetryBrowserMirror,
} from "../../../scripts/generate-telemetry-browser-mirror.js";
import {
  telemetryContractAdversarialVectors,
  telemetryV01Golden,
  telemetryV02Golden,
  telemetryV02LegacyIdGolden,
} from "../../../test/fixtures/telemetry-contract-vectors.mjs";
import * as browserCryptoAdapter from "../public/telemetry-envelope.js";
import * as browserTelemetry from "../public/telemetry-shared.generated.js";
import * as publicLibrary from "../public/lib.js";

const VALIDATION_COMPATIBILITY_EXPORTS = Object.freeze([
  "ACCOUNT_SCOPED_TELEMETRY_CONSENT_VERSION",
  "ACCOUNT_SCOPED_TELEMETRY_SCHEMA_VERSION",
  "MAX_TELEMETRY_BROWSER_BYTES",
  "TELEMETRY_ENVELOPE_SCHEMA_VERSION",
  "TELEMETRY_SCHEMA_VERSION",
  "validateAccountScopedTelemetryContribution",
  "validateContributionForUpload",
  "validateTelemetryContribution",
]);

const CRYPTO_ADAPTER_EXPORTS = Object.freeze([
  "ENVELOPE_SCHEMA_VERSION",
  "SYNTHETIC_SCHEMA_VERSION",
  "buildSyntheticFixture",
  "bytesToBase64Url",
  "createSyntheticEnvelope",
  "createTelemetryEnvelope",
  "validateSyntheticFixture",
]);

function stableContractOutcome(operation) {
  try {
    return {
      outcome: "returned",
      value: operation(),
    };
  } catch (error) {
    return {
      outcome: "threw",
      name: error?.name,
      code: error?.code ?? null,
      detailCode: error?.detailCode ?? null,
    };
  }
}

async function stableContractOutcomeAsync(operation) {
  try {
    return {
      outcome: "returned",
      value: await operation(),
    };
  } catch (error) {
    return {
      outcome: "threw",
      name: error?.name,
      code: error?.code ?? null,
      detailCode: error?.detailCode ?? null,
    };
  }
}

function deterministicCrypto({ plaintexts = [] } = {}) {
  return {
    getRandomValues(bytes) {
      bytes.fill(11);
      return bytes;
    },
    subtle: {
      async importKey() {
        return { kind: "wrapping-key" };
      },
      async generateKey() {
        return { kind: "payload-key" };
      },
      async encrypt(algorithm, _key, data) {
        const input = new Uint8Array(data);
        if (algorithm.name === "AES-GCM") {
          plaintexts.push(new TextDecoder().decode(input));
          return Uint8Array.from([0xa5, ...input.slice(0, 7)]).buffer;
        }
        return Uint8Array.from([0xb6, ...input.slice(0, 4)]).buffer;
      },
      async exportKey() {
        return Uint8Array.from([1, 2, 3, 4]).buffer;
      },
    },
  };
}

function deferredCrypto({ plaintexts = [] } = {}) {
  let releaseImport;
  let importStarted;
  const importGate = new Promise((resolve) => {
    releaseImport = resolve;
  });
  const importStartedGate = new Promise((resolve) => {
    importStarted = resolve;
  });
  return {
    plaintexts,
    releaseImport() {
      releaseImport();
    },
    importStarted: importStartedGate,
    cryptoImpl: {
      getRandomValues(bytes) {
        bytes.fill(11);
        return bytes;
      },
      subtle: {
        importKey() {
          importStarted();
          return importGate.then(() => ({ kind: "wrapping-key" }));
        },
        async generateKey() {
          return { kind: "payload-key" };
        },
        async encrypt(algorithm, _key, data) {
          const input = new Uint8Array(data);
          if (algorithm.name === "AES-GCM") {
            plaintexts.push(new TextDecoder().decode(input));
            return Uint8Array.from([0xa5, ...input.slice(0, 7)]).buffer;
          }
          return Uint8Array.from([0xb6, ...input.slice(0, 4)]).buffer;
        },
        async exportKey() {
          return Uint8Array.from([1, 2, 3, 4]).buffer;
        },
      },
    },
  };
}

function encryptionOptions(payload, cryptoImpl) {
  return {
    payload,
    publicJwk: { kty: "RSA", n: "safe", e: "AQAB" },
    keyId: "key:parity",
    cryptoImpl,
  };
}

test("the browser telemetry mirror is deterministic and current", async () => {
  const [actual, firstBuild, secondBuild] = await Promise.all([
    readFile(TELEMETRY_BROWSER_MIRROR_FILE, "utf8"),
    buildTelemetryBrowserMirror(),
    buildTelemetryBrowserMirror(),
  ]);
  assert.equal(firstBuild, secondBuild);
  assert.equal(actual, firstBuild);
  assert.match(
    actual,
    /^\/\/ @generated by scripts\/generate-telemetry-browser-mirror\.js\n/u,
  );
  assert.equal(await checkTelemetryBrowserMirror(), true);
});

test("the browser telemetry mirror verifier returns a frozen captured string record", async () => {
  const sourceText = await readFile(TELEMETRY_BROWSER_MIRROR_FILE, "utf8");
  const [direct, captured] = await Promise.all([
    verifyTelemetryBrowserMirrorSource(sourceText),
    readVerifiedTelemetryBrowserMirror(),
  ]);
  assert.equal(Object.isFrozen(direct), true);
  assert.equal(Object.isFrozen(captured), true);
  assert.equal(typeof captured.sourceText, "string");
  assert.equal(Buffer.isBuffer(captured.sourceText), false);
  assert.equal(direct.sourceText, sourceText);
  assert.equal(captured.sha256, direct.sha256);
  assert.equal(captured.byteLength, Buffer.byteLength(sourceText, "utf8"));
});

test("the browser telemetry mirror writer publishes one complete durable file", async (t) => {
  const directory = await mkdtemp(join(tmpdir(), "telemetry-browser-mirror-"));
  t.after(() => rm(directory, { recursive: true, force: true }));
  const outputFile = join(directory, "telemetry-shared.generated.js");

  await writeTelemetryBrowserMirror({ outputFile });

  assert.equal(
    await readFile(outputFile, "utf8"),
    await buildTelemetryBrowserMirror(),
  );
  assert.deepEqual(await readdir(directory), [
    "telemetry-shared.generated.js",
  ]);
});

test("the browser mirror exposes the canonical package contract", () => {
  assert.deepEqual(
    Object.keys(browserTelemetry),
    Object.keys(canonicalTelemetry),
  );
  for (const name of Object.keys(canonicalTelemetry)) {
    if (typeof canonicalTelemetry[name] !== "function") {
      assert.deepEqual(
        browserTelemetry[name],
        canonicalTelemetry[name],
        `${name} drifted from the canonical package`,
      );
    }
  }
});

test("public lib keeps validation and crypto adapter compatibility exports", () => {
  for (const name of VALIDATION_COMPATIBILITY_EXPORTS) {
    assert.equal(
      publicLibrary[name],
      browserTelemetry[name],
      `${name} must remain a direct browser-mirror re-export`,
    );
  }
  for (const name of CRYPTO_ADAPTER_EXPORTS) {
    assert.equal(
      publicLibrary[name],
      browserCryptoAdapter[name],
      `${name} must remain a direct crypto-adapter re-export`,
    );
  }
  for (const module of [
    canonicalTelemetry,
    browserTelemetry,
    browserCryptoAdapter,
    publicLibrary,
  ]) {
    assert.equal(
      Object.hasOwn(module, "createEncryptedEnvelope"),
      false,
      "raw arbitrary-payload encryption must not be a public client API",
    );
  }
});

test("canonical and browser validators accept the frozen golden payloads", () => {
  for (const [label, payload] of [
    ["v0.1", telemetryV01Golden()],
    ["v0.2", telemetryV02Golden()],
    ["v0.2 legacy IDs", telemetryV02LegacyIdGolden()],
  ]) {
    const canonical = stableContractOutcome(() =>
      canonicalTelemetry.validateContributionForUpload(payload));
    const browser = stableContractOutcome(() =>
      browserTelemetry.validateContributionForUpload(payload));
    assert.deepEqual(
      canonical,
      { outcome: "returned", value: true },
      `${label}: canonical package rejected its golden vector`,
    );
    assert.deepEqual(
      browser,
      canonical,
      `${label}: browser mirror drifted from the canonical package`,
    );
  }
});

test("canonical and browser validators preserve stable adversarial error codes", () => {
  for (const vector of telemetryContractAdversarialVectors()) {
    const expected = {
      outcome: "threw",
      name: "TypeError",
      code: vector.code,
      detailCode: vector.detailCode,
    };
    const canonical = stableContractOutcome(() =>
      canonicalTelemetry.validateContributionForUpload(vector.value));
    const browser = stableContractOutcome(() =>
      browserTelemetry.validateContributionForUpload(vector.value));
    assert.deepEqual(
      canonical,
      expected,
      `${vector.label}: canonical stable error changed`,
    );
    assert.deepEqual(
      browser,
      expected,
      `${vector.label}: browser stable error drifted`,
    );
    for (const validate of [
      canonicalTelemetry.validateContributionForUpload,
      browserTelemetry.validateContributionForUpload,
    ]) {
      assert.throws(
        () => validate(vector.value),
        (error) => {
          assert.equal(
            String(error?.message).includes("private-content-canary"),
            false,
            `${vector.label}: error message leaked fixture content`,
          );
          return true;
        },
      );
    }
  }
});

test("the crypto adapter validates real payloads through the browser mirror", async () => {
  for (const vector of telemetryContractAdversarialVectors()) {
    const canonical = stableContractOutcome(() =>
      canonicalTelemetry.validateContributionForUpload(vector.value));
    const adapter = await stableContractOutcomeAsync(() =>
      browserCryptoAdapter.createTelemetryEnvelope(
        encryptionOptions(vector.value, deterministicCrypto()),
      ));
    assert.deepEqual(
      adapter,
      canonical,
      `${vector.label}: crypto adapter did not preserve stable validation errors`,
    );
  }
});

test("the crypto adapter preserves injected crypto and real payload bytes", async () => {
  const payload = telemetryV01Golden();
  const plaintexts = [];
  const envelope = await browserCryptoAdapter.createTelemetryEnvelope(
    encryptionOptions(payload, deterministicCrypto({ plaintexts })),
  );

  assert.deepEqual(plaintexts, [JSON.stringify(payload)]);
  assert.deepEqual(Object.keys(envelope), [
    "schemaVersion",
    "synthetic",
    "keyId",
    "wrappedKey",
    "iv",
    "ciphertext",
  ]);
  assert.equal(envelope.schemaVersion, "telemetry-envelope-v0.1");
  assert.equal(envelope.synthetic, false);
  assert.equal("payload" in envelope, false);
  assert.deepEqual(
    await publicLibrary.createTelemetryEnvelope(
      encryptionOptions(payload, deterministicCrypto()),
    ),
    envelope,
  );

  for (const [bytes, expected] of [
    [new Uint8Array([]), ""],
    [new TextEncoder().encode("foo"), "Zm9v"],
    [new Uint8Array([251, 255]), "-_8"],
  ]) {
    assert.equal(browserCryptoAdapter.bytesToBase64Url(bytes), expected);
  }
});

test("the browser crypto adapter preserves the v0.2 payload snapshot", async () => {
  const payload = telemetryV02Golden();
  const plaintexts = [];
  const envelope = await browserCryptoAdapter.createTelemetryEnvelope(
    encryptionOptions(payload, deterministicCrypto({ plaintexts })),
  );

  assert.equal(envelope.schemaVersion, "telemetry-envelope-v0.1");
  assert.equal(envelope.synthetic, false);
  assert.deepEqual(plaintexts, [JSON.stringify(payload)]);
});

test("the browser adapter snapshots and validates bytes before deferred crypto", async () => {
  const payload = telemetryV01Golden();
  const expectedPlaintext = JSON.stringify(payload);
  const deferred = deferredCrypto();
  const pending = browserCryptoAdapter.createTelemetryEnvelope(
    encryptionOptions(payload, deferred.cryptoImpl),
  );

  // This happens immediately after invocation, while importKey is still held.
  payload.usageEvents[0].prompt = "private-content-canary";
  payload.usageEvents[0].components.outputTextTokens = 999_999;
  await deferred.importStarted;
  assert.deepEqual(deferred.plaintexts, []);
  deferred.releaseImport();
  await pending;

  assert.deepEqual(deferred.plaintexts, [expectedPlaintext]);
  assert.equal(
    deferred.plaintexts[0].includes("private-content-canary"),
    false,
  );
});

test("the browser adapter validates the parsed getter snapshot, not later caller state", async () => {
  const payload = telemetryV01Golden();
  const usageEvents = payload.usageEvents;
  const expectedPlaintext = JSON.stringify(payload);
  Object.defineProperty(payload, "usageEvents", {
    configurable: true,
    enumerable: true,
    get() {
      // JSON has already captured the root key list. This must not leak into
      // the frozen plaintext snapshot or cause a later raw-object validation.
      payload.privateContent = "private-content-canary";
      return usageEvents;
    },
  });
  const deferred = deferredCrypto();
  const pending = browserCryptoAdapter.createTelemetryEnvelope(
    encryptionOptions(payload, deferred.cryptoImpl),
  );

  await deferred.importStarted;
  assert.equal(payload.privateContent, "private-content-canary");
  deferred.releaseImport();
  await pending;

  assert.deepEqual(deferred.plaintexts, [expectedPlaintext]);
  assert.equal(
    deferred.plaintexts[0].includes("private-content-canary"),
    false,
  );
});

test("the browser adapter rejects forbidden data emitted by a getter before crypto", async () => {
  let cryptoReads = 0;
  const cryptoImpl = new Proxy({}, {
    get() {
      cryptoReads += 1;
      throw new Error("Web Crypto must not be reached");
    },
  });
  const payload = telemetryV01Golden();
  const usageEvents = payload.usageEvents;
  Object.defineProperty(payload, "usageEvents", {
    configurable: true,
    enumerable: true,
    get() {
      return [{ ...usageEvents[0], prompt: "private-content-canary" }];
    },
  });

  await assert.rejects(
    browserCryptoAdapter.createTelemetryEnvelope(
      encryptionOptions(payload, cryptoImpl),
    ),
    (error) => error?.code === "PRIVACY_CANARY_DETECTED",
  );
  assert.equal(cryptoReads, 0);
});

test("the browser adapter normalizes serialization faults before crypto", async () => {
  let cryptoReads = 0;
  const cryptoImpl = new Proxy({}, {
    get() {
      cryptoReads += 1;
      throw new Error("Web Crypto must not be reached");
    },
  });
  const payload = new Proxy(telemetryV01Golden(), {
    get(target, property, receiver) {
      if (property === "toJSON") {
        throw new Error("private-content-canary");
      }
      return Reflect.get(target, property, receiver);
    },
  });

  await assert.rejects(
    browserCryptoAdapter.createTelemetryEnvelope(
      encryptionOptions(payload, cryptoImpl),
    ),
    {
      name: "TypeError",
      message: "Telemetry payload serialization failed.",
    },
  );
  assert.equal(cryptoReads, 0);
});

test("the crypto adapter preserves the exact fixed synthetic fixture", async () => {
  const expected = JSON.parse(await readFile(
    new URL(
      "../../../test/fixtures/product-synthetic-contribution-v0.1.json",
      import.meta.url,
    ),
    "utf8",
  ));
  const fixture = browserCryptoAdapter.buildSyntheticFixture();
  assert.equal(JSON.stringify(fixture), JSON.stringify(expected));
  assert.equal(browserCryptoAdapter.validateSyntheticFixture(fixture), true);

  const modified = structuredClone(fixture);
  modified.quota.usedPercentAfter += 1;
  assert.throws(
    () => browserCryptoAdapter.validateSyntheticFixture(modified),
    {
      name: "TypeError",
      message: "The synthetic fixture must not be modified.",
    },
  );
  const reordered = structuredClone(fixture);
  const schemaVersion = reordered.schemaVersion;
  delete reordered.schemaVersion;
  reordered.schemaVersion = schemaVersion;
  assert.throws(
    () => browserCryptoAdapter.validateSyntheticFixture(reordered),
    {
      name: "TypeError",
      message: "The synthetic fixture must not be modified.",
    },
  );
  assert.throws(
    () => browserCryptoAdapter.validateSyntheticFixture({
      ...fixture,
      schemaVersion: "synthetic-contribution-v0.2",
    }),
    {
      name: "TypeError",
      message: "Only the fixed synthetic fixture can be contributed.",
    },
  );

  const plaintexts = [];
  const envelope = await browserCryptoAdapter.createSyntheticEnvelope({
    publicJwk: { kty: "RSA", n: "safe", e: "AQAB" },
    keyId: "key:synthetic-parity",
    cryptoImpl: deterministicCrypto({ plaintexts }),
  });
  assert.equal(envelope.schemaVersion, "synthetic-envelope-v0.1");
  assert.equal(envelope.synthetic, true);
  assert.deepEqual(plaintexts, [JSON.stringify(expected)]);
});

test("the crypto adapter fails closed before attempting encryption", async () => {
  await assert.rejects(
    browserCryptoAdapter.createTelemetryEnvelope(
      encryptionOptions(telemetryV01Golden(), null),
    ),
    {
      name: "Error",
      message: "Web Crypto is unavailable in this browser.",
    },
  );
  await assert.rejects(
    browserCryptoAdapter.createTelemetryEnvelope({
      ...encryptionOptions(telemetryV01Golden(), deterministicCrypto()),
      keyId: "not-a-key-id",
    }),
    {
      name: "TypeError",
      message: "A public JWK and key ID are required.",
    },
  );
  const maximumKeyId = `key:${"a".repeat(64)}`;
  assert.equal(
    (
      await browserCryptoAdapter.createTelemetryEnvelope({
        ...encryptionOptions(telemetryV01Golden(), deterministicCrypto()),
        keyId: maximumKeyId,
      })
    ).keyId,
    maximumKeyId,
  );
  await assert.rejects(
    browserCryptoAdapter.createTelemetryEnvelope({
      ...encryptionOptions(telemetryV01Golden(), deterministicCrypto()),
      keyId: `key:${"a".repeat(65)}`,
    }),
    {
      name: "TypeError",
      message: "A public JWK and key ID are required.",
    },
  );
});
