-- Synthetic empty schema generated by v0.1.16 src/local-unified-index.js.
-- Original source is in Git history; no user data.
PRAGMA application_id=1431131465;
PRAGMA user_version=8;
PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE meta(
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL) STRICT;
INSERT INTO meta VALUES('schema_version','local-unified-index-v2');
CREATE TABLE parser_version(
    id INTEGER PRIMARY KEY,
    parser_version TEXT NOT NULL,
    contract_version TEXT NOT NULL,
    UNIQUE(parser_version, contract_version)) STRICT;
CREATE TABLE ingest_run(
    id INTEGER PRIMARY KEY,
    received_at_ms INTEGER NOT NULL,
    parser_version_id INTEGER NOT NULL REFERENCES parser_version) STRICT;
CREATE TABLE index_generation(
    id INTEGER PRIMARY KEY,
    started_at_ms INTEGER NOT NULL,
    completed_at_ms INTEGER,
    parser_version_id INTEGER NOT NULL REFERENCES parser_version,
    contract_version TEXT NOT NULL,
    status TEXT NOT NULL CHECK(status IN
      ('in_progress', 'complete', 'partial', 'failed')),
    block_reason TEXT,
    discovered_source_count INTEGER,
    discovered_source_bytes INTEGER,
    indexed_source_count INTEGER,
    indexed_source_bytes INTEGER,
    usage_events INTEGER,
    quota_occurrences INTEGER,
    covered_start_ms INTEGER,
    covered_end_ms INTEGER,
    discovery_complete INTEGER NOT NULL DEFAULT 0
      CHECK(discovery_complete IN (0, 1)),
    diagnostics_complete INTEGER NOT NULL DEFAULT 0
      CHECK(diagnostics_complete IN (0, 1)),
    usage_provenance_complete INTEGER NOT NULL DEFAULT 0
      CHECK(usage_provenance_complete IN (0, 1)),
    source_order_complete INTEGER NOT NULL DEFAULT 0
      CHECK(source_order_complete IN (0, 1)),
    quota_provenance_complete INTEGER NOT NULL DEFAULT 0
      CHECK(quota_provenance_complete IN (0, 1)),
    tool_facts INTEGER,
    tool_fact_fingerprint TEXT,
    tool_provenance_complete INTEGER NOT NULL DEFAULT 0
      CHECK(tool_provenance_complete IN (0, 1))) STRICT;
CREATE TABLE model(
    id INTEGER PRIMARY KEY,
    model_id TEXT NOT NULL UNIQUE,
    recognition TEXT NOT NULL) STRICT;
CREATE TABLE tier_semantics(
    id INTEGER PRIMARY KEY,
    api_service_tier TEXT NOT NULL,
    billing_surface TEXT NOT NULL,
    codex_speed_mode TEXT NOT NULL,
    tier_source TEXT NOT NULL,
    provider_tier_raw TEXT,
    UNIQUE(api_service_tier, billing_surface, codex_speed_mode,
           tier_source, provider_tier_raw)) STRICT;
CREATE TABLE surface_class(
    id INTEGER PRIMARY KEY,
    agent_scope TEXT NOT NULL,
    surface TEXT NOT NULL,
    thread_source TEXT NOT NULL,
    lineage_disposition TEXT NOT NULL,
    UNIQUE(agent_scope, surface, thread_source, lineage_disposition)) STRICT;
CREATE TABLE account_scope(
    id INTEGER PRIMARY KEY,
    status TEXT NOT NULL,
    reason TEXT,
    plan_type TEXT,
    scope_local BLOB,
    UNIQUE(status, reason, plan_type, scope_local)) STRICT;
CREATE TABLE source_dimension(
    id INTEGER PRIMARY KEY,
    source_local BLOB NOT NULL UNIQUE) STRICT;
CREATE TABLE quota_observation(
    id INTEGER PRIMARY KEY,
    observed_at_ms INTEGER NOT NULL,
    limit_id TEXT NOT NULL,
    slot TEXT NOT NULL,
    plan_type TEXT,
    used_percent REAL,
    resets_at_ms INTEGER,
    duration_mins INTEGER,
    UNIQUE(observed_at_ms, limit_id, slot)) STRICT;
CREATE TABLE quota_occurrence(
    id INTEGER PRIMARY KEY,
    generation_id INTEGER REFERENCES index_generation,
    source_local BLOB NOT NULL CHECK(length(source_local) = 32),
    source_offset INTEGER NOT NULL CHECK(source_offset >= 0),
    source_ordinal INTEGER NOT NULL CHECK(source_ordinal >= 0),
    surface_id INTEGER NOT NULL REFERENCES surface_class,
    canonical_observation_id INTEGER NOT NULL REFERENCES quota_observation,
    observed_at_ms INTEGER NOT NULL,
    provider TEXT NOT NULL,
    plan_type TEXT,
    limit_id TEXT NOT NULL,
    slot TEXT NOT NULL,
    slot_order INTEGER NOT NULL CHECK(slot_order >= 0),
    used_percent REAL NOT NULL CHECK(used_percent >= 0 AND used_percent <= 100),
    resets_at_ms INTEGER,
    duration_mins INTEGER NOT NULL CHECK(duration_mins >= 1),
    admission TEXT NOT NULL CHECK(admission IN
      ('admitted', 'held', 'suppressed')),
    UNIQUE(source_local, source_offset, slot_order)) STRICT;
CREATE TABLE usage_event(
    event_key BLOB PRIMARY KEY,
    observed_at_ms INTEGER NOT NULL,
    generation_id INTEGER REFERENCES index_generation,
    ingest_run_id INTEGER NOT NULL REFERENCES ingest_run,
    parser_version_id INTEGER NOT NULL REFERENCES parser_version,
    -- NULL only on retained rows from a parser/schema that predates exact
    -- source ordering. Current-parser writers always set both fields.
    source_id INTEGER REFERENCES source_dimension,
    session_local BLOB NOT NULL,
    account_scope_id INTEGER NOT NULL REFERENCES account_scope,
    model_id INTEGER NOT NULL REFERENCES model,
    tier_id INTEGER NOT NULL REFERENCES tier_semantics,
    surface_id INTEGER NOT NULL REFERENCES surface_class,
    quota_observation_id INTEGER REFERENCES quota_observation,
    source_local BLOB CHECK(source_local IS NULL OR length(source_local) = 32),
    source_offset INTEGER CHECK(source_offset IS NULL OR source_offset >= 0),
    source_ordinal INTEGER CHECK(source_ordinal IS NULL OR source_ordinal >= 0),
    tier_observed_at_ms INTEGER,
    reasoning_effort INTEGER NOT NULL,
    outcome INTEGER NOT NULL,
    -- Token counts. Integers only. No prompt, reply, reasoning or file content
    -- is read, parsed or stored anywhere in this schema.
    tokens_in_uncached INTEGER,
    tokens_in_cache_read INTEGER,
    tokens_in_cache_write INTEGER,
    tokens_in_cache_write_5m INTEGER,
    tokens_in_cache_write_1h INTEGER,
    tokens_out_text INTEGER,
    tokens_out_reasoning INTEGER,
    tokens_out_combined INTEGER,
    total_input_context INTEGER) STRICT;
CREATE TABLE usage_event_boundary(
    current_event_key BLOB PRIMARY KEY
      REFERENCES usage_event(event_key) ON DELETE CASCADE,
    compaction_before INTEGER NOT NULL CHECK(compaction_before IN (0, 1)),
    turn_context_before INTEGER NOT NULL CHECK(turn_context_before IN (0, 1)),
    compacted_at_ms INTEGER,
    ingest_run_id INTEGER NOT NULL REFERENCES ingest_run,
    parser_version_id INTEGER NOT NULL REFERENCES parser_version,
    session_local BLOB NOT NULL,
    CHECK(compaction_before = (compacted_at_ms IS NOT NULL)),
    CHECK(compaction_before = 1 OR turn_context_before = 1)) STRICT;
CREATE TABLE tool_class_count(
    session_local BLOB NOT NULL,
    tool_class TEXT NOT NULL,
    count INTEGER NOT NULL,
    PRIMARY KEY(session_local, tool_class)) STRICT, WITHOUT ROWID;
CREATE TABLE tool_class_fact(
    event_key BLOB PRIMARY KEY CHECK(length(event_key) = 32),
    generation_id INTEGER NOT NULL REFERENCES index_generation ON DELETE CASCADE,
    source_local BLOB NOT NULL CHECK(length(source_local) = 32),
    source_offset INTEGER NOT NULL CHECK(source_offset >= 0),
    source_ordinal INTEGER NOT NULL CHECK(source_ordinal >= 0),
    session_local BLOB NOT NULL CHECK(length(session_local) = 32),
    observed_at_ms INTEGER NOT NULL,
    tool_ordinal INTEGER NOT NULL CHECK(tool_ordinal >= 0),
    tool_class TEXT NOT NULL CHECK(length(tool_class) BETWEEN 1 AND 64),
    source_kind TEXT NOT NULL CHECK(length(source_kind) BETWEEN 1 AND 64),
    UNIQUE(source_local, source_offset, tool_ordinal)) STRICT;
CREATE TABLE source_cursor(
    source_local BLOB PRIMARY KEY,     -- HMAC(device_salt, rollout key)
    source_ordinal INTEGER CHECK(source_ordinal IS NULL OR source_ordinal >= 0),
    session_local BLOB,
    scanned_bytes INTEGER NOT NULL,
    size_bytes INTEGER NOT NULL,
    mtime_ms INTEGER NOT NULL,
    -- 1 when this source's whole fork-replay snapshot set is durably in
    -- lineage_snapshot. A source scanned before anything forked from it was
    -- never asked to collect one; when a fork of it later appears, the
    -- incremental pass re-scans it once to build the set, then flips this.
    snapshots_persisted INTEGER NOT NULL,
    turn_context_seen INTEGER NOT NULL,
    carry_model TEXT,
    carry_effort TEXT,
    carry_tier_raw TEXT,
    carry_tier_observed_at_ms INTEGER, -- NULL means no tier state carried
    carry_total_input INTEGER,
    carry_total_cached INTEGER,
    carry_total_cache_write INTEGER,
    carry_total_output INTEGER,
    carry_total_reasoning INTEGER,
    carry_total_total INTEGER,
    ingest_run_id INTEGER NOT NULL REFERENCES ingest_run) STRICT;
CREATE TABLE source_boundary_state(
    source_local BLOB PRIMARY KEY
      REFERENCES source_cursor(source_local) ON DELETE CASCADE,
    compacted_at_ms INTEGER,
    source_offset INTEGER,
    turn_context_pending INTEGER NOT NULL
      CHECK(turn_context_pending IN (0, 1)),
    ingest_run_id INTEGER NOT NULL REFERENCES ingest_run,
    CHECK((compacted_at_ms IS NULL) = (source_offset IS NULL)),
    CHECK(compacted_at_ms IS NOT NULL OR turn_context_pending = 1)) STRICT;
CREATE TABLE lineage_snapshot(
    session_local BLOB NOT NULL,
    snapshot_local BLOB NOT NULL,
    PRIMARY KEY(session_local, snapshot_local)) STRICT, WITHOUT ROWID;
CREATE TABLE session_identity(
    session_local BLOB PRIMARY KEY,
    session_uuid TEXT NOT NULL) STRICT;
CREATE TABLE generation_source(
    generation_id INTEGER NOT NULL REFERENCES index_generation ON DELETE CASCADE,
    source_local BLOB NOT NULL CHECK(length(source_local) = 32),
    source_ordinal INTEGER NOT NULL CHECK(source_ordinal >= 0),
    session_local BLOB,
    surface_id INTEGER NOT NULL REFERENCES surface_class,
    status TEXT NOT NULL CHECK(status IN
      ('pending', 'skipped', 'touched', 'resumed', 'rescanned', 'complete', 'failed')),
    discovered_size_bytes INTEGER NOT NULL CHECK(discovered_size_bytes >= 0),
    scanned_bytes INTEGER NOT NULL CHECK(scanned_bytes >= 0),
    mtime_ms INTEGER NOT NULL,
    diagnostics_complete INTEGER NOT NULL DEFAULT 0
      CHECK(diagnostics_complete IN (0, 1)),
    PRIMARY KEY(generation_id, source_local)) STRICT, WITHOUT ROWID;
CREATE TABLE source_diagnostic(
    generation_id INTEGER NOT NULL REFERENCES index_generation ON DELETE CASCADE,
    source_local BLOB NOT NULL CHECK(length(source_local) = 32),
    code TEXT NOT NULL CHECK(code IN (
      'relevantLines', 'malformedLines', 'malformedTimestamps',
      'partialLines', 'salvagedRecords', 'turnContexts', 'tokenCounts',
      'forkReplayEventsSkipped', 'unattributedForkReplayEventsSkipped',
      'cumulativeCounterRegressions', 'tierEvents', 'modelSeededFromLineage',
      'tierSeededFromLineage', 'modelMissing', 'oversizedLines',
      'contradictedLeadingSnapshotsSkipped', 'toolRecords', 'toolEvents',
      'toolRecordsSkipped', 'toolSourceHistoryUnavailable')),
    count INTEGER NOT NULL CHECK(count >= 0),
    PRIMARY KEY(generation_id, source_local, code)) STRICT, WITHOUT ROWID;
CREATE INDEX usage_event_observed
    ON usage_event(observed_at_ms);
CREATE INDEX usage_event_session
    ON usage_event(session_local);
CREATE INDEX usage_event_boundary_session
    ON usage_event_boundary(session_local);
CREATE INDEX usage_event_replay_order
    ON usage_event(observed_at_ms, source_ordinal, source_local,
                   source_offset, event_key);
CREATE INDEX quota_occurrence_canonical
    ON quota_occurrence(canonical_observation_id);
CREATE INDEX quota_occurrence_replay_order
    ON quota_occurrence(observed_at_ms, source_ordinal, source_local,
                        source_offset, slot_order, id);
CREATE INDEX tool_class_fact_generation
    ON tool_class_fact(generation_id, event_key);
CREATE INDEX tool_class_fact_source
    ON tool_class_fact(source_local);
COMMIT;
